### ISSUE TITLE
Restore from backup failure after backup has been re-created from another session

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#22036] opened 2022-05-03 14:57 UTC
### Steps to reproduce

1. Create a new account from web
2. Set up secure backup (eventually create an e2ee room with some messages to have something to backup)
3. Keep the created session and use another private/context tab to log in the same account from another web
4. Verify the second session using the passphrase from 2
5. On the second session, go to Settings > Security & Privacy and then delete the backup
5. Still on the second session create a new backup (you will be prompt to enter passphrase again)
6. Now go back to the first session
7. go to Settings > Security & Privacy and then tap on Restore from backup.
8. Enter the passphrase

**Actual:**
After you entered sucessfully the passphrase you'll see this dialog
![image](https://user-images.githubusercontent.com/9841565/166478214-981191bb-25ee-4308-a534-10dca2aece4d.png)

It looks like the `legacy`dialog to enter the megolm backup key (not the 4S)

**Expected:**
It should just import your keys.

**Worth Noting:**
If you go back and try again to restore from backup it will work.

Notes:
It's a case of desynchronised 4S and local cached key. When you try to restore you already have a megolm backup key known locally in cache but it's outdated.

### Operating system

macOS

### Browser information

FF

### URL for webapp

develop.element.io

### Application version

Element version: 850a250cea91-react-3e31fdb6a71f-js-d190cdc307f1 Olm version: 3.2.8

### Homeserver

local synapse

### Will you send logs?

No

**Comment by richvdh** [comment] 2024-10-23 14:16
I wonder if this is still a thing. Given most of the code has been rewritten, it may well not be. We should re-triage it.

**Comment by richvdh** [comment] 2024-10-31 11:44
I think this is actually a duplicate of https://github.com/element-hq/element-web/issues/27469.

**Closed by richvdh** 2024-10-31 11:44 UTC
Labels: T-Defect, S-Minor, A-E2EE, A-E2EE-Key-Backup, O-Uncommon
