### ISSUE TITLE
Issue: "Unable to decrypt message" in all private rooms

### ISSUE THREAD

**Issue by blonchkman** [element-hq/element-web#27112] opened 2024-03-05 03:44 UTC
### Steps to reproduce

Dear all,
Sorry to come back to the subject: I rarely communicate in private rooms and have noticed that I can no longer access messages in these rooms since between February 13 and 28.
I don't know what happened and can't describe how to reproduce. I have this problem with Element-desktop on three systems that I maintain. On Android, it works fine. 
I've tried the following fix on each machine without any success:
- Close the session
- Open a new session with my login and password
- Validate the new session with android

I'm not particularly comfortable with encryption and, after searching the web quite a bit, I'm now out of ideas. I'd be grateful if you could provide me with a link or a tip that might help. 

Kindest regards

#### What did you expect?
I expect to communicate normally in private rooms.

#### What happened instead?
All incoming and outgoing messages are marked with a simple "Unable to decrypt message" without further clarification.

### Operating system

Ubuntu 22.04, Ubuntu 20.04 and Debian 12.5

### Application version

Element version: 1.11.59 
Crypto version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1

### How did you install the app?

https://element.io/download#linux

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-03-05 08:39
Duplicate of https://github.com/element-hq/element-meta/issues/245

**Closed by t3chguy** 2024-03-05 08:39 UTC
Labels: T-Defect
