### ISSUE TITLE
element-desktop wrong room list height calculation

### ISSUE THREAD

**Issue by 532910** [element-hq/element-web#14655] opened 2020-07-20 14:29 UTC
I don't know how to reproduce this.

![image](https://user-images.githubusercontent.com/14617699/87949330-8f913580-caae-11ea-9cb4-db9b055e0069.png)

```
% apt policy element-desktop    
element-desktop:
  Installed: 1.7.1
  Candidate: 1.7.1
  Version table:
 *** 1.7.1 500
        500 https://packages.riot.im/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by t3chguy** [comment] 2023-07-10 13:59
Doesn't look like a bug, looks like your sections are simply shrunk to not fill the space.

1. People isn't fully expanded
2. Low priority is collapsed

This matches expectations as designed

**Comment by 532910** [comment] 2023-07-11 04:33
This is a bug, as it allows to scroll the whitespace at the end.

**Comment by t3chguy** [comment] 2024-01-31 09:43
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.

**Closed by t3chguy** 2024-01-31 09:43 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, A-Room-List
