### ISSUE TITLE
Unable to restore session after upgrade

### ISSUE THREAD

**Issue by tim-seoss** [element-hq/element-web#27941] opened 2024-08-22 09:32 UTC
### Steps to reproduce

Updated via Debian package update `element-desktop:amd64` version `1.11.71` to `1.11.74`.

```
We encountered an error trying to restore your previous session.

If you have previously used a more recent version of Element, your session may be incompatible with this version. Close this window and return to the more recent version.

Clearing your browser's storage may fix the problem, but will sign you out and cause any encrypted chat history to become unreadable.
```

#### What did you expect?

Normal startup

#### What happened instead?

Failed to start

### Operating system

Debian 12 amd64

### Application version

1.11.74

### How did you install the app?

Debian package  - https://packages.element.io/debian/

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2024-08-22 10:17
Logs contain:

```
2024-08-22T09:27:09.587Z E Expected a pickle key, but none provided.  Encryption may not work.
...
2024-08-22T09:27:13.006Z E Unable to load session invalid type: sequence, expected a string at line 1 column 0
Error: invalid type: sequence, expected a string at line 1 column 0
    at A.exports.__wbindgen_error_new (vector://vector/webapp/bundles/b3e2705564f4b981444b/7490.js:1:106731)
    at matrix_sdk_crypto_wasm.wasm.<wasm_bindgen::JsError as core::convert::From<E>>::from::h1ae9b13139e15527 (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[2354]:0x2ad509)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hd03fc43b14ec8138 (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[616]:0x135ed0)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::hee45b573e253a33d (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[7405]:0x39ad24)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen::convert::closures::invoke1_mut::hd6ac503cc1b2bedc (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[8645]:0x3ac97a)
    at L (vector://vector/webapp/bundles/b3e2705564f4b981444b/7490.js:1:3400)
    at E (vector://vector/webapp/bundles/b3e2705564f4b981444b/7490.js:1:2422)
```

Duplicate of https://github.com/element-hq/element-desktop/issues/1816

**Closed by richvdh** 2024-08-22 10:17 UTC
Labels: T-Defect, S-Critical, A-Storage, O-Uncommon, A-Element-R
