### ISSUE TITLE
"A web page is slowing down your browser" during normal actions.

### ISSUE THREAD

**Issue by michaelkaye** [element-hq/element-web#16425] opened 2021-02-10 09:58 UTC
### Description

Firefox shows the yellow "A web page is slowing down your browser" alert.

### Steps to reproduce

- Unsure
- Browser/element was working, i changed channels from one internal channel to another, and then the error showed up. The browser was a fresh start from about 20min ago; by this time in the morning I'd only launched element and a few GitHub windows, so it wasn't inherently overloaded.
-  I tried to let it wait for longer (clicking "Wait" twice, which gives about 60s extra) but no impact was seen.

CPU for firefox was spinning at 100%. 

Describe how what happens differs from what you expected.

It shouldn't wedge my browser :)

Logs being sent: yes

I had to restart element to get back control so couldn't `/rageshake`, however there was this stack trace after i told it to stop the script:

```
 Script terminated by timeout at:
_@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:155784
f/o<@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:155082
f@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:155204
getTextFor@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:5397641
generatePreview@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:5399859
onAction@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:5400513
onDispatch@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:405022
r</e.prototype._invokeCallback@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:1923685
r</e.prototype.dispatch@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:1923487
dispatch@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:164006
o@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:160247
s.prototype.emit@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:17504
_handleEvent@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:1046840
n@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:1046885
s.prototype.emit@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:17504
_handleEvent@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:1046840
n@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:1046885
s.prototype.emit@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:17447
h.prototype.addEventToTimeline@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:995377
h.prototype.addLiveEvent@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:995098
g.prototype._addLiveEvent@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:796185
g.prototype.addLiveEvents@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:801450
m.prototype._processRoomEvents@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:2142778
m.prototype._processSyncResponse/<@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:2138676
I@https://app.element.io/bundles/8bdd9bb39f69e827e0f8/vendors~init.js:2:4382
WidgetDriver.js:12:204
```

when i got control of my browser and opened the web console to investigate.

### Version information

- **Platform**: web
For the web app:

- **Browser**: Firefox 85.0
- **OS**:Ubuntu, 
- **URL**: app.element.io

**Comment by jryans** [comment] 2021-02-11 13:56
@michaelkaye How often does this happen for you?

**Comment by michaelkaye** [comment] 2021-02-15 15:26
I had it happen twice in a row, which is why i reported; haven't had it happen since friday.

**Comment by jryans** [comment] 2021-02-23 16:42
Okay, thanks for the detail. I am occasionally seeing this message when restarting the app (which is not great itself), but so far I haven't seen it during regular use.

Please keep us updated if the frequency or triggers change here.

**Comment by bparker06** [comment] 2021-05-20 14:43
I'm unable to use element under firefox at all anymore... the page just randomly freezes within a minute of loading and the "page is slowing down" message reappears every time I click "wait" and the page never unfreezes. Works fine under Chromium.

**Comment by jryans** [comment] 2021-05-28 14:56
Hmm, that's surprising to hear... Quite a few of us (including myself) use Element with Firefox every day, so there's something more specific happening.

**Comment by baumkuchen42** [comment] 2021-11-29 19:42
I have the same issue. For me it happens when a file like a picture or audio is sent in a chat.
I tried logging off and on again but now I cannot verify my browser session because loading the QR code makes Element freeze again.

Interestingly, the self-hosted element instance of my university works just fine. It's just app.element.io that's having these issues.

**Comment by novocaine** [comment] 2021-12-06 00:35
> I have the same issue. For me it happens when a file like a picture or audio is sent in a chat. I tried logging off and on again but now I cannot verify my browser session because loading the QR code makes Element freeze again.
> 
> Interestingly, the self-hosted element instance of my university works just fine. It's just app.element.io that's having these issues.

Thanks for reporting this. It would be greatly helpful if you could send us debug logs so we can work out what the issue is.

**Comment by baumkuchen42** [comment] 2021-12-06 09:43
> > I have the same issue. For me it happens when a file like a picture or audio is sent in a chat. I tried logging off and on again but now I cannot verify my browser session because loading the QR code makes Element freeze again.
> > Interestingly, the self-hosted element instance of my university works just fine. It's just app.element.io that's having these issues.
> 
> Thanks for reporting this. It would be greatly helpful if you could send us debug logs so we can work out what the issue is.

Hey,
unfortunately (or fortunately for me), the issue stopped appearing a couple days after I commented on this issue. Right now, everything is running smoothly. But I managed to trigger it again by scrolling up. I hope the debug log I attached is sufficiently helpful because I'm not able to visit the settings menu again due to the website freezing every time I try now.
[issue.txt](https://github.com/vector-im/element-web/files/7659693/issue.txt)
[log-0.log](https://github.com/vector-im/element-web/files/7659694/log-0.log)

**Comment by richvdh** [comment] 2024-05-08 09:02
If nobody has seen this for 3.5 years, we should probably close it. Even if it happens again, it'll likely be a different cause by now.

**Closed by richvdh** 2024-05-08 09:02 UTC
Labels: T-Defect, A-Performance, Z-Platform-Specific, S-Major, O-Uncommon
