### ISSUE TITLE
Instant search among menu items to help settings discovery

### ISSUE THREAD

**Issue by bkil** [element-hq/element-web#22804] opened 2022-07-11 13:10 UTC
#### What would you like to do?

Provide a search box with autocomplete or a window through which a user can discover all options, settings, menu items and dialogues by starting to type text that appears within them. Ideally, synonyms should also be supported, as terminology is not the same between messaging platforms.

#### Why would you like to do it?

Element has too many options (along with developer and labs options) for even an intermediate user to keep in mind and keep this knowledge up to date after every release.

#### How would you like to achieve it?

Chromium has a "Search settings..." bar on top of its settings window. Sorry I can't give a link to its code, SEO has it tuned to G. Search engine settings.

### Have you considered any alternatives?

* I have taken the time to read through all options and menu item on all windows before I started using it along with their help. This takes a lot of time and surely is not something that could be expected from a user. You would also need to repeat this review after every release.
* I usually search in the Git repositories to discover functions (all of the repos, including their dependencies, also taking quite some time).

**Comment by SimonBrandner** [comment] 2022-07-11 13:15
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/9592

**Closed as not planned by SimonBrandner** 2022-07-11 13:15 UTC
Labels: T-Enhancement
