### ISSUE TITLE
Request to `matrix.org/.well-known/matrix/client` when logged to local server

### ISSUE THREAD

**Issue by xmedeko** [element-hq/element-web#26996] opened 2024-02-12 08:31 UTC
### Steps to reproduce

1. I am logged in in Element Desktop app to a local (non-federated) Synapse server.
2. I start the app, open DevTools Ctrl+Shit+I, Network tab.

#### What did you expect?
I expect all request targets our server only. 

#### What happened instead?
I see request to:
```
GET https://matrix.org/.well-known/matrix/client
```
and 
```
POST https://posthog.element.io/decide...
```

Please, either fix (remove) or document such requests. We need to consider them in our security assessment process.

### Operating system

Windows 11

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### How did you install the app?

https://element.io/download

### Homeserver

Local server Synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-02-12 08:32
Duplicate of https://github.com/element-hq/element-web/issues/11655

**Closed by t3chguy** 2024-02-12 08:32 UTC
Labels: T-Defect

**Comment by xmedeko** [comment] 2024-02-12 08:54
Thanks for the quick response. I was searching issues but have not found this one.
