### ISSUE TITLE
Error opening Spaces

### ISSUE THREAD

**Issue by DAB-OS** [element-hq/element-web#27512] opened 2024-06-02 11:31 UTC
### Steps to reproduce

I tried to open a Space that had been created for me, and it provided me with an error screen. 
[rageshake.tar.zip](https://github.com/user-attachments/files/15525073/rageshake.tar.zip)

#### What did you expect?
I expected the Space to open
#### What happened instead?
It provided me with the error message. 

### Operating system

Windows 10

### Application version

Element ver. 1.11.67

### How did you install the app?

https://element.io/download

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-02 22:43
Duplicate of https://github.com/element-hq/element-web/issues/27503

**Closed by t3chguy** 2024-06-02 22:43 UTC
Labels: T-Defect, S-Major, A-Spaces
