### ISSUE TITLE
problem report (too little volume on the computer led to blockade of element)

### ISSUE THREAD

**Issue by freddy970** [element-hq/element-web#27578] opened 2024-06-14 15:03 UTC
### Steps to reproduce

I cannot open the element desktop app since my volume was full and now I have to send in the protocols to reopen the page. 

i want to submit the protocols so i can reenter my account.

### Operating system

macOS

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-14 15:37
> Will you send logs?
Yes

Not seeing any logs from you

**Comment by freddy970** [comment] 2024-06-15 13:29
Ah yes, sorry. 
[issue.txt](https://github.com/user-attachments/files/15847777/issue.txt)
[log-0.log](https://github.com/user-attachments/files/15847778/log-0.log)
[log-1.log](https://github.com/user-attachments/files/15847779/log-1.log)
[log-2.log](https://github.com/user-attachments/files/15847780/log-2.log)
[log-3.log](https://github.com/user-attachments/files/15847781/log-3.log)
[log-4.log](https://github.com/user-attachments/files/15847782/log-4.log)

**Comment by t3chguy** [comment] 2024-06-17 08:16
Thanks for the logs, there is nothing out of the ordinary in them. Your issue description is incredibly unclear.

> I cannot open the element desktop app since my volume was full and now I have to send in the protocols to reopen the page.

> i want to submit the protocols so i can reenter my account.

> What did you expect?
What happened instead?

Please also fill these fields

**Comment by kegsay** [comment] 2024-06-17 13:07
Based on `storageManager_usage` I think they probably ran out of disk space and then had to clear everything?

**Comment by t3chguy** [comment] 2024-06-17 13:16
Duplicate of https://github.com/element-hq/element-web/issues/10891

**Closed by t3chguy** 2024-06-17 13:16 UTC
Labels: T-Defect, X-Needs-Info, S-Critical
