### ISSUE TITLE
Element desktop nightly sometimes segfaults during startup

### ISSUE THREAD

**Issue by mvgorcum** [element-hq/element-web#27389] opened 2024-04-24 20:30 UTC
### Steps to reproduce

Starting through .desktop file sometimes starts and sometimes crashes.

Starting through terminal gives:

```
$ element-desktop-nightly 
/home/mathijs/.config/Element-Nightly exists: yes
/home/mathijs/.config/Riot-Nightly exists: no
Enabling Sentry with dsn=https://029a0eb289f942508ae0fb17935bd8c5@sentry.matrix.org/6 environment=nightly
Starting auto update with base URL: https://packages.element.io/nightly/update/
Auto update not supported on this platform
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
Segmentation fault (core dumped)
```

but also sometimes gives:

```
$ element-desktop-nightly 
/home/mathijs/.config/Element-Nightly exists: yes
/home/mathijs/.config/Riot-Nightly exists: no
Enabling Sentry with dsn=https://029a0eb289f942508ae0fb17935bd8c5@sentry.matrix.org/6 environment=nightly
Starting auto update with base URL: https://packages.element.io/nightly/update/
Auto update not supported on this platform
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
```
After the latter element starts as normal.

### Outcome

Sometimes element-desktop-nightly starts, sometimes it doesn't.

### Operating system

Kubuntu 22.04

### Application version

element-desktop-nightly latest (from https://packages.element.io/nightly/update/ repo)

### How did you install the app?

apt repo

### Homeserver

synapse 1.105.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-04-25 00:32
Duplicate of https://github.com/element-hq/element-desktop/issues/1630

**Closed by t3chguy** 2024-04-25 00:32 UTC
Labels: T-Defect, S-Critical, A-Electron
