### ISSUE TITLE
Inter Ligatures no longer show up in the composer.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#26875] opened 2024-01-15 21:09 UTC
### Steps to reproduce

1. Type -> in the composer
2. Hit send
3. See a nice → in the timeline, and feel confused and frustrated that it didn't preview in the composer correctly.

#### What did you expect?

ligatures

#### What happened instead?

no ligatures :(

### Operating system

macOS 13.6.3

### Application version

Desktop nightly

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-01-15 23:41
Duplicate of https://github.com/element-hq/element-web/issues/17403

**Closed by t3chguy** 2024-01-15 23:41 UTC
Labels: T-Defect
