### ISSUE TITLE
Feature request : Make it possible to configure keyboard shortcuts

### ISSUE THREAD

**Issue by LutzLange** [element-hq/element-web#26881] opened 2024-01-17 08:18 UTC
#### What would you like to do?

I would like to be able to reconfigure keyboard shortcuts in ElementWeb/Desktop

#### Why would you like to do it?

I'm using a different keyboard layout and the standard shortcuts don't work well for me.

#### How would you like to achieve it?

It should be possible in the Settings menu to change the keyboard shortcuts.

**Comment by t3chguy** [comment] 2024-01-17 08:19
Duplicate of https://github.com/element-hq/element-web/issues/15076

**Closed by t3chguy** 2024-01-17 08:19 UTC
Labels: T-Enhancement
