### ISSUE TITLE
single room messages can not be loaded

### ISSUE THREAD

**Issue by wvhn** [element-hq/element-web#26978] opened 2024-02-06 20:59 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
overview of all subscribed rooms and persons on Safari under OSX Catalina

2. What do you click?
room from gitter.im with multiple members 

#### What did you expect?
all messages in a room should get displayed

#### What happened instead?
room is displayed. Some messages are displayed normally but some are not.
Error Message: Diese Nachricht kann nicht geladen werden (m.room.message) 

Error does not occur in rooms with only two members.

### Operating system

macOS Catalina

### Browser information

Safari

### URL for webapp

https://app.gitter.im/#/room/#smarthomeNG_smarthome:gitter.im

### Application version

Version von Gitter: 1.11.57 Krypto-Version: Olm 3.2.15

### Will you send logs?

Yes

**Comment by dbkr** [comment] 2024-02-08 12:56
There are some strange exceptions in the logs which may be the cause:

```
2024-02-06T20:50:53.756Z E undefined is not a constructor (evaluating 'new Intl.ListFormat((0,i.of)(),{style:"long",type:"conjunction"})')
m@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:2593472
render@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/element-web-app.js:1:95029
qs@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3070663
Dl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3097511
Fl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3097439
Tl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3097302
yl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3094289
yl@[native code]
@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3044026
@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3128481
$i@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3043972
Hi@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3043907
ml@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3091674
enqueueSetState@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3047881
@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3119772
r@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/element-web-app.js:1:505725
promiseReactionJob@[native code]
2024-02-06T20:50:53.768Z E undefined is not a constructor (evaluating 'new Intl.ListFormat((0,i.of)(),{style:"long",type:"conjunction"})')
m@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:2593472
Vn@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/element-web-app.js:1:109116
ss@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3058107
$a@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3110233
Dl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3097511
Fl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3097439
Tl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3097302
yl@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3094289
yl@[native code]
@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3044026
@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3128481
$i@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3043972
Hi@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3043907
ml@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3091674
enqueueSetState@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3047881
@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/bundle.js:2:3119772
r@https://app.gitter.im/bundles/9dccb1bc66b3f9d713f0/element-web-app.js:1:505725
promiseReactionJob@[native code]
```

This would suggest Intl.ListFormat doesn't exist in the browser, but this has been in Safari since 14.1, which is available for Catalina. What version of Safari is this?

**Comment by wvhn** [comment] 2024-02-08 13:38
Thanks for looking into it. 

My Safari version is v.15.6.1 but the Mozilla implementation notes state that Intl.ListFormat is only available for Big Sur (macOS v11) and above. Catalina is  v10.15.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat
![image](https://github.com/element-hq/element-web/assets/17801971/22fa83e7-cb72-4e50-ac85-df998cde8e23)

Intl.ListFormat is undefined if I call it on the developer console. 

BR
Wolfram

**Comment by t3chguy** [comment] 2024-02-12 08:12
Our support policy https://github.com/element-hq/element-web#supported-environments says we only support 2 versions of Safari (17.3, 17.2), so unfortunately your environment is unsupported and must be closed as per that policy.

**Closed by t3chguy** 2024-02-12 08:12 UTC
Labels: T-Defect, X-Needs-Info

**Comment by richvdh** [comment] 2024-05-07 15:51
related: https://github.com/element-hq/element-web/issues/27444

**Comment by richvdh** [comment] 2024-05-07 15:55
I discovered this issue after opening #27444, because we're still getting reports of it happening.

> Our support policy https://github.com/element-hq/element-web#supported-environments says we only support 2 versions of Safari (17.3, 17.2), so unfortunately your environment is unsupported and must be closed as per that policy.

FTR, "your environment is unsupported" is correct, but not for this reason. Safari 17 has the same problem. The problem is the use of Catalina.

Although it's true that we are under no obligation to support such environments, it feels like we could, in theory at least, do a better job of telling people that their environment is unsupported, rather than leaving them with a partially-functional application.
