### ISSUE TITLE
When receiving an invitation from someone, seek and show places common with that person

### ISSUE THREAD

**Issue by Porkepix** [element-hq/element-web#28362] opened 2024-11-01 14:00 UTC
#### What would you like to do?
When receiving a request to talk with someone, seek in every chan we're in if that person is there, and list them if there are

#### Why would you like to do it?
Matrix seems to now becomes target of spam and other problematic behaviors, that would allows us to be aware if we might know that person from some place or not

#### How would you like to achieve it?
Search in the list of members of every chan that account is part of.

### Have you considered any alternatives?

Looking manually, or blindly accepting the request, with the risk it involves.

**Comment by t3chguy** [comment] 2024-11-01 14:02
Duplicate of https://github.com/element-hq/element-meta/issues/371

**Closed by t3chguy** 2024-11-01 14:02 UTC
Labels: T-Enhancement
