### ISSUE TITLE
Search doesn't seem to index encrypted rooms

### ISSUE THREAD

**Issue by krokodilerian** [element-hq/element-web#28683] opened 2024-12-08 10:07 UTC
### Steps to reproduce

This is a new, fresh installation of element-desktop, I've been using the web version until now (but needed search).

I start element-desktop in a terminal, and I see

```
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store TypeError: keytar.setPassword is not a function
    at getOrCreatePassphrase (file:///opt/Element/resources/app.asar/lib/seshat.js:42:30)
    at async IpcMainImpl.<anonymous> (file:///opt/Element/resources/app.asar/lib/seshat.js:90:36)
(node:3543159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 serverSupportedVersions listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `element-desktop --trace-warnings ...` to show where the warning was created)
(node:3543159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 userAccessToken listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:3543159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 homeserverUrl listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:3543159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 userAccessToken listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
```

I then go to Setting->Security and privacy->Search, and check the state of the message sync. It's done after a while, but with less messages than I expect.

Then, I try a search in a private chat, for words I know exist there, and nothing is found. I can see messages being found only in one of the non-encrypted channels I'm in, if I ask for Element to search in all channels.

#### What did you expect?

To see messages from private channels being found with search

#### What happened instead?

No such messages were found

### Operating system

Debian stable

### Application version

Element version: 1.11.87 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

https://element.io/download

### Homeserver

fosdem.ems.host

### Will you send logs?

Yes

**Comment by Sazu-bit** [comment] 2024-12-08 20:27
I get this with opening an attachment. 

```
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store TypeError: keytar.setPassword is not a function
    at getOrCreatePassphrase (file:///usr/lib/schildichat-desktop/resources/app/lib/seshat.js:42:30)
    at async IpcMainImpl.<anonymous> (file:///usr/lib/schildichat-desktop/resources/app/lib/seshat.js:90:36)
(node:25831) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 serverSupportedVersions listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:25831) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 userAccessToken listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:25831) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 serverSupportedVersions listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:25831) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 userAccessToken listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:25831) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 serverSupportedVersions listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:25831) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 userAccessToken listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
Crashing due to FD ownership violation:
#0 0x60d634a595d4 <unknown>
#1 0x60d634a5084e <unknown>
#2 0x60d634a50802 close
#3 0x7a64b6af2584 pa_close
#4 0x60d634a7f7cc <unknown>
#5 0x60d634a1909a <unknown>
#6 0x60d6349e5e9a <unknown>
#7 0x60d63383cb9d <unknown>
#8 0x60d63383e9f3 <unknown>
#9 0x60d63383a04c <unknown>
#10 0x60d6312401a7 <unknown>
#11 0x60d631241b29 <unknown>
#12 0x60d631241918 <unknown>
#13 0x60d63123ecb1 <unknown>
#14 0x60d63123f1aa <unknown>
#15 0x60d630ee323e <unknown>
#16 0x7a64b9335d6e <unknown>
```

Looks like someone coded the keytar.setPassword call incorrectly.

**Comment by t3chguy** [comment] 2024-12-09 09:47
> Looks like someone coded the keytar.setPassword call incorrectly.

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/983b24ce-84e9-44b0-9645-351312476354">

It hasn't changed in over 2 years

Duplicate of https://github.com/element-hq/element-web/issues/28684

**Closed by t3chguy** 2024-12-09 09:47 UTC
Labels: T-Defect, S-Major, A-Indexing, O-Occasional
