### ISSUE TITLE
Keys not set at first login, have to reset-all to work

### ISSUE THREAD

**Issue by crjo** [element-hq/element-web#27536] opened 2024-06-07 14:03 UTC
### Steps to reproduce

1 - Open Edge private window
2 - Login (oidc)
3 - Set Up secure Backup
![image](https://github.com/element-hq/element-web/assets/5144838/f9338d40-2749-4412-a3ea-5e85d867435c)
When click on setup get a 401 but only on console, no other error
![image](https://github.com/element-hq/element-web/assets/5144838/48e4b4aa-2aa4-4868-bf17-b6f307f56bcf)
Going ahead, creating keys and downloading file
![image](https://github.com/element-hq/element-web/assets/5144838/a856bf2e-e5f4-4fd3-9028-194e24689a01)
4 - Log out
5 - Close Edge private window

6 - Open Edge private window
7- Login (oidc)
![image](https://github.com/element-hq/element-web/assets/5144838/db9fe094-587f-45df-b6bc-3b4e17f89290)
8 - Upload file saved at step 3
![image](https://github.com/element-hq/element-web/assets/5144838/70a04ec0-9975-4d28-8871-fc1262fb4bcb)
9 - Click on continue does nothing, only erases security key
10 - Reset-all
11 - Get a Single Sign On verification (didn't get that on step 3)
![image](https://github.com/element-hq/element-web/assets/5144838/3368df3e-7087-42d6-a66c-3513f2b51867)
12 - Confirm
![image](https://github.com/element-hq/element-web/assets/5144838/35c8aebf-7fac-40e7-ade0-c77aed8bf212)
13 - Log out
14 - Close Edge private window

15 - Open Edge private window
16 - Login (oidc)
17 - No problem now

### Outcome

Expected : Keys set at first login

Experience : Keys set after reset-all

### Operating system

Windows

### Application version

Element Web 1.11.62

### Homeserver

Synapse 1.108.0

### Will you send logs?

No

**Comment by crjo** [comment] 2024-06-10 06:45
Element Web upgraded to 1.11.68 : still the issue
We are using Keycloak as OIDC

**Comment by t3chguy** [comment] 2024-06-10 08:20
Duplicate of https://github.com/element-hq/element-web/issues/27524

**Closed by t3chguy** 2024-06-10 08:20 UTC
Labels: T-Defect, S-Major, A-E2EE-Key-Backup, A-SSO
