### ISSUE TITLE
Visual appearance of check boxes unclear and inconsistent

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27181] opened 2024-03-13 22:16 UTC
### Steps to reproduce

1. Go to settings
2. Observe check boxes

#### What did you expect?
Clear marked and unmarked state

#### What happened instead?
Various states of grey and bright or dark borders

![image](https://github.com/element-hq/element-web/assets/640121/5e8deea9-ac3b-4610-a97c-37884aece9d5)
![image](https://github.com/element-hq/element-web/assets/640121/5806a1f6-fb90-402f-a749-e96a0d247dee)

### Operating system

Windows 11

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

No

**Comment by bblacher** [comment] 2024-03-14 06:58
Duplicate of https://github.com/element-hq/element-web/issues/27166

**Closed** 2024-03-14 08:55 UTC
Labels: T-Defect
