### ISSUE TITLE
@mentions popup doesn't scale very well on narrow windows

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#27976] opened 2024-08-29 10:50 UTC
### Steps to reproduce

`@mention` someone in a narrow window

#### What did you expect?

Better scaling of the mentions popup

#### What happened instead?

Overlapping text and other unwanted rendering. I have a customer provided screenshot that looks even more messy than I was able to reproduce. Attached on the rageshake

[Screencast_20240829_114045.webm](https://github.com/user-attachments/assets/c002910c-c190-4c18-ae02-8a5cb23fd601)

### Operating system

Fedora 40

### Browser information

Firefox 129.0.2 (64-bit)

### URL for webapp

https://riots.im/1.11.76/

### Application version

Element version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

Synapse 1.113.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-08-29 11:09
Duplicate of https://github.com/element-hq/element-web/issues/21393

**Closed by t3chguy** 2024-08-29 11:09 UTC
Labels: T-Defect, S-Minor, O-Occasional
