### ISSUE TITLE
"Show unread threads" should be an option in the thread pane

### ISSUE THREAD

**Issue by ajkessel** [element-hq/element-web#26863] opened 2024-01-11 16:06 UTC
### Your use case

Thread pane currently allows "All threads" and "My threads" but not "unread threads". The latter is an extremely common use case. Particularly when there are older unread threads, it is quite cumbersome to find them. I suggest "unread threads" be added as a third option in the thread pane.

**Comment by t3chguy** [comment] 2024-01-11 16:40
Duplicate of https://github.com/element-hq/element-meta/discussions/1825

**Closed by t3chguy** 2024-01-11 16:40 UTC
Labels: T-Enhancement
