### ISSUE TITLE
Replies to messages sent before you joined an encrypted room are incorrectly shown as UTD

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27356] opened 2024-04-16 15:24 UTC
### Steps to reproduce

1. Join an encrypted room
2. See someone reply to a message that predates your join
3. Observe that it's UTD.
4. This is an expected UTD: it should instead show "You do not have permission to view this message" or something instead.
![Screenshot 2024-04-16 at 16 21 46](https://github.com/element-hq/element-web/assets/1294269/c2772e4f-a8ec-4062-b53c-8525042330d3)

#### What did you expect?

Expected UTDs should have nice UX rather than show up as UTDs.

### Application version

nightly

### Will you send logs?

No

**Comment by richvdh** [comment] 2024-06-14 09:26
I think this might just be a duplicate of https://github.com/element-hq/element-meta/issues/2317, whose fix is waiting for rollout of MSC4115 support

**Comment by richvdh** [comment] 2024-06-14 10:59
Yes, this is now fixed:

![image](https://github.com/element-hq/element-web/assets/1389908/577dd147-6b0a-46cf-89f2-bf96c9be432a)

However, threads do have a similar problem. Filed as https://github.com/element-hq/element-web/issues/27577

**Closed by richvdh** 2024-06-14 10:59 UTC
Labels: T-Defect, S-Minor, A-E2EE, Z-UISI, O-Frequent
