### ISSUE TITLE
Gifs are not animated if sent by windows keyboard

### ISSUE THREAD

**Issue by thanasistrisp** [element-hq/element-web#22513] opened 2022-06-10 09:48 UTC
### Steps to reproduce

In windows 10 keyboard gifs are sent as *.png instead of *.gif. 
In android for example they are sent correctly

Possible ways to fix it:
- Gifs through keyboard should be sent as animated
- Add gif picker not the giphy bot so that I am able to choose gifs from a category and be able to send gifs to encrypted rooms

#### What did you expect?
To be animated
#### What happened instead?
They are static

### Operating system

Windows 11

### Application version

**Desktop app**, Element Nightly: 0.0.1-nightly.2022061001

### How did you install the app?

From element website

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment] 2022-06-10 14:00
Duplicate of https://github.com/vector-im/element-web/issues/15983

**Closed as not planned by robintown** 2022-06-10 14:00 UTC
Labels: T-Defect

**Comment by t3chguy** [comment] 2022-06-10 22:31
Also cannot reproduce, works fine on my Win 11 laptop.

**Comment by t3chguy** [comment] 2022-06-10 23:03
https://user-images.githubusercontent.com/2403652/173160807-2935ad5a-36ee-45cf-878b-69fb281b022c.mp4

Works fine here, not sure what to suggest.

**Comment by t3chguy** [comment] 2022-06-10 23:33
Indeed, can reproduce, but it is definitely upstream of Element, as the browser is handing us the PNG.

![image](https://user-images.githubusercontent.com/2403652/173162561-3a57c1b3-59ae-4ea8-91dd-cb0f2947d1d4.png)

Might be related to https://github.com/electron/electron/issues/5078
