### ISSUE TITLE
ElementR: malformed megolm key in backup will make the whole backup import fails

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26775] opened 2023-12-15 18:47 UTC
```
rageshake.ts:77 Error restoring backup Error: missing field `sender_claimed_keys`
    at module.exports.__wbindgen_error_new (matrix_sdk_crypto_wasm.js:7273:1)
    at serde_wasm_bindgen::error::Error::new::haa52582176c8e8a7 (0156008e:0x346ed8)
    at byn$mgfn-shared$serde::de::Error::missing_field::hcb818cd6c817fdc6 (0156008e:0x3d85d6)
    at serde::de::Error::missing_field::hcb818cd6c817fdc6 (0156008e:0x3013a0)
    at olmmachine_importBackedUpRoomKeys (0156008e:0xc3cd7)
    at OlmMachine.importBackedUpRoomKeys (matrix_sdk_crypto_wasm.js:4115:1)
    at RustBackupManager.importBackedUpRoomKeys (backup.ts:209:31)
    at RustCrypto.importBackedUpRoomKeys (rust-crypto.ts:1200:41)
    at MatrixClient.restoreKeyBackup (client.ts:3971:34)
    at async RestoreKeyBackupDialog.tsx:231:17
```

https://github.com/element-hq/element-web/issues/26774

**Comment by BillCarsonFr** [comment] 2023-12-15 18:53
should check the validity here probably https://github.com/matrix-org/matrix-js-sdk/blob/68898aeff2c5cb080f0df293a452d0cad9fe5447/src/rust-crypto/backup.ts#L545

**Comment by t3chguy** [comment] 2023-12-15 18:56
Duplicate of https://github.com/element-hq/element-web/issues/26774

**Closed by t3chguy** 2023-12-15 18:56 UTC
Labels: Z-Labs, A-Element-R
