### ISSUE TITLE
Crash on startup following verification

### ISSUE THREAD

**Issue by linuxtim** [element-hq/element-web#27463] opened 2024-05-11 10:12 UTC
### Steps to reproduce

Login to new session.  Crashed immediately after verification.  Enabled core dumps, and restarted.  Crashed on startup.

### Outcome

Crash on startup following verification

### Operating system

Debian 12 x86-64

### Application version

1.11.66

### How did you install the app?

With apt from https://packages.element.io/debian/ 

### Homeserver

matrix.org

### Will you send logs?

Backtrace provided

**Comment by linuxtim** [comment] 2024-05-11 10:16
gdb says: "Program terminated with signal SIGTRAP, Trace/breakpoint trap."

Backtrace:

#0  0x000055c44528a4f4 in partition_alloc::internal::DiscardSystemPagesInternal(unsigned long, unsigned long)::$_0::operator()() const (this=<optimized out>) at ../../base/allocator/partition_allocator/src/partition_alloc/page_allocator_internals_posix.h:428
#1  partition_alloc::internal::DiscardSystemPagesInternal(unsigned long, unsigned long) (address=25271605198848, length=45056) at ../../base/allocator/partition_allocator/src/partition_alloc/page_allocator_internals_posix.h:428
#2  partition_alloc::DiscardSystemPages(unsigned long, unsigned long) (address=25271605198848, length=45056) at ../../base/allocator/partition_allocator/src/partition_alloc/page_allocator.cc:360
#3  partition_alloc::internal::DecommitSystemPagesInternal(unsigned long, unsigned long, partition_alloc::PageAccessibilityDisposition) (address=25271605198848, length=45056, accessibility_disposition=<optimized out>) at ../../base/allocator/partition_allocator/src/partition_alloc/page_allocator_internals_posix.h:298
#4  partition_alloc::DecommitSystemPages(unsigned long, unsigned long, partition_alloc::PageAccessibilityDisposition) (address=25271605198848, length=45056, accessibility_disposition=partition_alloc::PageAccessibilityDisposition::kAllowKeepForPerf) at ../../base/allocator/partition_allocator/src/partition_alloc/page_allocator.cc:303
#5  0x000055c44528d0b3 in partition_alloc::PartitionRoot::DecommitSystemPagesForData(unsigned long, unsigned long, partition_alloc::PageAccessibilityDisposition) (this=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>, address=140584612235876, length=45056, accessibility_disposition=partition_alloc::PageAccessibilityDisposition::kAllowKeepForPerf) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1860
#6  partition_alloc::internal::SlotSpanMetadata::Decommit(partition_alloc::PartitionRoot*) (this=0x16fc01001680, root=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_page.cc:222
#7  partition_alloc::internal::SlotSpanMetadata::DecommitIfPossible(partition_alloc::PartitionRoot*) (this=0x16fc01001680, root=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_page.cc:249
#8  partition_alloc::internal::SlotSpanMetadata::RegisterEmpty() (this=0x16fc020010e0) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_page.cc:105
#9  partition_alloc::internal::SlotSpanMetadata::FreeSlowPath(unsigned long) (this=0x16fc020010e0, number_of_freed=<optimized out>) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_page.cc:202
#10 0x000055c4452a2a6b in partition_alloc::internal::SlotSpanMetadata::Free(unsigned long, partition_alloc::PartitionRoot*) (this=0x16fc020010e0, slot_start=25271621238784, root=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_page.h:657
#11 partition_alloc::PartitionRoot::FreeInSlotSpan(unsigned long, partition_alloc::internal::SlotSpanMetadata*) (this=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>, slot_start=25271621238784, slot_span=0x16fc020010e0) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1661
#12 partition_alloc::PartitionRoot::RawFree(unsigned long, partition_alloc::internal::SlotSpanMetadata*) (this=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>, slot_start=25271621238784, slot_span=0x16fc020010e0) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1716
#13 partition_alloc::PartitionRoot::RawFreeWithThreadCache(unsigned long, partition_alloc::internal::SlotSpanMetadata*) (this=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>, slot_start=25271621238784, slot_span=0x16fc020010e0) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1776
#14 partition_alloc::PartitionRoot::FreeNoHooksImmediate(void*, partition_alloc::internal::SlotSpanMetadata*, unsigned long) (this=<optimized out>, object=<optimized out>, slot_span=<optimized out>, slot_start=<optimized out>) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1647
#15 partition_alloc::PartitionRoot::FreeInline<(partition_alloc::internal::FreeFlags)2>(void*) (this=0x55c449d3bd80 <allocator_shim::ConfigurePartitions(partition_alloc::internal::base::StrongAlias<allocator_shim::EnableBrpTag, bool>, partition_alloc::internal::base::StrongAlias<allocator_shim::EnableMemoryTaggingTag, bool>, partition_alloc::TagViolationReportingMode, allocator_shim::BucketDistribution, partition_alloc::internal::base::StrongAlias<allocator_shim::SchedulerLoopQuarantineTag, bool>, unsigned long, unsigned long, partition_alloc::internal::base::StrongAlias<allocator_shim::ZappingByFreeFlagsTag, bool>)::new_main_allocator>, object=0x16fc0201c000) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1541
#16 partition_alloc::PartitionRoot::FreeInlineInUnknownRoot<(partition_alloc::internal::FreeFlags)2>(void*) (object=0x16fc0201c000) at ../../base/allocator/partition_allocator/src/partition_alloc/partition_root.h:1437
#17 allocator_shim::internal::PartitionFree(allocator_shim::AllocatorDispatch const*, void*, void*) (object=0x16fc0201c000, context=<optimized out>) at ../../base/allocator/partition_allocator/src/partition_alloc/shim/allocator_shim_default_dispatch_to_partition_alloc.cc:340
#18 0x000055c446437943 in leveldb::DeleteBlock(void*, void*) (arg=0x7fdc67df8a64, ignored=<optimized out>) at ../../third_party/leveldatabase/src/table/table.cc:137
#19 0x000055c446436547 in leveldb::Iterator::CleanupNode::Run() (this=<optimized out>) at ../../third_party/leveldatabase/src/include/leveldb/iterator.h:92
#20 leveldb::Iterator::~Iterator() (this=0x16fc01429000) at ../../third_party/leveldatabase/src/table/iterator.cc:16
#21 0x000055c446438508 in leveldb::Block::Iter::~Iter() (this=0x16fc01429000) at ../../third_party/leveldatabase/src/table/block.cc:77
#22 leveldb::Block::Iter::~Iter() (this=0x16fc01429000) at ../../third_party/leveldatabase/src/table/block.cc:77
#23 0x000055c44643a96d in leveldb::IteratorWrapper::Set(leveldb::Iterator*) (this=0x16fc00eb6640, iter=0x16fc01655e80) at ../../third_party/leveldatabase/src/table/iterator_wrapper.h:27
#24 leveldb::(anonymous namespace)::TwoLevelIterator::SetDataIterator(leveldb::Iterator*) (this=0x16fc00eb65d0, data_iter=0x16fc01655e80) at ../../third_party/leveldatabase/src/table/two_level_iterator.cc:143
#25 leveldb::(anonymous namespace)::TwoLevelIterator::InitDataBlock() (this=0x16fc00eb65d0) at ../../third_party/leveldatabase/src/table/two_level_iterator.cc:158
#26 0x000055c44643aa6f in leveldb::(anonymous namespace)::TwoLevelIterator::SkipEmptyDataBlocksForward() (this=0x16fc00eb65d0) at ../../third_party/leveldatabase/src/table/two_level_iterator.cc:123
#27 0x000055c446436d6b in leveldb::IteratorWrapper::Next() (this=0x16fc03a0d078) at ../../third_party/leveldatabase/src/table/iterator_wrapper.h:53
#28 leveldb::(anonymous namespace)::MergingIterator::Next() (this=0x16fc02819fe0) at ../../third_party/leveldatabase/src/table/merger.cc:77
#29 0x000055c446427230 in leveldb::(anonymous namespace)::DBIter::FindNextUserEntry(bool, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >*) (this=0x16fc00c21fe0, skipping=true, skip=0x16fc00c22030) at ../../third_party/leveldatabase/src/db/db_iter.cc:203
#30 0x000055c4449d2709 in content::CleanupScopeTask::DeletePrefixedRange(leveldb::Slice, leveldb::ReadOptions const&, leveldb::WriteOptions const&) (this=0x16fc0197d6e0, prefix=..., read_options=<optimized out>, write_options=...) at ../../components/services/storage/indexed_db/scopes/leveldb_scopes_tasks.cc:224
#31 0x000055c4449d25c8 in content::CleanupScopeTask::Run() (this=0x16fc0197d6e0) at ../../components/services/storage/indexed_db/scopes/leveldb_scopes_tasks.cc:145
#32 0x000055c4449d0d32 in base::internal::FunctorTraits<leveldb::Status (content::CleanupScopeTask::*)()>::Invoke<leveldb::Status (content::CleanupScopeTask::*)(), std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> >>(leveldb::Status (content::CleanupScopeTask::*)(), std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> >&&) (method=<optimized out>, receiver_ptr=<optimized out>) at ../../base/functional/bind_internal.h:710
#33 base::internal::InvokeHelper<false, leveldb::Status, 0ul>::MakeItSo<leveldb::Status (content::CleanupScopeTask::*)(), std::__Cr::tuple<std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> > >>(leveldb::Status (content::CleanupScopeTask::*&&)(), std::__Cr::tuple<std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> > >&&) (functor=<optimized out>, bound=<optimized out>) at ../../base/functional/bind_internal.h:860
#34 base::internal::Invoker<base::internal::BindState<leveldb::Status (content::CleanupScopeTask::*)(), std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> > >, leveldb::Status ()>::RunImpl<leveldb::Status (content::CleanupScopeTask::*)(), std::__Cr::tuple<std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> > >, 0ul>(leveldb::Status (content::CleanupScopeTask::*&&)(), std::__Cr::tuple<std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> > >&&, std::__Cr::integer_sequence<unsigned long, 0ul>) (functor=<optimized out>, bound=<optimized out>) at ../../base/functional/bind_internal.h:991
#35 base::internal::Invoker<base::internal::BindState<leveldb::Status (content::CleanupScopeTask::*)(), std::__Cr::unique_ptr<content::CleanupScopeTask, std::__Cr::default_delete<content::CleanupScopeTask> > >, leveldb::Status ()>::RunOnce(base::internal::BindStateBase*) (base=<optimized out>) at ../../base/functional/bind_internal.h:904
#36 0x000055c4449d1a31 in base::OnceCallback<leveldb::Status ()>::Run() && (this=0x7fdc67df8db8) at ../../base/functional/callback.h:156
#37 base::internal::ReturnAsParamAdapter<leveldb::Status>(base::OnceCallback<leveldb::Status ()>, std::__Cr::unique_ptr<leveldb::Status, std::__Cr::default_delete<leveldb::Status> >*) (func=..., result=0x16fc0158eb80) at ../../base/task/post_task_and_reply_with_result_internal.h:23
#38 0x000055c44520f0e1 in base::OnceCallback<void ()>::Run() && (this=<optimized out>) at ../../base/functional/callback.h:156
#39 base::internal::PostTaskAndReplyRelay::RunTaskAndPostReply(base::internal::PostTaskAndReplyRelay) (relay=...) at ../../base/threading/post_task_and_reply_impl.h:45
#40 base::internal::FunctorTraits<void (*)(base::internal::PostTaskAndReplyRelay)>::Invoke<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>(void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&) (args=<optimized out>, function=<optimized out>) at ../../base/functional/bind_internal.h:641
#41 base::internal::InvokeHelper<false, void, 0ul>::MakeItSo<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&) (bound=<optimized out>, functor=<optimized out>) at ../../base/functional/bind_internal.h:860
#42 base::internal::Invoker<base::internal::BindState<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunImpl<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>, 0ul>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&, std::__Cr::integer_sequence<unsigned long, 0ul>) (bound=<optimized out>, functor=<optimized out>) at ../../base/functional/bind_internal.h:991
#43 base::internal::Invoker<base::internal::BindState<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunOnce(base::internal::BindStateBase*) (base=<optimized out>) at ../../base/functional/bind_internal.h:904
#44 0x000055c4451ebedf in base::OnceCallback<void ()>::Run() && (this=0x7fdc67df9258) at ../../base/functional/callback.h:156
#45 base::TaskAnnotator::RunTaskImpl(base::PendingTask&) (this=<optimized out>, pending_task=...) at ../../base/task/common/task_annotator.cc:201
#46 0x000055c4452133fb in base::TaskAnnotator::RunTask<base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::internal::SequenceToken const&)::$_0>(perfetto::StaticString, base::PendingTask&, base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::internal::SequenceToken const&)::$_0&&) (this=0x232c00210408, event_name=..., pending_task=<optimized out>, args=<optimized out>) at ../../base/task/common/task_annotator.h:89
#47 base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::internal::SequenceToken const&) (this=<optimized out>, task=..., traits=<optimized out>, task_source=<optimized out>, token=<optimized out>) at ../../base/task/thread_pool/task_tracker.cc:679
#48 0x000055c445213dc0 in base::internal::TaskTracker::RunBlockShutdown(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::internal::SequenceToken const&) (this=0x232c00210400, task=..., traits=..., task_source=0x16fc019d9fe0, token=...) at ../../base/task/thread_pool/task_tracker.cc:672
#49 0x000055c445212f0b in base::internal::TaskTracker::RunTaskWithShutdownBehavior(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::internal::SequenceToken const&) (this=0x232c00210400, task=..., traits=..., task_source=0x16fc019d9fe0, token=...) at ../../base/task/thread_pool/task_tracker.cc:697
#50 base::internal::TaskTracker::RunTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&) (this=0x232c00210400, task=..., task_source=0x16fc019d9fe0, traits=...) at ../../base/task/thread_pool/task_tracker.cc:521
#51 0x000055c44521294d in base::internal::TaskTracker::RunAndPopNextTask(base::internal::RegisteredTaskSource) (this=0x232c00210400, task_source=...) at ../../base/task/thread_pool/task_tracker.cc:416
#52 0x000055c4452258d3 in base::internal::WorkerThread::RunWorker() (this=0x232c002e8640) at ../../base/task/thread_pool/worker_thread.cc:430
#53 0x000055c44522565d in base::internal::WorkerThread::RunPooledWorker() (this=0x7fdc67df8a64) at ../../base/task/thread_pool/worker_thread.cc:315
#54 0x000055c44522557b in base::internal::WorkerThread::ThreadMain() (this=0x232c002e8640) at ../../base/task/thread_pool/worker_thread.cc:295
#55 0x000055c44523fd95 in base::(anonymous namespace)::ThreadFunc(void*) (params=<optimized out>) at ../../base/threading/platform_thread_posix.cc:103
#56 0x00007fdc6ccc8134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#57 0x00007fdc6cd487dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by t3chguy** [comment] 2024-05-13 05:54
Duplicate of https://github.com/element-hq/element-desktop/issues/691

**Closed by t3chguy** 2024-05-13 05:54 UTC
Labels: T-Defect, S-Critical
