### ISSUE TITLE
Variable playback speed for voice msgs

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27077] opened 2024-02-26 22:07 UTC
#### What would you like to do?

Speed up playback for VMs

#### Why would you like to do it?

Accessibility, and to deal with people who speak slowly.

#### How would you like to achieve it?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

### Additional context

Surprisingly useful feature in youtube.

**Comment by t3chguy** [comment] 2024-02-26 22:24
Duplicate of https://github.com/element-hq/element-meta/issues/2148

**Closed by t3chguy** 2024-02-26 22:24 UTC
Labels: T-Enhancement
