### ISSUE TITLE
Search dialog closes after a few character, unless I type _very_ slow

### ISSUE THREAD

**Issue by grinapo** [element-hq/element-web#28519] opened 2024-11-22 09:00 UTC
### Steps to reproduce

1. click on search or ctrl-K
2. start typing normal speed
3. 2-3 characters get into the search, then dialog closes, and the rest goes into the message input field

#### What did you expect?
dialog not closing, search searching

#### What happened instead?
dialog close, no search, letters in message box

### Operating system

Debian/Linux

### Browser information

134.0a1 (2024-11-16) (64-bit)

### URL for webapp

https://riot.grin.hu/

### Application version

griot version: 1.11.86 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

grin.hu

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-11-22 09:50
Duplicate of https://github.com/element-hq/element-web/issues/28493

**Closed by t3chguy** 2024-11-22 09:50 UTC
Labels: T-Defect, S-Major, O-Frequent, A-Spotlight-Search
