### ISSUE TITLE
secure_backup_required not enforced (SSO)

### ISSUE THREAD

**Issue by jonathanmmm** [element-hq/element-web#22302] opened 2022-05-20 21:14 UTC
### Steps to reproduce

Hi,

I am using oidc_providers to login users.
I set the following under `.well-known/matrix/client`:
```
"io.element.e2ee": { 
            "default": true, 
            "secure_backup_required": true
    },
```

User logs in (for the first time)

#### What did you expect?

User is forced to backup encryption

#### What happened instead?

User can probably just see very shortly the UI described here https://github.com/matrix-org/matrix-react-sdk/pull/5130#issue-681944072 (second picture).
But after that a user can just use Element normally (only sees the small notification pop up like thing in the top left corner that can be dismissed).

When logging in with another device (and resetting encryption) a user is forced to backup.

### Operating system

Windows

### Browser information

Brave Version 1.38.117 Chromium: 101.0.4951.67

### URL for webapp

app.element.io

### Homeserver

Synapse Docker v1.59.1

### Will you send logs?

No

**Comment by richvdh** [comment] 2024-06-26 11:09
duplicate of https://github.com/element-hq/element-web/issues/24105

**Closed by richvdh** 2024-06-26 11:09 UTC
Labels: T-Defect, S-Major, A-E2EE-Key-Backup, X-Needs-Investigation, O-Uncommon
