### ISSUE TITLE
Make Use of the standardized org.freedesktop.appearance.color-scheme to read dark mode preference

### ISSUE THREAD

**Issue by sam9032** [element-hq/element-web#19306] opened 2021-10-06 07:33 UTC
#### What would you like to do?
Change the dark/light preference detection with the Use of 
the new org.freedesktop.appearance.color-scheme key.

#### Why would you like to do it?
It would be amazing if element changes its theme as soon as the desktop environment switches from light to dark or vice versa.

#### How would you like to achieve it?

The current detection of the dark/light preference under Linux only takes place at program startup. When the desktop environment changes from light to dark or vice versa, element does not notice this.
Recently the org.freedesktop.appearance.color-scheme key got standardized across all DEs, which should be more reliable and more easy to use.
It would fix the Issue vector-im/element-desktop#881 and similar ones for linux users if the DE supports the new standard key.

Useful links:
[Gnome blog post](https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/)  
[Spec](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45) 
[KDE implementation](https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/49)

**Comment by t3chguy** [comment] 2021-10-06 08:24
Presumably Electron/Chromium already map this to the prefers-dark media selector, the issue is we don't react to it changing after the app has started.

**Comment by sam9032** [comment] 2021-10-06 08:33
> Presumably Electron/Chromium already map this to the prefers-dark media selector, the issue is we don't react to it changing after the app has started.

Hm okay, didn't know that.
So is there a way to react to it, after the app has started? Like element gets triggered if the prefers-dark media selector changes in electron?

**Comment by t3chguy** [comment] 2021-10-06 09:09
Sure, we just don't have it hooked up, I'm just saying that the issue isn't Desktop/Linux specific.
More of a duplicate of https://github.com/vector-im/element-web/issues/15459

**Closed as completed** 2021-10-07 08:05 UTC
Labels: A-Electron, T-Enhancement, O-Uncommon
