### ISSUE TITLE
Missing session data

### ISSUE THREAD

**Issue by vranki** [element-hq/element-web#27446] opened 2024-05-07 17:17 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

I closed element desktop from taskbar.

3. What do you click?

Started element desktop again

#### What did you expect?

Element starting

#### What happened instead?

Element warns about missing session data and forces a log out. There is 15 gigs of free space on disk.

![image](https://github.com/element-hq/element-web/assets/81116/54a59570-786f-4b04-a6e7-80fa5861af48)

### Operating system

Ubuntu 24.04

### Application version

Element Desktop 1.11.65 (official deb package)

### How did you install the app?

Official deb repo

### Homeserver

hacklab.fi

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-05-07 17:20
Duplicate of https://github.com/element-hq/element-desktop/issues/1568

**Closed by t3chguy** 2024-05-07 17:20 UTC
Labels: T-Defect, S-Critical, A-Session-Mgmt
