### ISSUE TITLE
Failed to restore session

### ISSUE THREAD

**Issue by Biep** [element-hq/element-web#27029] opened 2024-02-18 21:59 UTC
### Steps to reproduce

1. I stopped Element and shut down the computer.
2. I restart the computer and restart Element, and it tells me that it failed to restore the session.
![afbeelding](https://github.com/element-hq/element-web/assets/12461597/cc98a051-2c09-419f-922d-52907387feab)

#### What did you expect?
To get back into my Element session

#### What happened instead?
I got the panic screen shown above.

### Operating system

Ubuntu 22.04

### How did you install the app?

From the standard repo.

### Homeserver

synod.im

### Will you send logs?

Yes

**Comment by Biep** [comment] 2024-02-18 22:07
I started another "sleeping" (web) session so as not to lose my keys, and then quit Element Desktop.  When I restarted it, the session came up fine.  No need to log out or clear the cache.

**Comment by Angedestenebres** [comment] 2024-02-19 08:31
Hey :cat: 

I noticed the same issue on one of my computer with the flatpak version. As always, I closed Element and the shut down my computer and when I restarted it and launched again Element, my session can't be restored.

Impacted version: 1.11.58

On another computer with Element installed from element repo (deb), it still work normally for the moment.

**Comment by BillCarsonFr** [comment] 2024-02-19 09:01
Duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed by BillCarsonFr** 2024-02-19 09:01 UTC
Labels: T-Defect
