### ISSUE TITLE
Clicking next to the arrow next to a space with sub-spaces in folded sidebar state crashes the application

### ISSUE THREAD

**Issue by almereyda** [element-hq/element-web#27532] opened 2024-06-06 19:21 UTC
### Steps to reproduce

1. Fold the sidebar
2. Click on the small triangle icon next to a space with sub-spaces

#### What did you expect?

No crash.

#### What happened instead?

A crash that sent me here

### Operating system

Ubuntu

### Application version

The error reporting modal doesn't tell, but maybe should? It also offers me to download a ragshake.tar, so it knows where I'm heading ...

### How did you install the app?

https://flathub.org/apps/im.riot.Riot

### Homeserver

liiib.re

### Will you send logs?

Yes

**Comment by almereyda** [comment] 2024-06-06 19:23
This was reproducible. It doesn't seem to be the triangle, but rather the application border. Maybe this is a packaging issue in https://github.com/flathub/im.riot.Riot?

**Comment by almereyda** [comment] 2024-06-06 19:25
Three, four times in a row now. Very reproducible. Switching back to web.

**Comment by almereyda** [comment] 2024-06-06 19:27
While we're at it.

https://github.com/element-hq/element-web/assets/1645308/412d06ac-cfce-49ec-9d8e-1c66ea18c88d

**Comment by glungtung** [comment] 2024-06-06 19:46
I'm struggling with this exact same bug since few days.
I'm using Synapse + Element from Docker, Version de Element : 1.11.68 (Firefox on macos)

On page loading i get these errors in console : `Uncaught (in promise) ReferenceError: can't access lexical declaration 'Q' before initialization   J  Markdown.ts:395`
When it crashes i get thes errors`TypeError: Node.compareDocumentPosition: Argument 1 is not an object.
    y RovingTabIndex.tsx:103`

**Comment by t3chguy** [comment] 2024-06-06 20:21
Duplicate of https://github.com/element-hq/element-web/issues/27503

**Closed by t3chguy** 2024-06-06 20:21 UTC
Labels: T-Defect, S-Critical, A-Subspaces

**Comment by almereyda** [comment] 2024-06-07 08:52
Thanks.
