### ISSUE TITLE
"Unable to restore session" if home server is down

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#27033] opened 2024-02-19 11:00 UTC
### Steps to reproduce

1. Stop my home server
2. Open a new tab to an element web that was previously connected to that home server

#### What did you expect?

A recoverable error like "Check your connection"

#### What happened instead?

"Unable to restore session" with button "Clear storage and sign out".

This encourages me to delete my session, potentially losing access to all my historical messages, even though that won't help and is not necessary.

### Operating system

Ubuntu 22.04

### Browser information

Chromium 121.0.6167.160

### Homeserver

My local synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-02-19 11:01
Duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed by t3chguy** 2024-02-19 11:01 UTC
Labels: T-Defect
