### ISSUE TITLE
Please do not force us to stare at our blury, enlarged profile pictures

### ISSUE THREAD

**Issue by CrimsonFez** [element-hq/element-web#27381] opened 2024-04-23 03:58 UTC
#### What would you like to do?
Currently, when you set a profile picture it becomes the background image.

With Profile Picture
![with_pfp](https://github.com/element-hq/element-web/assets/46582994/b6baa189-125b-4235-8bc0-eb3e1e7cdb3b)

Without Profile Picture
![default](https://github.com/element-hq/element-web/assets/46582994/417dd137-adc6-4190-a2a0-98f0f6fec215)

Let us have the default or allow us to set the background image/color.

### Have you considered any alternatives?

I could leave my profile picture unset, but I don't like that either.

### Additional context

Can anyone explain why this design decision was made? It really sucks for profile pictures that have colors that clash with the default theming of element.

**Comment by t3chguy** [comment] 2024-04-23 08:22
Duplicate of https://github.com/element-hq/element-web/issues/14665

**Closed by t3chguy** 2024-04-23 08:22 UTC
Labels: T-Enhancement
