### ISSUE TITLE
Toggle in Settings not visible in ON state

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27178] opened 2024-03-13 22:07 UTC
### Steps to reproduce

1. Go to settings
2. Observe and switch a toggle

#### What did you expect?
Clearly visible on and off states

#### What happened instead?
Off state looks grey, so that's ok, but On state is completely black and it's unclear even that this is a toggle.

![image](https://github.com/element-hq/element-web/assets/640121/76c8cf48-fdfa-4a47-8d26-67ba8d05eaef)

![image](https://github.com/element-hq/element-web/assets/640121/bc659ea1-5b53-451b-8989-55059c36399d)

### Operating system

Windows 11

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-03-13 22:08
Duplicate of https://github.com/element-hq/element-web/issues/27166

**Closed by t3chguy** 2024-03-13 22:08 UTC
Labels: T-Defect
