### ISSUE TITLE
Expanding / Collapsing a Space Crashes the App

### ISSUE THREAD

**Issue by hazecodeio** [element-hq/element-web#27583] opened 2024-06-15 18:33 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Any time really

2. What do you click?
Expand, collapse, then expand a space.

3. More steps…
None

#### What did you expect?
A normal expand / collapse of a space

#### What happened instead?
Crash

TypeError: Cannot read properties of null (reading 'compareDocumentPosition')
    at y (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1765194)
    at Array.sort (<anonymous>)
    at _ (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1765511)
    at Object.ds [as useReducer] (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4257403)
    at t.useReducer (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4369105)
    at E (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1766563)
    at ss (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4256175)
    at qs (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4265673)
    at Wa (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4309038)
    at Dl (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4295411)
2024-06-15T18:07:30.531Z E Cannot read properties of null (reading 'compareDocumentPosition')
TypeError: Cannot read properties of null (reading 'compareDocumentPosition')
    at y (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1765194)
    at Array.sort (<anonymous>)
    at _ (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1765511)
    at Object.ds [as useReducer] (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4257403)
    at t.useReducer (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4369105)
    at E (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1766563)
    at ss (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4256175)
    at qs (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4265673)
    at Wa (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4309038)
    at Dl (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:4295411)
2024-06-15T18:07:30.531Z E The above error occurred while React was rendering the following components: 
    at E (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:1766419)
    at mi (vector://vector/webapp/bundles/c73469086a55f7f61043/9892.js:2:163663)
    at div
    at div
    at div
    at div
    at Bv (vector://vector/webapp/bundles/c73469086a55f7f61043/9892.js:2:750419)
    at zv (vector://vector/webapp/bundles/c73469086a55f7f61043/9892.js:2:750662)
    at h (vector://vector/webapp/bundles/c73469086a55f7f61043/bundle.js:2:2096753)
    at cS (vector://vector/webapp/bundles/c73469086a55f7f61043/9892.js:2:1128434)
2024-06-15T18:07:42.148Z D Sending bug report.
2024-06-15T18:07:42.203Z D FetchHttpApi: --> GET https://matrix-client.matrix.org/_synapse/admin/v1/server_version
2024-06-15T18:07:42.648Z D FetchHttpApi: <-- GET https://matrix-client.matrix.org/_synapse/admin/v1/server_version [445ms 200]

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.11.68 Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### How did you install the app?

https://element.io/download#linux

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-16 01:33
Duplicate of https://github.com/element-hq/element-web/issues/27503

**Closed by t3chguy** 2024-06-16 01:33 UTC
Labels: T-Defect, S-Critical, A-Spaces
