### ISSUE TITLE
Element apps stuck on loading because of default home server being unavailable.

### ISSUE THREAD

**Issue by marknefedov** [element-hq/element-web#28187] opened 2024-10-12 09:26 UTC
### Steps to reproduce

1. Open Element web client on a fresh system.
2. App fails to load if matrix-client.matrix.org is unavailable or response is tampered.

#### What did you expect?
Client falls back to "Choose homeserver" or any other option to switch default server.
#### What happened instead?
Stuck on loading.

<img width="1486" alt="image" src="https://github.com/user-attachments/assets/0221076e-85ed-4e41-8b69-59df77b221ee">

### Operating system

All

### Homeserver

default

### Will you send logs?

Yes

Related to https://github.com/element-hq/element-web/issues/28050
Related to https://github.com/element-hq/element-ios/issues/7854

**Comment by t3chguy** [comment] 2024-10-18 12:47
Cannot reproduce

<img width="1705" alt="image" src="https://github.com/user-attachments/assets/0358dfdf-377c-4554-8955-800e5e77eee0">

This was previously an issue and was claimed to be fixed in https://github.com/element-hq/element-web/issues/11154#issuecomment-1628613218

**Comment by t3chguy** [comment] 2024-11-19 10:06
Closing as presumed fixed

**Closed by t3chguy** 2024-11-19 10:06 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Login, O-Uncommon
