### ISSUE TITLE
Element oftentimes crashes with "Something went wrong!" when expanding the list of subspaces underneath a space

### ISSUE THREAD

**Issue by ArrayBolt3** [element-hq/element-web#27518] opened 2024-06-04 02:45 UTC
### Steps to reproduce

1. Make sure you have joined a space and at least one or more sub-spaces of that space. (The Ubuntu Community space and its subspaces are good at triggering this.)
2. Click the little right-facing arrow next to the top-level space to hide (or show) it.
3. Keep clicking that arrow until it crashes, it doesn't take very long.

#### What did you expect?
The list of subspaces should appear and disappear reliably.

#### What happened instead?
Sometimes when attempting to make the list of subspaces appear, Element will suddenly drop to the "Something went wrong!" screen.

### Operating system

Ubuntu 24.04 LTS

### Application version

1.11.67

### How did you install the app?

Official deb repo from packages.element.io

### Homeserver

ubuntu.com (Synapse, version unknown)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-04 08:48
Duplicate of https://github.com/element-hq/element-web/issues/27503

**Closed by t3chguy** 2024-06-04 08:48 UTC
Labels: T-Defect, S-Major, A-Subspaces
