### ISSUE TITLE
Sent msg in a thread; it entirely vanished

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#26632] opened 2023-11-23 14:17 UTC
### Steps to reproduce

1. Open thread
2. Send a message
3. Switched room
4. It then vanished

#### What did you expect?

Messages which don't disappear.

### Application version

Element Nightly version: 2023112301 Crypto version: Rust SDK 0.6.0 (17d4f2f), Vodozemac 0.5.0

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-11-27 08:21
Thank you for reporting the issue!

With `2023-11-23T14:10:24.973Z W EventTimelineSet.addEventToTimeline: Ignoring event=$abc(belongs to thread=$def) that does not belong in timeline=!jkl:server.dev:2023-11-23T09:29:21.973Z timelineSet(threadId=undefined)` from the logs this is probably a duplicate of https://github.com/vector-im/element-web/issues/26494

Could it be that the thread root was not loaded @ara4n ?

**Comment by t3chguy** [comment] 2024-01-31 09:44
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.

**Closed by t3chguy** 2024-01-31 09:44 UTC
Labels: T-Defect, X-Needs-Info
