### ISSUE TITLE
Thread deleted message pops up for a very short time on load

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#23003] opened 2022-08-05 09:02 UTC
### Steps to reproduce

1. Start a thread
2. Delete the thread and the message
3. Reload

#### What did you expect?

Not seeing my deleted message

#### What happened instead?

Deleted message pops up for a short time period („Hi“ message in video)

![hi](https://user-images.githubusercontent.com/6216686/183042735-6c060402-d992-4f61-8f9e-ad5af6075976.gif)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 103.0.1

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 3e3f279469ad-react-e864dbfacf01-js-3907d1c28f87 Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by turt2live** [comment] 2022-08-05 22:03
I don't think this is a bug we'll be able to fix. The sync accumulator didn't have a chance to persist the redaction, so it's still using the original event.

**Comment by MadLittleMods** [comment] 2022-08-09 02:54
We can fix the sync accumulator persist better instead of [every 5 minutes](https://github.com/matrix-org/matrix-js-sdk/blob/c3d7a4977afadb032867775120d0f571ee087b29/src/store/indexeddb.ts#L40). Currently, this would be hard because it's one big giant JSON that takes a while to persist but we can refactor how we store things to be more managable.

This kind of edge case also causes the "Beware: edge case" explained in https://github.com/matrix-org/matrix-react-sdk/pull/8354 where the history refresh can appear multiple times.

**Comment by t3chguy** [comment] 2024-11-27 21:20
Closing due to no reproduction in over 2 years

> We can fix the sync accumulator persist better instead of [every 5 minutes](https://github.com/matrix-org/matrix-js-sdk/blob/c3d7a4977afadb032867775120d0f571ee087b29/src/store/indexeddb.ts#L40). Currently, this would be hard because it's one big giant JSON that takes a while to persist but we can refactor how we store things to be more managable.

https://github.com/element-hq/element-web/issues/13243

**Closed by t3chguy** 2024-11-27 21:20 UTC
Labels: T-Defect, X-Won't-Fix, S-Tolerable, A-Storage, O-Uncommon
