### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by poptart262** [element-hq/element-web#28527] opened 2024-11-22 18:46 UTC
### Steps to reproduce

1. Where are you starting? From the Search Bar       What can you see? I see the search bar start to appear but when I start to type it closes and the letters Ive typed display in the last chat box I used.
2. What do you click? Search (Ctrl+K)
3. More steps… If I try 2-4 times it eventually works. We also noticed that Typing fast causes it to close and if we Type very slowly it doesnt close. 

I cannot add Screenshots because its too fast to capture.

### Operating system

Windows 10

### Application version

11.11.86

### How did you install the app?

Through the Browser 

### Homeserver

chat.serverplus.com

### Will you send logs?

No

**Comment by david-crespo** [comment] 2024-11-23 04:36
https://github.com/element-hq/element-web/issues/28493 

They fixed it, it'll be in the next release.

**Comment by t3chguy** [comment] 2024-11-23 12:25
Duplicate of https://github.com/element-hq/element-web/issues/28493

**Closed by t3chguy** 2024-11-23 12:25 UTC
Labels: T-Defect, S-Major, O-Frequent, A-Spotlight-Search
