### ISSUE TITLE
Pressing send message to user in side panel opens the new room in historical tab

### ISSUE THREAD

**Issue by Gnuxie** [element-hq/element-web#21101] opened 2022-02-16 12:38 UTC
### Steps to reproduce

1. Click on someone in the side panel of a room
2. Click send message
3. Joining thing opens
4. The room gets put into the historical users section

#### What did you expect?

The room to go under people
#### What happened instead?

it went under historical and my only options on the '...' was to forget the room

### Operating system

Manjaro Linux (kernel 5.15.16-1)

### Browser information

Firefox 96.0.3

### URL for webapp

app.element.io/

### Application version

Element version: 1.10.3
Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-02-17 05:43
I don't think I can repro on develop.element.io

**Comment by t3chguy** [comment] 2024-11-18 12:23
Closing due to lack of reproduction in multiple years

**Closed by t3chguy** 2024-11-18 12:23 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Minor, A-Room-List, O-Uncommon
