### ISSUE TITLE
one.element.io doesn't start anymore in Firefox 128

### ISSUE THREAD

**Issue by sd2k9** [element-hq/element-web#27864] opened 2024-07-26 15:35 UTC
### Steps to reproduce

Since around the Element Web update around 18.07.2024
I cannot use Element Web at https://one.element.io/ anymore.

Clearing browser cache or stored data doesn't help.

Can I somehow find out why Element thinks that the latest Firefox release is not a supported browser?

Thank you!

#### What did you expect?
Login to Matrix Element One

#### What happened instead?
![image](https://github.com/user-attachments/assets/a116e5c3-5525-4d62-95cf-c6eacf43bd97)

Looking at the firefox console I can see the following error:
```
Error: Unsupported browser
    c compat.ts:34
    a BackgroundAudio.ts:27
    q Notifier.ts:116
    ts Notifier.ts:535
    Webpack 3
[rageshake.ts:77:16](webpack://element-web/react-sdk/src/rageshake/rageshake.ts)
    t rageshake.ts:77
    <anonymous> logger.ts:97
    ts index.ts:231
```

### Operating system

Debian GNU/Linux 12 (bookworm)

### Browser information

Firefox 128.0 (64-bit)

### URL for webapp

https://one.element.io

### Application version

Element version: 1.11.71

### Homeserver

Element One

### Will you send logs?

No

**Comment by sd2k9** [comment] 2024-07-26 15:41
Complete output of Firefox Console is attached. Is there anything else I can provide or check myself? Thanks!

[firefox_console.txt](https://github.com/user-attachments/files/16393843/firefox_console.txt)

**Comment by t3chguy** [comment] 2024-07-26 18:07
Duplicate of https://github.com/element-hq/element-web/issues/27793
Your browser has a required feature disabled, this feature isn't optional in the web spec.

**Closed** 2024-07-26 18:07 UTC
Labels: T-Defect, S-Critical, O-Frequent

**Comment by t3chguy** [comment] 2024-07-29 15:19
Maintaining how to modify your browser back to stock is not feasible for such a small team. Browsers don't agree on such internal behaviours and they are not the same between browsers. Different options appear with every update.

**Comment by sd2k9** [comment] 2024-07-29 15:34
I understand - and agree - that giving instructions about settings for all browsers out there is not feasible.

I was just wondering, wouldn't it be possible to give more details about a failure? Like a "Your browser is missing WebAudio" instead of "unsupported browser"? This should make debugging (and solving) of problems much easier for everybody - would I have gotten this message I could have solved the problem myself without the need of your help.  
Isn't this especially helpful for a small team, giving your users the knowledge to solve as many issues as possible by themself?

There are restricted environments out there where returning to stock is not possible, but modifying some settings may be.

Anyway, again thanks for your help and your consideration of my suggestion.

**Comment by mpeter50** [comment] 2024-08-15 02:23
> We already have a WebAudio Modernizr check loaded which should do exactly that, its just a case of a new release coming out to make use of them.

If you mean an error message in the console, I guess thats something, but its not really visible, and it can be hard to find among the few dozen other messages when you are supposed to be doing something else than debugging software.

![image](https://github.com/user-attachments/assets/083554ee-dfd6-4259-b606-1c10c246d91f)

In that case, I think having this text message about the missing feature on the displayed webpage besides the "Unsupported browser" text would be more helpful.

**Comment by t3chguy** [comment] 2024-08-15 08:53
@mpeter50 riot.grin.hu is on 1.11.72 which is 2 versions out of date so doesn't have the latest error I spoke about earlier.

**Comment by mpeter50** [comment] 2024-08-15 21:03
Oh, sorry. I thought "Enable audio/webaudio Modernizr rule (https://github.com/element-hq/element-web/pull/27772)" in the changelog was about that.

**Comment by mpeter50** [comment] 2024-08-30 01:05
I think this is still happening on app.element.io, which runs Element version 1.11.76.
If webaudio is disabled, the page still only shows a generic "unsupported" message, while the console logs the lack of webaudio support:

|app.element.io page error message|developer console output|
|-|-|
|![image](https://github.com/user-attachments/assets/5a5b4cc8-5267-4e61-a52a-5eecc5244d9a)|![image](https://github.com/user-attachments/assets/db9bc803-b75c-46b9-9ef1-f09a3309d898)|

Should I open an issue for this? Asking in case I have just overlooked something.
