### ISSUE TITLE
Element said that I have to close the session and lose the data

### ISSUE THREAD

**Issue by yajo** [element-hq/element-web#26979] opened 2024-02-07 07:35 UTC
### Steps to reproduce

1. Opened Element.
2. Big dialog telling me to lose my data.
3. I want to get the logs, it asks me to create an issue... here it is ❤️ 

#### What did you expect?
Not loosing data.

#### What happened instead?
![imagen](https://github.com/element-hq/element-web/assets/973709/1a118d3c-e35f-4869-9562-cadef4599f20)

Clicked red button.
Lost it.

### Operating system

Fedora Silverblue 39

### Application version

Element version: 1.11.57, Olm version: 3.2.14

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment] 2024-02-08 16:38
Looks like a duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed** 2024-02-08 17:49 UTC
Labels: T-Defect, S-Major, O-Uncommon, Team: Crypto, Z-Labs, A-Element-R

**Comment by BillCarsonFr** [comment] 2024-02-12 13:10
There are several places where version is called and could reject:
- In `Lifecycle` > `restoreFromLocalStorage` > `await checkServerVersions()`
- In `ServerSupportUnstableFeatureController` `await this.client.isVersionSupported(this.stableVersion))`

There other places where it's check but there is some basic retries, like in `DeviceListener` > `cli.isVersionSupported("v1.1")`


Maybe there should be some global retry on getVersion, and also throw something specific to be checked against in `handleLoadSessionFailure` and show something else?
Given the nature of getVersion, we might want to retry forever on certain errors though
