### ISSUE TITLE
EDR apparently corrupted itself with "Unable to restore session"

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27028] opened 2024-02-18 19:36 UTC
### Steps to reproduce

1. Upgraded macOS
2. Launched EDR on wobbly wifi

![Screenshot 2024-02-18 at 19 32 54](https://github.com/element-hq/element-web/assets/1294269/89c1a373-a276-47ba-91f4-0f53c22f698f)

3. Relaunched and it seems okay? maybe?

#### What did you expect?

App not to give terrifying warnings about having corrupted itself, telling the user to logout when in practice just restarting the app is all that's needed.

### Application version

Nightly 2024021701

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment] 2024-02-19 09:01
Duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed by BillCarsonFr** 2024-02-19 09:01 UTC
Labels: T-Defect
