### ISSUE TITLE
Cannot close or switch thread, attempting to close it brings it back automatically

### ISSUE THREAD

**Issue by dkasak** [element-hq/element-web#27313] opened 2024-04-10 08:33 UTC
### Steps to reproduce

1. I'm in a room with an open thread in the sidebar
2. I click the thread sidebar close `x` button
3. The sidebar briefly disappears, before instantly reappearing with the same thread open
4. Clicking on another thread fails to open that thread in the sidebar

#### What did you expect?

For the thread sidebar to behave normally (closing, switching threads).

#### What happened instead?

The opposite of the above.

### Operating system

Arch Linux

### Application version

Element version: 1.11.63 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### How did you install the app?

Arch Linux repo

### Homeserver

Synapse 1.98.0

### Will you send logs?

Yes

**Comment by dkasak** [comment] 2024-04-10 08:35
Switching rooms seems to have helped resolve it.

**Comment by t3chguy** [comment] 2024-04-10 08:39
Duplicate of https://github.com/element-hq/element-web/issues/27271

**Closed by t3chguy** 2024-04-10 08:39 UTC
Labels: T-Defect
