### ISSUE TITLE
Allow flipping through images when in gallery mode

### ISSUE THREAD

**Issue by fsiddi** [element-hq/element-web#27592] opened 2024-06-18 00:36 UTC
### Steps to reproduce

1. Visit https://element.blender.org/#/room/#extensions-web:blender.org and click on one image
2. Once the image is enlarged, try to see another image by pressing left or right key

(Was advised to report this as a bug after a conversation with Matthew)

#### What did you expect?
I expect to be able to press right and left arrow keys to flip through the images.

#### What happened instead?
Nothing.

### Operating system

macOS Sonoma 14.5 (23F79)

### Browser information

Chrome Version 125.0.6422.176 (Official Build) (arm64)

### URL for webapp

https://element.blender.org/#/room/#extensions-web:blender.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-18 08:16
Duplicate of https://github.com/element-hq/element-web/issues/337

**Closed by t3chguy** 2024-06-18 08:16 UTC
Labels: T-Defect, S-Minor, A-Light-Box
