### ISSUE TITLE
When back-paginating, the jump to last read message can appear and point upwards, when in reality the last read message is below us...

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#9535] opened 2019-04-21 10:46 UTC

**Comment by lampholder** [comment] 2019-04-24 09:18
P2ing this 'cause I have no idea on frequency and it seems a tricky one to pin down for the relative value - if people see this again (and can dump some logs when they do) it might be more realistic to chase down.

**Comment by t3chguy** [comment] 2024-11-18 12:25
Closing due to lack of reproduction in over a year

**Closed by t3chguy** 2024-11-18 12:25 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Tolerable, A-Timeline, O-Uncommon
