### ISSUE TITLE
Can't connect session to key backup, leading to lost keys

### ISSUE THREAD

**Issue by schildbach** [element-hq/element-web#23497] opened 2022-10-15 12:52 UTC
### Steps to reproduce

- Go to Safety & Privacy settings
- Encryption→Secure Backup says: "This session is not backing up your keys, but you do have an existing backup you can restore from and add to going forward. Connect this session to key backup before signing out to avoid losing any keys that may only be on this session."
- Click "Connect this session to Key Backup"
- It restores the keys from the backup. (Why? I'd expect to actually backup my keys _to_ the backup, rather than restoring from it.)
- After the process is finished, nothing has changed. Encryption→Secure Backup still says: "This session is not backing up your keys, but you do have an existing backup you can restore from and add to going forward. Connect this session to key backup before signing out to avoid losing any keys that may only be on this session."

#### What did you expect?
A message like "This session is backing up your keys"

#### What happened instead?
"This session is not backing up your keys"

### Operating system

Ubuntu 22.04.1

### Application version

1.11.10

### How did you install the app?

flatpak install flathub im.riot.Riot

### Homeserver

Synapse 1.68.0

### Will you send logs?

Yes

**Comment by dbkr** [comment] 2022-10-17 13:18
I strongly suspect this won't be actionable without logs.

**Comment by schildbach** [comment] 2022-10-17 13:23
I just sent logs.

**Comment by schildbach** [comment] 2022-11-12 21:15
I just retested on Element 1.11.14 – this time on the webapp. t's still not working as expected – the backup cannot be enabled and the keys are lost on logout.

**Comment by schildbach** [comment] 2022-11-22 13:24
I just retested on Element 1.11.15 and Synapse 1.72.0 – same issue.

**Comment by schildbach** [comment] 2022-11-22 13:26
…and I sent debug logs again, just in case.

**Comment by AIlkiv** [comment] 2023-01-11 15:25
I had the same problem.
Solving:
1. "Export E2E room keys"
2. In section "Secure Backup" click "Reset" for create new backup.
3. "Import E2E room keys"

Result, I have correct message "This session is backing up your keys."

**Comment by valynor** [comment] 2023-04-25 15:00
I have the same issue as OP. 
Element version: 1.11.30
Olm version: 3.2.12

Despite the message suggesting that keys are not backed up properly everything is working fine on all of my 4 sessions. 
This is only on element-web, on iPhone and iPad it says that it's backing up the keys from the session.

**Comment by sascha-wi** [comment] 2023-05-24 08:22
Same issue here.

Element version: 1.11.31
Olm version: 3.2.14

On linux. When trying to "connect this session to key backup" it gives some kind of progress with count of 400 something being reached and "Keys restored Sucsessfully restored 491 keys". Clicking ok dialog disappears. But reopening security setting still says "this session is **not backing up your keys**"

**Comment by valynor** [comment] 2023-08-01 18:31
Element-Web 1.11.37 on two different Macs, still the same issue: 
"This session is not backing up your keys"

Just to check if this would change something I logged out & deleted the desktop session completely from browser storage. 
Logged in, verified .. same issue: "This session is not backing up your keys". 

I think this should get some priority getting fixed, it's very confusing to say the least.

**Comment by sevenrats** [comment] 2024-03-06 14:00
Losing conversations to this bug. Very disappointing.  It appears that having a second session open and in sync can function as a workaround though.  For example, my android device is properly connected to key backup, so if my Android is in sync when I log out of desktop, then the keys will be backed up properly by the Android device and can be restored to the desktop by verification.  However, if the Android is not in sync when I log out, keys and conversations are lost.  This is very inconvenient, but certainly a much better workaround than manual key management.

**Comment by sascha-wi** [comment] 2024-03-11 12:47
```
Element version: 1.11.59
Crypto version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1
```
Under cryptography in Settings -> Security & Privacy it still shows "Session key: <not supported>"

**Comment by richvdh** [comment] 2024-03-11 14:41
Duplicate of https://github.com/element-hq/element-web/issues/26530, I think

**Closed by richvdh** 2024-03-11 14:41 UTC
Labels: T-Defect, S-Major, A-E2EE-Key-Backup, X-Needs-Investigation, O-Uncommon
