### ISSUE TITLE
error in console log.

### ISSUE THREAD

**Issue by hallo43** [element-hq/element-web#28609] opened 2024-12-02 07:08 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
build Synapse and Element-web the latest version
3. What do you click?
only access login page

#### What did you expect?
there is not error in console log.
#### What happened instead?
Uncaught (in promise) ReferenceError: Cannot access 'F' before initialization
    at Object.J (init.js:1:81507)
    at b.start (init.js:1:1216028)
    at get instance (init.js:1:1336089)
    at ./src/stores/widgets/WidgetLayoutStore.ts (init.js:1:1344116)
    at u (bundle.js:2:83424)
    at ./src/utils/WidgetUtils.ts (init.js:1:1402119)
    at u (bundle.js:2:83424)
    at ./src/stores/ActiveWidgetStore.ts (init.js:1:1193739)
    at u (bundle.js:2:83424)
    at ./src/stores/WidgetStore.ts (init.js:1:1220472)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-12-02 08:54
Duplicate of https://github.com/element-hq/element-web/issues/27606

**Closed by t3chguy** 2024-12-02 08:54 UTC
Labels: T-Defect, S-Minor, A-Widgets, O-Uncommon
