### ISSUE TITLE
Redirected to out of date room after logging in

### ISSUE THREAD

**Issue by michaelbeaumont** [element-hq/element-web#16669] opened 2021-03-11 22:14 UTC
### Description

When I go to https://app.element.io/#/room/#rtic:matrix.org (logged out), I see an up to date room (active, with messages from today). When I log in with my account from mozilla.org, I'm instead redirected to an older room (not active, with the latest message from June 2020) #rtfm-rs:matrix.org (the room was renamed as far as I understand it)

### Steps to reproduce

- Navigate to `#rtic:mozilla.org` (e.g. with https://app.element.io/#/room/#rtic:matrix.org)
- Log in with an account with homeserver `mozilla.modular.im`
- See the out of date room `#rtfm-rs:mozilla.org`

Instead I should see the same room as before I logged in.

Logs being sent: no

### Version information

- **Platform**: web & desktop

For the web app:

- **Browser**: Firefox 87.0b7
- **OS**: Arch Linux

For the desktop app:

- **OS**: Arch Linux
- **Version**: Element version: 1.7.22, olm version: 3.2.1

**Comment by t3chguy** [comment] 2024-11-25 16:13
Closing due to lack of logs and no reproduction in multiple years

**Closed by t3chguy** 2024-11-25 16:13 UTC
Labels: T-Defect, P3, S-Minor, X-Needs-Investigation
