### ISSUE TITLE
Session cannot be restored.

### ISSUE THREAD

**Issue by toneji** [element-hq/element-web#26920] opened 2024-01-24 14:09 UTC
### Steps to reproduce

When I start up element, I get the following error message.
<img width="819" alt="スクリーンショット 2024-01-24 23 05 16" src="https://github.com/element-hq/element-web/assets/5512055/55505752-0438-4331-82cd-2076a4590810">

### Outcome

unresolved

### Operating system

macOS Sonoma 14.3

### Application version

element v1.11.55

### How did you install the app?

https://github.com/element-hq/element-web/releases/tag/v1.11.55

### Homeserver

synapse v1.99.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-01-24 14:13
> Will you send logs?
Yes

Please provide these logs

**Comment by toneji** [comment] 2024-01-24 14:54
Resolved.
The reason was that the certificate had expired.
I apologize for the trouble.

**Comment by richvdh** [comment] 2024-02-16 10:54
Duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed by richvdh** 2024-02-16 10:54 UTC
Labels: T-Defect, X-Needs-Info
