### ISSUE TITLE
Connecting session to backup fails - failed to decrypt sessions

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#26932] opened 2024-01-26 11:46 UTC
### Steps to reproduce

1. Think you have key backup enabled
2. go to settings to check
3. see button "Connect this session to Key Backup"
4. better click it to be safe, don't want to lose my message history!
5. hit OK
6. back to 1

#### What did you expect?
Backup works/gets enabled
#### What happened instead?
> Keys restored
> Successfully restored 8575 keys
> Failed to decrypt 501 sessions!

It is not at all explained what this (failed part) means, nor does it lead to a failure mode of having failed to set up the backup

### Operating system

arch

### Browser information

Firefox 121

### URL for webapp

https://develop.element.io

### Application version

Element version: e6543bbde642-react-38f791b79db5-js-35ea144bcaed Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by akoyaxd** [comment] 2024-02-18 16:14
I experience the same issue since a few weeks. Can't tell exactly. Maybe noteworthy: I use Element X for Android and iOS on parallel with the legacy apps and Element web.

**Comment by HarHarLinks** [comment] 2024-02-18 16:24
Ftr, I have all kinds of clients, incl legacy and X clients on Android and iOs in use on that account. The issue appeared before migration to Web R and is still present after.

**Comment by akoyaxd** [comment] 2024-02-19 18:25
Another side note:
manually exporting and importing my e2ee keys works. But this does not seem to fix the backup. On new Devices I still get the error, that some sessions can not be imported.

**Comment by richvdh** [comment] 2024-03-12 12:28
Duplicate of #26530

**Closed by richvdh** 2024-03-12 12:28 UTC
Labels: T-Defect, S-Major, O-Uncommon, Team: Crypto
