### ISSUE TITLE
Inefficient use of space for edited messages in narrow windows 

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#27974] opened 2024-08-29 09:29 UTC
### Steps to reproduce

Make Element narrow and edit a message

#### What did you expect?

More efficient use of space

#### What happened instead?

Wasted space starting from v1.11.74

| v1.11.73 | v1.11.74 |
| - | - |
| ![screenshot_2024-08-29T09-14-08Z](https://github.com/user-attachments/assets/c83bcd4e-a2e2-48b6-8fb3-36db72c584e9) | ![screenshot_2024-08-29T09-13-52Z](https://github.com/user-attachments/assets/c0f47c5b-4163-4684-b052-721c709cc9e9) |

### Operating system

Fedora 40

### Browser information

Firefox 129.0.2 (64-bit)

### URL for webapp

https://riots.im/1.11.74

### Application version

v1.11.74 and later

### Homeserver

Doesn't matter but matrix.org in the above screenshots

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-08-29 11:11
Duplicate of https://github.com/element-hq/element-web/issues/1633

**Closed by t3chguy** 2024-08-29 11:11 UTC
Labels: T-Defect, S-Minor, A-Message-Editing, A-Appearance, O-Occasional
