### ISSUE TITLE
Can't Read All Messages In Browser

### ISSUE THREAD

**Issue by muellert** [element-hq/element-web#27795] opened 2024-07-21 17:16 UTC
### Steps to reproduce

1. I am using Elements on a mobile.
2. I exported the session key and copied it to my computer.
3. I opened 'app.element.io, logged in with the same account I'm using on my mobile, and verify this with my Elements on my mobile (no other method works).
4. I select a channel.
5. I see "Unable to decrypt message" everywhere.
6. I import an "E2E room key".
7. I still see "Session key: &lt;not supported&gt;".

#### What did you expect?

I expected to be able to read all messages in that channel.

#### What happened instead?

Some messages are readable. Others still show "Unable to decrypt message".

So far, it seems as if only messages I sent from my mobile while I was logged out in the browser, are unreadable in the browser once I log in there, while messages which I received during that same time, are readable.

### Operating system

Debian 12

### Browser information

Chromium 121.0.6167.139 (Official Build) built on Debian 12.4, running on Debian 12.6 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.71 Crypto version: Rust SDK 0.7.1 (80a151e), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

No  (what would be in those logs?)

**Comment by ruben1PvP** [comment] 2024-07-22 18:48
I have the same issue. I've seen that:
1. It doesn't matter if you CTRL + F5 or if you log out and log in again.
2. It doesn't matter what method you use to decrypt the messages (verifying by another device or using the secret key).
3. It happened to me in Firefox and in Windows 10.
4. Sometimes it says that the key backup is not working, others that it does but the session is waiting (eternally) to get them.

I basically have one device where I can't decrypt the messages from my e2e rooms. The others are ok. Even new messages that I sent from the session where the decryption is not working are decrypted in other devices without any problem.

**Comment by dbkr** [comment] 2024-07-29 12:01
This will need investigation to see if there's a particular, exact sequence of steps to trigger the bug. Otherwise, this is going to be tough to investigate without logs.

**Comment by ruben1PvP** [comment] 2024-07-29 15:24
> This will need investigation to see if there's a particular, exact sequence of steps to trigger the bug. Otherwise, this is going to be tough to investigate without logs.

Is it even possible for us (The people who have the problem) to get logs and send them here?
For us, the "exact sequence of steps" is just logging in in app.element.io and verifying the session.

**Comment by t3chguy** [comment] 2024-07-31 19:26
> I import an "E2E room key".

These keys you're exporting/importing only contain keys to history at that moment in time, as megolm keys are cycled and new ones are formed any time someone joins or leaves a room to ensure Perfect Forward Secrecy. So this explains why you keep having fewer messages available as you load the same key into newer sessions.

**Comment by muellert** [comment] 2024-07-31 19:29
I don't understand how logging in to the same room with the same account, just on a different browser, constitutes "joining" a room. Regarding the room in question, there are only two people in it, me, and someone else. It has been like that from day one, and there will be no change.

**Comment by t3chguy** [comment] 2024-07-31 19:41
> I don't understand how logging in to the same room with the same account, just on a different browser, constitutes "joining" a room.

Each of your devices has its own cryptographic identity (olm), if that didn't happen then if someone compromised your device, e.g. it was stolen, they'd be able to not only decrypt history but also future. Megolm sessions are also rotated periodically, every N messages & every M days. So again, your export only guarantees the history from before it is decryptable.

**Comment by muellert** [comment] 2024-07-31 19:55
Good point. So the reason why my older messages are all readable on my phone is because they're re-encrypted with the new key?

**Comment by t3chguy** [comment] 2024-07-31 20:02
You haven't given enough information about your phone to know which device it is in this series. Once a device is authenticated it'll receive any new megolm sessions from that point onwards but have no access to history unless you have keybackup (or manual key export as in your case) and then the messages for which the keys were included in the backup will be decryptable.

**Comment by ruben1PvP** [comment] 2024-07-31 20:38
> > I import an "E2E room key".
> 
> These keys you're exporting/importing only contain keys to history at that moment in time, as megolm keys are cycled and new ones are formed any time someone joins or leaves a room to ensure Perfect Forward Secrecy. So this explains why you keep having fewer messages available as you load the same key into newer sessions.

In my case this would not be the case, knowing that if I log in another client (like Fluffychat) or in Element Android **after logging in web and having these problems**, all the encrypted messages are visible. Can mine be considered then a new problem? Do I have to open a new issue myself?

**Comment by t3chguy** [comment] 2024-07-31 20:39
sounds like you are using key backup and for some reason it isn't getting restored, have you tried manually restoring it?

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/58b81f4b-1460-463d-af60-75464741a2f5">

**Comment by ruben1PvP** [comment] 2024-07-31 20:48
> sounds like you are using key backup and for some reason it isn't getting restored, have you tried manually restoring it?
> <img alt="image" width="1105" src="https://private-user-images.githubusercontent.com/2403652/353991295-58b81f4b-1460-463d-af60-75464741a2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTg2NzcsIm5iZiI6MTcyMjQ1ODM3NywicGF0aCI6Ii8yNDAzNjUyLzM1Mzk5MTI5NS01OGI4MWY0Yi0xNDYwLTQ2M2QtYWY2MC03NTQ2NDc0MWEyZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMjAzOTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZjYTI1MTc4ZjgwN2RkZmEwOGQ3YmRkY2Y4NmViMjgzNWMyZDQ4NTliNWZjZWYxNzkxOGRmZmVmZmM2ZTY4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qx7xxFyHRkbiNXrB7vD72SZeCYFmajAGGMKFg_1NTdw">

I don't know how that would change a thing, it asked me for my security key like it did multiple times before and, as I said before, that doesn't work.

**Comment by richvdh** [comment] 2024-09-17 16:13
Duplicate of element-hq/element-meta#245

**Closed by richvdh** 2024-09-17 16:13 UTC
Labels: T-Defect, S-Major, A-E2EE, O-Occasional
