### ISSUE TITLE
Live Location Share - Missing system permissions can fail silently

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#22668] opened 2022-06-28 06:46 UTC
### Steps to reproduce

- Disable location services for Chrome** in system settings***
- Go to element, enable location services for the tab
- Try to share live location

** Test in FF too
*** Test on other distributions than osx
→ unable to reproduce on Ubuntu 22.04 LTS

#### What did you expect?

„Could not fetch location“ dialogue

![image](https://user-images.githubusercontent.com/6216686/176114873-486d7b02-e7cf-452f-9cf5-38d733e14b6b.png)

#### What happened instead?

It will hang and then eventually show permission denied error in log

### Operating system

macOS

### Browser information

Chrome

### Will you send logs?

No

---

PSD-281

**Comment by weeman1337** [comment] 2022-06-28 07:04
We should probably change the dialogue text to something like:

- Failed to fetch your location
- Check your browser permissions
- Check your system permissions

„Please try again“ later doesn't really help.

**Comment by weeman1337** [comment] 2022-06-28 09:19
Cannot reproduce on Ubuntu 22.04 LTS. This issue should be investigated by someone with the environment mentioned in the description (macOS).

**Comment by t3chguy** [comment] 2024-11-18 12:23
Closing due to lack of reproduction in multiple years

**Closed by t3chguy** 2024-11-18 12:23 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, O-Uncommon, Z-Labs, A-Location-Sharing
