### ISSUE TITLE
Encrypted messages cannot be decrypted. Important!

### ISSUE THREAD

**Issue by devosonder** [element-hq/element-web#26808] opened 2023-12-26 11:05 UTC
### Steps to reproduce

1. Element > Settings > Sessions > Select all other sessions  (not required)
2. Click the "Sign Out" button above the Sessions list  (not required)
4. Sign out of your current element
5. Log in again.
6. Enter your Security Phrase
7. See that none of the old messages can be decrypted.

#### What did you expect?
Sign Out ve Sign In islemlerinden sonra Security Phrase ile dogrulama islemi yapilir. Tum mesajlarin gorunur olmasi gerekiyor.

#### What happened instead?
After Sign Out and Sign In, verification is done with Security Phrase. No message is readable.

### Operating system

Windows and MacOS

### Browser information

Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit)

### URL for webapp

app.element.io and develop.element.io

### Application version

Element: 1.11.52 Crypto version: Olm 3.2.15

### Homeserver

Synapse docker v1.98.0

### Will you send logs?

Yes

**Comment by devosonder** [comment] 2023-12-26 11:21
The following error message is written dozens of times in console.
```
rageshake.ts:77 Error decrypting event (id=$R7RftYCW1tzgmiLdpVril3owPmzln6nO6CrEpP-dV8M type=m.room.encrypted sender=@devosonder:matrix.org room=!ieMLULGUrRgkasaeOo:matrix.org ts=2023-12-26T09:36:09.148Z): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: rMbenX62MzHoZs4wIlM0e1+DQ59Ebn7+nhEqrE5N5TY|HVvgG0p9SpyoluMxCV7B4OtiTroNOorzDsCSwDa6+tI]
e.<computed> @ rageshake.ts:77
(anonymous) @ logger.ts:97
decryptionLoop @ event.ts:923
```

**Comment by devosonder** [comment] 2023-12-26 11:56
Sign Out and Sign In without deleting the Sessions. Again, the messages will not be readable.

**Comment by devosonder** [comment] 2023-12-26 11:56
Sign Out and Sign In without deleting the Sessions. Again, the messages will not be readable.

**Comment by websharik** [comment] 2023-12-26 13:09
~ week ago same problem. Old messages cannot be decrypted, but latest messages was decrypt fine (looks as before/after some update). Today all messages cannot be decrypted.

**Comment by devosonder** [comment] 2023-12-26 13:43
> ~ week ago same problem. Old messages cannot be decrypted, but latest messages was decrypt fine (looks as before/after some update). Today all messages cannot be decrypted.
> 
> On manual import element-keys from latest session, will decrypt "middle" messages (old, and new messages stay crypted).

This is a big problem. I hope it will be fixed soon.

**Comment by jazzroutine** [comment] 2023-12-27 11:52
Same here. 
Latest stable Synapse - 1.98.0
Latest web client - 1.11.52
Docker compose

I have only web client, this is my ONLY device. 
I have only to users on my matrix server - User1 & User2

Initial setup was OK, made an Security Phrase, no problem here.
I've created a chat between users and typed some messages. 

Both users signed out from web client and signed in after 5 minutes. 
Login, pass, Security Phrase, everything is green.

All messages are encrypted!!! No way to decrypt them. No errors or anything, just encrypted messages. 

If I pull previous image of web client - **1.11.51** - everything is started to work as expected again!

**Comment by MidhunSureshR** [comment] 2024-01-04 08:24
Duplicate of https://github.com/element-hq/element-web/issues/26814. Closing this in favor of that issue since it contains a bit more technical info.

**Closed by MidhunSureshR** 2024-01-04 08:24 UTC
Labels: T-Defect, X-Regression, S-Major, A-E2EE-Key-Backup, O-Frequent
