### ISSUE TITLE
Toggling light/dark theme changes the emoji font

### ISSUE THREAD

**Issue by anoadragon453** [element-hq/element-web#27172] opened 2024-03-13 10:35 UTC
### Steps to reproduce

1. Open up a room and type an emoji into the composer
2. Use the "light/dark" theme toggle button to toggle between light and dark themes.
3. See the emoji change from Twemoji to something else(?)

#### What did you expect?

The emoji font to not change.

#### What happened instead?

[Screencast from 2024-03-13 10-32-28.webm](https://github.com/element-hq/element-web/assets/1342360/77a377bf-3f21-4cbd-aa93-2ef014fc705d)

### Operating system

NixOS Linux

### Application version

Element version: 1.11.59, Crypto version: Olm 3.2.15

### How did you install the app?

From https://github.com/NixOS/nixpkgs/

### Will you send logs?

Yes

**Comment by anoadragon453** [comment] 2024-03-13 10:37
Note: I was _not_ able to reproduce this on develop.element.io (1.11.60) in Firefox stable (123.0).

**Comment by t3chguy** [comment] 2024-03-13 10:38
Duplicate of https://github.com/element-hq/element-web/issues/26248

**Closed by t3chguy** 2024-03-13 10:38 UTC
Labels: T-Defect

**Comment by anoadragon453** [comment] 2024-03-13 10:40
Ahh, I was searching for "emote"/"emoji". Thanks for the quick response as always!
