### ISSUE TITLE
Jitsi screen sharing Windows App 3+ participants not working

### ISSUE THREAD

**Issue by dimkaskv** [element-hq/element-web#27329] opened 2024-04-12 20:40 UTC
### Steps to reproduce

Start Element Windows app
Make 3+ meeting group
Start videocall with Camera button
Try to share screen
You receive error, as its iFrame with iFrame, so Jitsi can't ask Allow for screen sharing.

### Outcome

Hey guys, time to fix it. Main well known issue.
Windows Element app dont allow share screen with Jitsi.
We terminate using Element in our big organisation just because this issue.

### Operating system

Windows 11

### Application version

1.11.64

### How did you install the app?

https://element.io/download

### Homeserver

matrix.rogator.de

### Will you send logs?

Yes

**Comment by dimkaskv** [comment] 2024-04-12 20:45
Only navigator.mediaDevices.getDisplayMedia() in console of webapp helps.

**Comment by t3chguy** [comment] 2024-04-15 07:41
Duplicate of https://github.com/element-hq/element-desktop/issues/683

**Closed by t3chguy** 2024-04-15 07:41 UTC
Labels: T-Defect
