### ISSUE TITLE
Blank thread right side panel

### ISSUE THREAD

**Issue by MarcWadai** [element-hq/element-web#27687] opened 2024-07-08 16:34 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I see on the main chat that there is 2 messages in the thread

2. What do you click?
I click on the thread under the message to open the thread side panel 

3. More steps…
I cannot reproduce it consistently. It also happens that sometimes the timeline of the thread is also missing some messages while it was displaying more in the main chat. It might be related to this bug.
When refreshing the page (sometimes mutliple times) it is working again.

![image](https://github.com/element-hq/element-web/assets/10048869/892b6e29-2e05-42b4-ab06-0d733cd08a46)

#### What did you expect?
To see the messages in the thread panel

#### What happened instead?
Blank right side panel 

### Operating system

linux

### Browser information

firefox 126

### Application version

1.11.70

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-07-09 08:23
Duplicate of https://github.com/element-hq/element-web/issues/24623

**Closed by t3chguy** 2024-07-09 08:23 UTC
Labels: T-Defect, S-Major, A-Right-Panel, O-Occasional, A-Threads
