### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by stemy2** [element-hq/element-web#28733] opened 2024-12-13 16:19 UTC
#### What would you like to do?
Use multiple accounts in the same app.
#### Why would you like to do it?
I have 2 accounts, including one in a non-federated instance, i'd like to use them both without using 2 instances.
### Have you considered any alternatives?

Using apps with multiple account support, but they lack functionalities, and element would be THE perfect app if it implemented that.

**Comment by t3chguy** [comment] 2024-12-17 09:07
Duplicate of https://github.com/element-hq/element-meta/discussions/1681

**Closed by t3chguy** 2024-12-17 09:07 UTC
Labels: T-Enhancement, T-Feature
