### ISSUE TITLE
Windows on ARM64 Build

### ISSUE THREAD

**Issue by Jasonthefirst** [element-hq/element-web#27654] opened 2024-06-28 09:08 UTC
#### What would you like to do?

Now that the new Snapdragon Elite ARM processors out, I would like to see a windows on arm ARM64 build as it would help the performance significantly. The prism emulated Version works but stutters sometimes and takes more battery than necessary. 
Now that chrome (chromium) supports ARM64 natively it should be possible.

### Have you considered any alternatives?

The prism emulation works but is slower and less performant.

**Comment by t3chguy** [comment] 2024-07-01 08:56
Duplicate of https://github.com/element-hq/element-desktop/issues/650

**Closed by t3chguy** 2024-07-01 08:56 UTC
Labels: T-Enhancement, T-Feature
