### ISSUE TITLE
Voice call failure when trying to share the screen

### ISSUE THREAD

**Issue by kosmos** [element-hq/element-web#27522] opened 2024-06-05 13:40 UTC
### Steps to reproduce

1. During a voice call
2. Click the "Share Screen" button

#### What did you expect?

The screen is expected to be shared with the participants of the call.

#### What happened instead?

The call is interrupted during a voice call after pressing the “Expand Screen” key.

### Operating system

MacOS

### Application version

Element Version 1.11.68

### Homeserver

Synapse 1.106

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-06-05 16:00
Duplicate of https://github.com/element-hq/element-desktop/issues/1703

**Closed by t3chguy** 2024-06-05 16:00 UTC
Labels: T-Defect, S-Major, A-VoIP
