### ISSUE TITLE
Show date when scrolling

### ISSUE THREAD

**Issue by claell** [element-hq/element-web#26925] opened 2024-01-24 17:19 UTC
#### What would you like to do?
Always see the date that messages were sent, also when scrolling through them.

#### Why would you like to do it?
Orientation, for example when searching for some information, etc.

#### How would you like to achieve it?
When scrolling, I want to see the date, possibly as a hover or something.

### Have you considered any alternatives?

Actively looking for dates in long message lists is pretty tiresome (scrolling 100 messages, then seeing the date entry, then again more messages, etc.). Fast scrolling to find a specific date is pretty hard that way.

### Additional context

Related issue for Element X Android: https://github.com/element-hq/element-x-android/issues/2270

**Comment by t3chguy** [comment] 2024-01-24 17:34
> When scrolling, I want to see the date, possibly as a hover or something.

You can already hover on the timestamp to see it

<img width="156" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/2df3ae14-5757-4655-8531-d8bf167fa50b">


Duplicate of https://github.com/element-hq/element-meta/issues/2277 otherwise

**Closed by t3chguy** 2024-01-24 17:34 UTC
Labels: T-Enhancement

**Comment by claell** [comment] 2024-01-24 17:39
Ah, good hint!
However, that isn't really good UX, for example when scrolling.

Also, I don't know whether your referenced issue is good UX, either. That suggests showing the date on all messages. Again, when scrolling, that is not that easy to spot and clutters the UI a bit. Mobile applications do it as in the referenced Element X Android issue.
However, showing the date on every message might be okay as well.

**Comment by t3chguy** [comment] 2024-01-24 17:43
@claell https://github.com/element-hq/element-meta/issues/1230 then - which is referenced from the other issue

**Comment by claell** [comment] 2024-01-24 17:45
Sure, though that scope was originally for jumps, not scrolling. 😉 But it's okay to not open more issues about this!

**Comment by HarHarLinks** [comment] 2024-02-08 15:36
I think it is sticky date deviders https://github.com/element-hq/element-web/issues/7575 that we want. It is currently combined and entangled with the `/jumptodate` feature and respective labs flag.
