### ISSUE TITLE
Requested rageshake for UTD

### ISSUE THREAD

**Issue by Arkaniad** [element-hq/element-web#27879] opened 2024-07-30 21:40 UTC
### Steps to reproduce

This rageshake was requested following a UTD

### Outcome

This rageshake was requested following a UTD

### Operating system

MacOS Sonomoa 14.6

### Browser information

Firefox 128.0.3 (20240725162350)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.72 Crypto version: Rust SDK 0.7.1 (431263d), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-07-31 08:54
Duplicate of https://github.com/element-hq/element-meta/issues/245

**Comment by t3chguy** [comment] 2024-07-31 08:54
Thanks for the logs

**Closed by t3chguy** 2024-07-31 08:54 UTC
Labels: T-Defect
