### ISSUE TITLE
Repeated and frequent requests to specific endpoints cause Synapse logs to bloat rapidly.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-web#27246] opened 2024-03-27 04:34 UTC
### Steps to reproduce

1. Update to 1.11.62 (Desktop, x64 Windows);
2. If you do not have a logged in account, please log in first.

#### What did you expect?
n/a

#### What happened instead?
After upgrading to 1.11.62, it was discovered through devtool that Element was requesting certain endpoints repeatedly and frequently, which caused Synapse's CPU usage to increase and the log to be filled up heavily.
![{CCAD32D5-422E-4323-18AC-0955328C202B}](https://github.com/element-hq/element-web/assets/48104960/83766dfe-48c8-42b0-bc49-82f74373c8ed)
![{87ED1736-F1AA-2E4C-E85F-842504521C4F}](https://github.com/element-hq/element-web/assets/48104960/0a6045cb-a621-4b64-b590-72f0bbee4618)

**This comes under the self-hosted scenario.**

### Operating system

x64 Windows 11 (10.0.22631)

### Application version

Element Desktop 1.11.62

### How did you install the app?

https://packages.element.io/desktop/update/win32/x64/index.html

### Homeserver

Synapse 1.103.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-03-27 09:40
Duplicate of https://github.com/element-hq/element-web/issues/27173

**Closed by t3chguy** 2024-03-27 09:40 UTC
Labels: T-Defect
