### ISSUE TITLE
When opening room, view should start on the last unread message

### ISSUE THREAD

**Issue by bicolino34** [element-hq/element-web#27415] opened 2024-05-01 08:25 UTC
#### What would you like to do?
I want an option so that I can change default behaviour of opening room with view on the latest new messages. I want my messenger to always show me the last message I haven't read.

#### Why would you like to do it?
I prefer to read all the messages in chats I joined and every time when I open the room I have to click the button to go to the last unread message. And it's a little bit inconvenient. Also, it seems to be the default behaviour for most messangers to start from the unread messages, not the latest sent.

#### How would you like to achieve it?
Setting option to change the default behaviour

**Comment by t3chguy** [comment] 2024-05-01 08:27
Duplicate of https://github.com/element-hq/element-meta/issues/1548

**Closed by t3chguy** 2024-05-01 08:27 UTC
Labels: T-Enhancement
