### ISSUE TITLE
Messages in threads always in reverse order on conduwuit

### ISSUE THREAD

**Issue by GearKite** [element-hq/element-web#27664] opened 2024-07-03 07:56 UTC
### Steps to reproduce

1. Be on any Conduwuit homeserver
2. Create a thread, send some messages
3. Restart client to sync again
4. Open thread
5. See messages in reverse order

https://github.com/element-hq/element-web/assets/29222413/d26931a3-3640-4c62-b107-e652191b64bc

(This also happens on Element Desktop.)

#### What did you expect?
Messages in the order that they were sent
#### What happened instead?
Messages were in the reverse order

### Operating system

NixOS

### Browser information

LibreWolf 127.0

### URL for webapp

app.element.io

### Application version

Element version: 1.11.69 Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### Homeserver

transfem.dev

### Will you send logs?

Yes

**Comment by dbkr** [comment] 2024-07-03 09:34
The title would suggest this is probably a bug with that homeserver impl, but I'll leave this open in case anyone wants to investigate and confirm.

**Comment by ashishnd** [comment] 2024-07-03 12:18
Hey, I tried reproducing the issue that you mentioned above on the web application using both Google Chrome and LibreWolf 127.0 from Windows 11 OS.

 I did not encounter the above mentioned problem of messages getting into reverse order in threads but I did come across a slightly smaller issue which is when I write a message which is only a small integer, like the number 1 for example, and open a thread for that message, then the number is duplicated in one more line for about 5-6 seconds and then disappears making things back to normal in both Google Chrome and LibreWolf on Windows 11 OS.

Here is the video:

https://github.com/element-hq/element-web/assets/58184732/248a39f7-fb2e-4af9-94dc-70cd4d273cf1

Please let me know if I've missed something!

**Comment by GearKite** [comment] 2024-07-03 12:25
Looking at the URL, seems like you are on matrix.org. This issue happens when your account is on a [conduwuit](https://github.com/girlbossceo/conduwuit) homeserver (like transfem.dev).

**Comment by t3chguy** [comment] 2024-07-03 20:46
https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv1roomsroomidthreads is vague and does not specify the sort order, just that 

> ordered by the latest_event in each event’s aggregated children. 

Closing as a server/spec issue.

**Closed by t3chguy** 2024-07-03 20:46 UTC
Labels: T-Defect, S-Minor, O-Uncommon, A-Threads

**Comment by isosphere** [comment] 2024-07-08 02:07
> https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv1roomsroomidthreads is vague and does not specify the sort direction, just that

The sort order should be chronological, from the earliest to the latest message. I agree the spec does not make this clear, but it is how all threaded communication has worked since USENET; those writing the spec may have taken that for granted. 

I've forked conduwuit (https://github.com/isosphere/conduwuit/tree/504_sort_threads) to sort the threads by server timestamps before sending them back to the client and it does not change Element's behaviour - even if I reverse the server's sort order. Element Android displays the same behaviour; it's consistently reversed - unless you have the thread open while new messages come in. 

nheko does not exhibit this behaviour with the same server.
