### ISSUE TITLE
Export of threads, linked to the main conversation

### ISSUE THREAD

**Issue by lili36** [element-hq/element-web#27688] opened 2024-07-09 06:05 UTC
#### What would you like to do?
Unless I didn't find the option, when exporting a conversation, it doesn't export the threads in it.
I get a special cursor as for a link, but no link.
It would be great to also export the threads, with internal link.
Or even, as intermediate option, the thread it self as conversation.

#### Why would you like to do it?
Right now, when exporting a conversation in html, I don't get the threads in it and found no way to export the theads one by one.

#### How would you like to achieve it?
When exporting the chat, have an option "include threads" we can choose or not.
If chosen, export the threads with an html file by thread, and each thread's html file would be linked in the main one.

### Have you considered any alternatives?

I google it and tried to explore the options, but I am not an expert to use a complex solution, just an end-user.

**Comment by t3chguy** [comment] 2024-07-09 07:28
Duplicate of https://github.com/element-hq/element-web/issues/27259

**Closed by t3chguy** 2024-07-09 07:28 UTC
Labels: T-Enhancement, A-Export-Chat, T-Feature
