### ISSUE TITLE
Emoji picking on Sonoma (and others?) is broken

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27072] opened 2024-02-26 12:18 UTC
### Steps to reproduce

1. Be on macOS on ED - may require Sonoma
2. Be in composer, in normal markdown mode
3. Try to add an emoji in the composer via ctrl-cmd-space
4. You may get an single-emoji suggestion based on the previous word you typed, e.g.

![Screenshot 2024-02-26 at 12 15 27](https://github.com/element-hq/element-web/assets/1294269/9e69061b-ee44-4139-9327-c100e68184c5)

5. You hit enter to select it
6. Rather than selecting it, it sends your message :(
7. It then prepopulates the composer with the emoji by itself.

#### What did you expect?

Looks like the focus ordering/hierarchy is wrong: hitting enter to select the emoji should fire before enter to send the message

#### What happened instead?

Vice versa

### Operating system

macOS Sonoma 14.3.1

### Application version

Element Nightly version: 2024022601 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ara4n** [comment] 2024-02-26 12:18
The same happens (most of the time?) if macOS triggers the full emoji picker, and not just the single-emoji suggestion.  Although even weirder things happen if you transition from single-emoji to full picker (in that no emoji gets inserted at all?)

**Comment by t3chguy** [comment] 2024-02-26 16:14
I cannot reproduce


https://github.com/element-hq/element-web/assets/2403652/68a4c16e-9146-47f1-afd6-5663578ec58d

macOS 14.2.1 (23C71)

**Comment by dbkr** [comment] 2024-03-08 14:46
Nor can I

**Comment by t3chguy** [comment] 2024-03-22 11:04
Closing due to inability to reproduce, including on latest Sonoma.

**Closed by t3chguy** 2024-03-22 11:04 UTC
Labels: T-Defect, X-Cannot-Reproduce
