### ISSUE TITLE
New image view is hard to tell where the image ends and the metadata begins

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#27184] opened 2024-03-14 10:51 UTC
### Steps to reproduce

1. send a screenshot of ux
2. open it

#### What did you expect?
can tell what is UI and what is screenshot
#### What happened instead?
all blends together

### Application version

Element version: 54ba0873dada-react-c42562ef3967-js-8e0ef5ff2cd9 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-03-14 10:52
Duplicate of https://github.com/element-hq/element-web/issues/27175

**Closed by t3chguy** 2024-03-14 10:52 UTC
Labels: T-Defect

**Comment by HarHarLinks** [comment] 2024-03-14 11:01
really? i realize 27175 is titled "image view is broken" but the description is about overflowing the window, not it being completely-should-not-have-been-merged-broken.
