### ISSUE TITLE
Warn on logout if there are message keys pending backup

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#14830] opened 2020-07-30 15:37 UTC
Or probably a spinner with an option to skip & discard the keys. Probably a bit of an edge case as they'd generally be uploaded promptly, unless you're offline in which case you're not receiving message keys at all.

**Comment by dbkr** [comment] 2020-07-30 15:40
It looks like soft logout tries to do something like this but see https://github.com/vector-im/riot-web/issues/14829

**Comment by richvdh** [comment] 2024-06-26 11:06
duplicate of #27267

**Closed by richvdh** 2024-06-26 11:06 UTC
Labels: T-Enhancement, A-E2EE-Key-Backup
