### ISSUE TITLE
Notification from a room I can't see, join, or leave

### ISSUE THREAD

**Issue by progval** [element-hq/element-web#28479] opened 2024-11-17 14:49 UTC
### Steps to reproduce

For a few months now, Element has been showing me a notification from #codeberg.org:matrix.org, but when I click it it says "Codeberg can't be previewed. Do you want to join it?", and the "Join the discussion" button under it results in:

```
Failed to join
MatrixError: [403] You do not belong to any of the required rooms/spaces to join this room. (https://matrix-client.matrix.org/_matrix/client/v3/join/!ImcWflUWyvAekDFLHt%3Amatrix.tu-berlin.de)
```

#### What did you expect?

be able to join the room or dismiss the notification

#### What happened instead?

I can't join the room or dismiss the notification

### Operating system

Debian 12

### Browser information

Firefox 128.4.0esr

### URL for webapp

https://riot.im/app/

### Application version

Element version: 1.11.85 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-11-18 10:03
> Element has been showing me a notification from #codeberg.org:matrix.org

Where exactly are you seeing the notifications, in what form? If you're receiving events from a room you cannot join then that sounds like a server issue rather than a client issue.

**Comment by t3chguy** [comment] 2024-11-18 11:04
Duplicate of https://github.com/element-hq/element-web/issues/24392

**Closed by t3chguy** 2024-11-18 11:04 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-Notifications, O-Uncommon

**Comment by progval** [comment] 2024-11-18 17:45
Are you sure it's a duplicate? I'm not even in the room, and I don't see this situation among the issues listed there

**Comment by progval** [comment] 2024-11-24 08:19
Now I can see the room and Element offers me to leave it, but I get this error when I try to leave it: "MatrixError: [403] @pinkie:matrix.org not in room !wkyjxWeAOBpKMvHbno:matrix.org. (https://matrix-client.matrix.org/_matrix/client/v3/rooms/!wkyjxWeAOBpKMvHbno%3Amatrix.org/leave)"
