### ISSUE TITLE
My messages are not visible to receiver, the receiver sees "waiting for this message"

### ISSUE THREAD

**Issue by naccaccio** [element-hq/element-web#28396] opened 2024-11-06 13:31 UTC
### Steps to reproduce

1. Send message on macOS app to another matrix.org user using web app

#### What did you expect?
The receiver sees the message.

#### What happened instead?
The receiver sees "waiting for this message".

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-11-06 14:23
`waiting for this message` is not a string in Element Web, more details would be necessary. Please fill the issue template where you left it blank with No response.

**Comment by t3chguy** [comment] 2024-11-18 12:29
Closing due to lack of required information

**Closed by t3chguy** 2024-11-18 12:29 UTC
Labels: T-Defect, X-Needs-Info, S-Major, A-E2EE, O-Occasional

**Comment by andybalaam** [comment] 2024-11-19 13:45
After investigating the debug logs you sent (thanks!) we think this was caused by https://github.com/matrix-org/matrix-rust-sdk/issues/1415 . (This bug is fixed, but it leaves things on the receiver side in an incorrect state.)

If the receiver logs out and logs in again, the problem should go away. Do get back to us here if that doesn't work.
