### ISSUE TITLE
Progress indicator for key backup restore in background

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#17830] opened 2021-06-29 10:49 UTC
When we restore the key backup automatically on login, or when you restore explicitly and close the dialog, there's no indicator of progress.

**Comment by aaronraimist** [comment] 2022-01-23 18:26
Related: https://github.com/vector-im/element-web/issues/17157 https://github.com/vector-im/element-web/issues/20694

**Comment by richvdh** [comment] 2023-12-12 10:28
seems to be the same as #20694, but that has more info, so let's close this one.

**Comment by richvdh** [comment] 2023-12-12 10:28
Duplicate of #20694

**Closed by richvdh** 2023-12-12 10:28 UTC
Labels: T-Enhancement, A-E2EE-Key-Backup, A-E2EE-Cross-Signing, O-Occasional
