### ISSUE TITLE
Key repeat is very slow

### ISSUE THREAD

**Issue by marekjedrzejewski** [element-hq/element-web#27245] opened 2024-03-26 20:57 UTC
### Steps to reproduce

When typing in the message composer key repeat is much slower than for the rest of the system - noticed it when holding backspace to delete part of message, but it happens for other keys too.
Same issue happens for search field, but on smaller scale.

#### What did you expect?
Standard rate for key repeat

#### What happened instead?
Very slow and inconsistent key repeat

### Operating system

Arch Linux

### Browser information

Firefox 124.0.1

### URL for webapp

app.element.io

### Application version

Element 1.11.62

### Homeserver

Synapse 1.53

### Will you send logs?

No

**Comment by turt2live** [comment] 2024-03-26 22:49
This sounds like a symptom of high CPU usage on your machine. Is it better now than before?

**Comment by t3chguy** [comment] 2024-03-27 09:44
Duplicate of https://github.com/element-hq/element-web/issues/25713

**Closed by t3chguy** 2024-03-27 09:44 UTC
Labels: T-Defect
