### ISSUE TITLE
Clicking on a tile outside the green Join/View button should not join the room

### ISSUE THREAD

**Issue by daniel-pg** [element-hq/element-web#26158] opened 2023-09-13 03:16 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Home Space -> Left Panel -> Explore rooms button on top-right of the panel 

2. What do you click?
Click any room tile below the "Suggestions" label

#### What did you expect?
Clicking on a tile should only expand the room's description. I should only join a room if I click INSIDE the green button area.

#### What happened instead?
I ended up accidentally joining a room i didn't want to.

### Operating system

Manjaro Linux

### Application version

Element version: 1.11.40 Olm version: 3.2.14

### How did you install the app?

Package manager (Pamac)

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-09-13 08:30
https://github.com/vector-im/element-web/assets/2403652/ae989ad5-4f35-4318-945e-fa44996322c0

Cannot reproduce what you mean, can you provide a similar recording please

**Comment by robintown** [comment] 2023-09-13 19:03
Is it possible that you're only looking at the preview of a public room, after tapping the tile?

**Comment by daniel-pg** [comment] 2023-09-13 22:30
Sorry, I think I didn't make the steps to reproduce the problem clear enough.

Home Space -> Left Panel -> Explore rooms button
![Screenshot_20230913_184905](https://github.com/vector-im/element-web/assets/38893804/5fdbf91d-7f36-4e20-9175-f33cf5c170bc)

Click any room tile below the "Suggestions" label, outside the area of the green button
![Screenshot_20230913_192549](https://github.com/vector-im/element-web/assets/38893804/1c754b02-3919-4e70-bd6a-324aaab096b0)

You end up joining/viewing the room regardless of the place where you clicked in the tile.
![Screenshot_20230913_184955](https://github.com/vector-im/element-web/assets/38893804/fb05e353-8cd4-4317-abc6-a1345d66df22)

**Comment by t3chguy** [comment] 2023-09-14 08:22
Weird, for me it says `Loading...` not joining.

https://github.com/vector-im/element-web/assets/2403652/69cb8a81-6110-4ffb-999a-caf30bc9f813

**Comment by daniel-pg** [comment] 2023-09-14 19:25
If the green button says "View", it will load a preview of the room. If the green button says "Join", it will join the room. My problem is that it will join/preview the room regardless of the place I click inside the tile. Clicking the tile should only trigger the action if I click over the green button, not outside of it.

**Comment by t3chguy** [comment] 2023-09-14 19:38
Fair enough, this is as designed

**Comment by daniel-pg** [comment] 2023-09-14 19:40
Yes, this is a problem of misleading user interface, a false affordance. I thought that clicking the tile would only expand the room's description, but instead it will trigger an action. In the worst case, the user can end up joining a room they didn't intend to.

**Comment by florianduros** [comment] 2024-07-04 08:23
Closing in favour of https://github.com/element-hq/element-web/issues/27523

**Closed by florianduros** 2024-07-04 08:23 UTC
Labels: T-Defect, A-Spaces, X-Needs-Design
