### ISSUE TITLE
Allow to manually override online status

### ISSUE THREAD

**Issue by rda0** [element-hq/element-web#26804] opened 2023-12-22 12:33 UTC
#### What would you like to do?

Manually override `online`, `away`, `offline`.

#### Why would you like to do it?

For privacy reasons.

#### How would you like to achieve it?

Right-click menu.

**Comment by t3chguy** [comment] 2023-12-22 15:53
Duplicate of https://github.com/element-hq/element-meta/issues/871

**Closed by t3chguy** 2023-12-22 15:53 UTC
Labels: T-Enhancement

**Comment by rda0** [comment] 2023-12-22 16:38
oops sorry
