### ISSUE TITLE
Stuck notification without any way to remove it

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#26941] opened 2024-01-30 09:54 UTC
### Steps to reproduce

1. In the room list, one room has a stuck notification

![image](https://github.com/element-hq/element-web/assets/640121/23f2d908-f3aa-4a3f-9000-45bd83a8f334)

#### What did you expect?

- Clicking on it, I would expect that the notification goes away.
- Right-clicking on the room, I would expect an option to clear all notifications

#### What happened instead?
I cannot remove it, it doesn't go away, there is no option to clear it.

![image](https://github.com/element-hq/element-web/assets/640121/1e444d87-28f7-4f66-9305-e83f3527167b)

### Operating system

Windows 11

### Application version

Element version: 1.11.56-rc.0 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-01-30 09:56
Duplicate of https://github.com/vector-im/element-web/issues/24392

**Closed by t3chguy** 2024-01-30 09:56 UTC
Labels: T-Defect

**Comment by langleyd** [comment] 2024-01-30 14:38
@kongo09 A fix that address this went into develop last friday so you should see this fixed in the the currently nightly or next release.
