### ISSUE TITLE
Element desktop app is crashing after update. Even nightly build crashes on 10.15.7 mac OS Catalina

### ISSUE THREAD

**Issue by tinkueg** [element-hq/element-web#27060] opened 2024-02-22 21:17 UTC
### Steps to reproduce

I have been using this app for three years and recently I updated since yesterday it is crashing.
1) Install Element from the installation .
2) Launch the app 

See that it crashes!

#### What did you expect?
Element home screen.
#### What happened instead?
Crash. Segmentation Fault.

### Operating system

macOS Catalina 10.15.7 

### How did you install the app?

https://try.element.io/get-started

### Will you send logs?

Yes

**Comment by tinkueg** [comment] 2024-02-22 21:20
[Crash_Report.txt](https://github.com/element-hq/element-web/files/14379462/Crash_Report.txt)

**Comment by t3chguy** [comment] 2024-02-22 21:40
Duplicate of https://github.com/element-hq/element-desktop/issues/1505

**Closed by t3chguy** 2024-02-22 21:40 UTC
Labels: T-Defect
