### ISSUE TITLE
Adding someone else's space as a subspace should require admin as it causes various issues

### ISSUE THREAD

**Issue by MBybee** [element-hq/element-web#26868] opened 2024-01-14 18:04 UTC
### Steps to reproduce

Adding another space as a subspace causes the other space to appear under the new space.
This does not require any permissions from the other space.

#### What did you expect?
There should have been no changes to other space, it should simply exist as a link or a subset of rooms. Members of the other space should have no interruptions.
#### What happened instead?
Members of both spaces can no longer see the space icon unless they expand the new top level space, links seem to go to the top space instead, and if they depart from the top level space and leave rooms, they leave *both* spaces when they should have only left the new space. Not the previously existing one.

This causes confusion, issues, and is open to abuse. Only admins should be able to rearrange spaces.

### Operating system

Linux, Windows, Android 

### Browser information

FF and Chrome

### URL for webapp

https://app.element.io

### Application version

Element version: 1.11.53 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-01-15 09:01
Duplicate of https://github.com/element-hq/element-meta/issues/306

**Closed by t3chguy** 2024-01-15 09:01 UTC
Labels: T-Defect
