### ISSUE TITLE
Delay in sending messages.

### ISSUE THREAD

**Issue by MarkRiot** [element-hq/element-web#7720] opened 2018-11-19 20:24 UTC
### Description

Messages sent from the Win7 app to iOS are facing a delay. This can vary between 10 seconds and over a minute. This has only happened since version 0.17.4 and I am using the Matrix server. 

### Steps to reproduce

The person in the room that suggested raising the issue could not reproduce it. 

A log will be sent to the URL as soon a I submit this.

### Version information

As above.

Additional - I installed 0.16.5 and it's working just as well as it once was. Could the reduction in memory that the current version is using be causing it? Just a thought.

**Comment by lampholder** [comment] 2018-11-23 13:40
Thanks for your report.

Are you measuring the time it takes for the server to accept the message (the time it takes for the message you've sent to change from grey to black), or the time it takes for the message to appeaer on the receiver's device?

Are both sender and recevier on the same homeserver? What time of day were the messages sent?

Thanks!

**Comment by MarkRiot** [comment] 2018-11-26 22:10
Thanks for getting back to me and sorry for the delay in my reply.

At best it's around 10 seconds for the message to turn from gray to black (white in my case). It can be much longer but it's usually 10. After that it's difficult to tell whether the message is received instantly but I believe it is.

Both devices I assume are on the Matrix server. Both apps are pretty much "out the box". The pairing of the devices and ticking of a few boxes in preferences has been the extent of the modifications. 

The time of day doesn't seem to matter. The delay is always there. However, now I know rolling back to 0.16.5 fixes things, as soon as the delay interferes with communicating I do so. Usually within the first couple of minutes of opening Riot after the forced upgrade.

If it helps I've noticed other people make the same complaint in the room. One f them asking if I was using the app on Windows 7. As I am.

**Comment by rdmarsee** [comment] 2019-01-15 15:17
I, too, am facing this, but it only appears to be affecting computers running Windows 7. My Android phone and Linux desktop do not appear to face the same issue.
I have noticed that the problem tends to get worse with the more messages sent. The first 5-10 will send instantly, but beyond a certain point, the text will remain gray for >10 seconds (usually longer) each message.
If the application is closed and restarted, messages are again sent instantly for a short time.

**Comment by jessica21lauren** [comment] 2019-06-10 17:30
My whole team is experiencing a delay in sending and receiving messages consistently

**Comment by thomasfrobieter** [comment] 2020-04-30 13:18
Same here. The delay differs from day to day, not measured it, but sometimes up to a minute.

Windows 10 with Riot client.

**Comment by t3chguy** [comment] 2020-04-30 14:25
Are you using the matrix.org homeserver?

**Comment by t3chguy** [comment] 2020-04-30 14:32
That's the cause of your issue. Other servers don't have such delays.

**Comment by thomasfrobieter** [comment] 2020-04-30 16:12
Oh yeah, works amazingly fast on our own modular.im riot server. Thx!

**Comment by turt2live** [comment] 2020-04-30 16:15
This issue overall sounds like a matrix.org server issue - closing as the problem isn't with Riot.

**Closed as completed by turt2live** 2020-04-30 16:15 UTC
Labels: T-Defect, X-Needs-Info, A-Performance
