### ISSUE TITLE
Element R: App freezes while backing up megolm keys

### ISSUE THREAD

**Issue by anoadragon453** [element-hq/element-web#26488] opened 2023-11-01 13:51 UTC
### Steps to reproduce

1. Log in to https://develop.element.io using my `@andrewm:element.io` account.
2. Put in my key backup passphrase during login, which connects my session to key backup.
3. Attempt to use the app

#### What did you expect?

No freezing.

#### What happened instead?

The app freezes for ~10s at a time, every 2-5s. It appears the UI thread if getting blocked behind something in the Rust crypto layer. Taking a performance recording in Chrome, I see that `wasm-function[xxxx]` is the culprit, but no more data than that.

The app freezes, then once it unfreezes, the following log is printed:

```
 INFO matrix_sdk_crypto::backups: Successfully created a room keys backup request, key_count: 100, keys: {"!JMaTDIsletcCnEaaDp:matrix.org": {"yyyyyyyyyyyyyyyyy": {"zzzzzzzzzzzzzzzz", ... }}}, backup_key: MegolmV1BackupKey { key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", version: Some("1") }
    at /home/work/.cargo/git/checkouts/matrix-rust-sdk-1f4927f82a3d27bb/7440ce0/crates/matrix-sdk-crypto/src/backups/mod.rs:506
```

this continues over and over, each time with a different set of 100 keys.

### Operating system

NixOS Linux

### Browser information

Chromium v118.0.5993.117

### URL for webapp

develop.element.io

### Application version

Both on develop.element.io and when building from latest source today, I also built and linked matrix-rust-sdk-crypto-wasm

### Homeserver

element.io

### Will you send logs?

No

**Comment by richvdh** [comment] 2023-11-01 13:55
Part of the problem here is https://github.com/vector-im/element-web/issues/26347, though that doesn't explain why it locks up the UI while it's happening.

**Comment by richvdh** [comment] 2023-11-01 14:18
@anoadragon453 has sent me a performance profile demonstrating the problem. It shows calls to `<matrix_sdk_indexeddb::crypto_store::IndexeddbCryptoStore as matrix_sdk_crypto::store::traits::CryptoStore>::get_inbound_group_sessions::{{closure}}::hf2c9e7d12573886c` which block for 7 seconds.

**Comment by richvdh** [comment] 2023-11-07 17:05
[`IndexeddbCryptoStore::inbound_group_sessions_for_backup`](https://github.com/matrix-org/matrix-rust-sdk/blob/afcc702/crates/matrix-sdk-indexeddb/src/crypto_store.rs#L962) (which we call repeatedly, until all keys are backed up)  calls `get_inbound_group_sessions`, which decrypts and returns ALL megolm keys recorded in the indexeddb, and *then* filters out the first 100 of those that are already backed up.

This is clearly an insane way to do things.

**Comment by ara4n** [comment] 2023-11-09 15:51
just as a datapoint: disabling seshat has stopped my logs tight-looping with keyshare reqs. but the freezing (presumably due to this bug) is as bad as it was before (and makes the app pretty much unusable).

**Comment by richvdh** [comment] 2023-12-04 10:20
@ara4n unfortunately that profile doesn't tell us a great deal. 

@BillCarsonFr also reported continued freezing after the fix landed, but I don't think we have a profile from him either :(. (He did report that it went away having merged https://github.com/matrix-org/matrix-js-sdk/pull/3934 into his dev copy, but that feels like fixing the symptoms rather than the cause.)

**Comment by anoadragon453** [comment] 2023-12-04 14:17
I too am continuing to experience freezes on:

* Element Web b9d616a0b728f00714a88f5c3bd20212284eee0d
* matrix-react-sdk 7638790095f8f033a8c72627180dd4c589892917
* matrix-js-sdk f31e83fd0375d33e6b0ee1cb8ba95f37f775aeae
* matrix-rust-sdk-crypto-wasm e4576fd8e17b978612fb3d53318c3ec87b022533

Initially, the application runs fine, even after feeding it my key backup passphrase. Then, I go into Security & Privacy settings and try to see the status of key backup. I imagine this trigger key backup to start, at which point the application shows familiar signs of freezing for 5-10s every 5 seconds.

Element employees can view a performance trace from Chromium here: https://matrix.to/#/!UcgyhoigetVICUfvRw:matrix.org/$ykAFN0Z3NRkiyTGVWBLelZpiS72mQ_gXoL19IISZtWA?via=element.io&via=matrix.org&via=jki.re

**Comment by ara4n** [comment] 2023-12-05 09:11
I got a trace from EWR (not EDR) here, fwiw: https://github.com/matrix-org/element-web-rageshakes/issues/23324

**Comment by richvdh** [comment] 2023-12-06 17:26
Ok, it turns out that there is another call to `CryptoStore::get_inbound_group_sessions` (which, per the above, is a disaster area) in the "mark request as sent" path [here](https://github.com/matrix-org/matrix-rust-sdk/blob/e43a25a/crates/matrix-sdk-crypto/src/backups/mod.rs#L485) which explains why we are still seeing problems here.

I think we need a new method in CryptoStore which takes the list of room/sender/session triplets from the backup request, and marks them all as sent. Then we need to burn `CryptoStore::get_inbound_group_sessions` with fire.

**Comment by richvdh** [comment] 2023-12-06 17:36
I think this is also responsible for logs along the lines of:

```
Backup: Error processing backup request for rust crypto-sdk Error: failed to read or write to the crypto store DomException UnknownError (0): The operation failed for reasons unrelated to the database itself and not covered by any other error code."
```

(and also things like `violation: success handler took 10000ms` or words to that effect.)

-- in short, it's taking tens of seconds to read all the inbound group sessions from the store, and indexeddb is complaining about it.

**Comment by ara4n** [comment] 2024-01-05 19:25
The app is still freezing for minutes on end when backing up megolm keys.

**Comment by ara4n** [comment] 2024-01-09 12:10
actually, it's not freezing, it's "just" taking 1-5 mins to send msgs

**Closed by ara4n** 2024-01-09 12:10 UTC
Labels: T-Defect, S-Critical, O-Occasional, Z-Labs, A-Element-R, Z-Element-R-Blocker

**Comment by richvdh** [comment] 2024-01-09 12:18
> actually, it's not freezing, it's "just" taking 1-5 mins to send msgs

ie, it's https://github.com/element-hq/element-web/issues/26783
