### ISSUE TITLE
Room search popup disappears if typing too fast

### ISSUE THREAD

**Issue by tpetazzoni** [element-hq/element-web#28530] opened 2024-11-24 12:57 UTC
### Steps to reproduce

Since a recent update of Element (as of maybe ~2 weeks ago), the room search popup simply disappears if typing too fast.

My Element workflow is heavily based on using Ctrl+K to fire up the room search popup, and then typing some parts of the room I'd like to switch to. This workflow has been working super well for years, and as of a few weeks ago, it stopped working, with the room search popup simply disappearing if I type "too fast". If I intentionally slow down my typing in the popup search box, then everything is fine. But of course, I'd like to type normally, not slowly :-)

I am using Element through Firefox 132.0.1 under Fedora 40.

#### What did you expect?

The room search popup stays so that I can search.

#### What happened instead?

The room search popup closes itself if I type too fast.

### Operating system

Fedora

### Browser information

Firefox 132.0.1

### URL for webapp

https://app.element.io

### Application version

Element 1.11.86

### Homeserver

matrix.bootlin.com, Synapse server

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-11-24 18:34
Duplicate of https://github.com/element-hq/element-web/issues/28493

**Closed by t3chguy** 2024-11-24 18:34 UTC
Labels: T-Defect, S-Major, O-Frequent, A-Spotlight-Search
