### ISSUE TITLE
Deleted events visible in room previews (may be stale room previews in general)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#17893] opened 2021-07-06 16:17 UTC
### Description
if the most recent msg gets redacted in a room, you can still see it in the preview text in the room list.

### Steps: 
1. Enable message previews
2. Send a message "test"
3. Edit the message "test 2"
4. Delete the message

### Expected:
The message "test 2" is not displayed in the preview

### Observed:
The message "test 2" is displayed in the preview

**Comment by t3chguy** [comment] 2021-07-06 16:19
![image](https://user-images.githubusercontent.com/2403652/124634459-47655180-de7e-11eb-83fc-a2fd8aad498a.png)


![image](https://user-images.githubusercontent.com/2403652/124634441-40d6da00-de7e-11eb-8935-d4de394aab5a.png)

**Comment by ara4n** [comment] 2021-07-06 18:26
might be that it was an edited msg that was redacted? or that the user parted the room afterwards?

**Comment by t3chguy** [comment] 2021-07-06 19:16
Right with edits that sounds plausible given a redaction doesn't redact the entire edit chain and message previews will fall-through to the latest message they can show

**Comment by ara4n** [comment] 2021-07-07 13:13
actually, the problem seems to be that all room previews are very stale for me on `Element Nightly version: 2021070403`.

the preview for the room i'm currently looking at is currently ~7 messages behind the actual most recent msg in the room.

**Comment by ara4n** [comment] 2021-09-08 21:22
This is still happening, and it's really annoying as it just can't trust previews any more.

<img width="1132" alt="Screenshot 2021-09-08 at 22 20 48" src="https://user-images.githubusercontent.com/1294269/132587326-d4fca10d-00c1-4f7d-a609-5b3a383e7753.png">

i think it might be getting stuck after a gappy sync? or if the last message was an edit, it gets confused and doesn't update to the next-best value?

**Comment by ara4n** [comment] 2021-10-19 12:24
Just had it again; this time it's not an edited message.  It showed the 3rd most recent message as the preview rather than the most recent one.

**Comment by gsouquet** [comment] 2022-09-27 10:07
Just had another flavour of this issue

**Comment by Johennes** [comment] 2023-05-17 06:20
Reproduced this just now myself.

![Screenshot 2023-05-17 at 08 16 37](https://github.com/vector-im/element-web/assets/1137962/720901fb-d140-48fc-ad26-066924b0593f)

![Screenshot 2023-05-17 at 08 16 28](https://github.com/vector-im/element-web/assets/1137962/96a22089-3e92-4835-8ae1-e0063f0fc3ca)

There seems to be nothing exotic in-between sending the message and redacting it.

![Screenshot 2023-05-17 at 08 19 29](https://github.com/vector-im/element-web/assets/1137962/09e76b50-920c-459a-ab0e-4ff21d2da1bd)

**Comment by t3chguy** [comment] 2023-05-17 07:40
@Johennes that sounds like https://github.com/vector-im/element-web/issues/22334

**Comment by t3chguy** [comment] 2023-05-17 07:40
Actually that one is a duplicate of this whole isse

**Comment by langleyd** [comment] 2024-04-16 09:46
Added repro steps and updated Occurrence. I think at most this falls into the "some users regularly" category. 

We should be following the logic of the timeline. I'll have a look and if it's easy to re-use that logic will add a fix.

**Closed** 2024-04-17 12:54 UTC
Labels: T-Defect, X-Regression, S-Major, A-Message-Previews, O-Occasional
