### ISSUE TITLE
Permanent white screen with disabled registration and identity server invites

### ISSUE THREAD

**Issue by gabrc52** [element-hq/element-web#26606] opened 2023-11-19 17:00 UTC
### Steps to reproduce

1. Host Element on a custom URL, say matrix.example.org
2. Set `setting_defaults` -> `UIFeature.registration` to `false` and `disable_guests` to `true`
3. A user who has not logged in nor registered their email to the matrix.org identity server receives an email invite to a room through the matrix.org identity server (copy the link saying "Join the conversation" and paste it in an incognito window)

For reference, the URL has a structure like https://matrix.example.org/#/room/%21roomid%3Amatrix.org?email=jack%40example.org&signurl=https%3A%2F%2Fmatrix.org%2F_matrix%2Fidentity%2Fapi%2Fv1%2Fsign-ed25519%3Ftoken%3Dlongstringofthings%26private_key%3Dbla&room_name=test%20room&room_avatar_url=&inviter_name=Gabriel%20R.&guest_access_token=&guest_user_id=&room_type=

In reproducing this bug, you could try visiting this URL directly.

5. Element redirects you to https://matrix.example.org/#/register with a white screen
6. Any subsequent attempts to use Element, such as manually navigating to https://matrix.example.org/ result in being redirected back to the white screen

#### What did you expect?

I am able to use Element

#### What happened instead?

White screen. Trying to switch to a different URL has Element redirect you back to `#/register`

![image](https://github.com/vector-im/element-web/assets/24363938/4a54abba-a9df-4b3a-9499-8a846ea06f6f)

### Operating system

macOS and Linux

### Browser information

Safari and Firefox 119.0.1

### Application version

Element 1.11.48

### Homeserver

Synapse 1.95.1+jammy1

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-11-29 08:20
@gabrc52  Unfortunately I cannot reproduce your issue. Please update your issue with more information. If we don’t hear back from you in a week, we will close the issue as we need to be able to reproduce it before we can fix it.

Is there anything you configured on the server side? Can you provide the browser logs when you are on the white screen?

**Comment by gabrc52** [comment] 2023-11-30 00:48
I've realized `disable_guests` also needs to be set to `true` for this bug to occur.

Could you try the following?

First, run Element under localhost, for example:

```
wget https://github.com/vector-im/element-web/releases/download/v1.11.50/element-v1.11.50.tar.gz
tar xf element-v1.11.50.tar.gz
cd element-v1.11.50/
mv config.sample.json config.json
python3 -m http.server
```

Then in `config.json`, set `setting_defaults` -> `UIFeature.registration` to `false` and `disable_guests` to `true`, i.e.

```
$ diff config.json config.sample.json 
12c12
<     "disable_guests": true,
---
>     "disable_guests": false,
38d37
< 	"UIFeature.registration": false,
```

Finally, open an incognito window and paste the following URL: http://localhost:8000/#/room/%21xxx%3Axxx.xxx?email=xxx%40example.com&signurl=https%3A%2F%2Fmatrix.org%2F_matrix%2Fidentity%2Fapi%2Fv1%2Fsign-ed25519%3Ftoken%xxx%26private_key%xxx&room_name=xxx&room_avatar_url=&inviter_name=xxx%20xxx&guest_access_token=&guest_user_id=&room_type=

Alternatively, visiting `http://localhost:8000/#/register` directly triggers the bug too.

Attempting to visit `http://localhost:8000/` results in the same white screen:

![image](https://github.com/vector-im/element-web/assets/24363938/f007f22c-f6a1-40dc-9113-60bf7d79d796)

**Closed** 2024-07-15 10:16 UTC
Labels: T-Defect, S-Major, A-Config, O-Uncommon
