### ISSUE TITLE
Incorrect number of notifications shown in room list

### ISSUE THREAD

**Issue by neilisfragile** [element-hq/element-web#25999] opened 2023-08-18 08:40 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I am looking at a given room, I have another notification in another room - the badge is read and tells me there are two messages.

3. What do you click?
I click on the room and then find only one message waiting for me. 

The room is a DM (no threads), the previous message is sent by me, the (single) message that is triggering a count of two is replying to my message. The new message also uses my name. So it is could the be the case that the reference to my name in the reply is being added to the overall count?

Notifying message is $7R8mb1vRmJwS5U2NCaXliE5jOzSnfhfeXjod6Z1cqp4 
Previous message it replies to is $Jf3hispBeZVEiPirDyvNjEI0nRxKfqYIWdLqXsUbtWc

#### What did you expect?
If the badge says 2 messages, I would expect to find two new messages
#### What happened instead?
Instead, there was only one message, so the correct behaviour would have been to show a highlighted notification with a count of 1. 

### Operating system

macOS

### Browser information

Version 115.0.5790.170 (Official Build) (x86_64)

### URL for webapp

develop

### Application version

Element version: 017fbb37936e-react-3828c9f66a41-js-97cf73bc5281 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment] 2023-08-22 07:54
Thank you for reporting the issue @neilisfragile . Unfortunately I cannot reproduce it. I tried every combination of replies and mentions in a DM. It may depend on the notification settings. Can you add information about your settings to the description?

**Comment by t3chguy** [comment] 2024-01-31 09:43
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.

**Closed by t3chguy** 2024-01-31 09:43 UTC
Labels: T-Defect, X-Needs-Info

**Comment by neilisfragile** [comment] 2024-02-02 14:34
I don't recall seeing this bug in the wild for a while.
