### ISSUE TITLE
Last admin warning dialog not showing when changing role in room settings 

### ISSUE THREAD

**Issue by MarcWadai** [element-hq/element-web#28547] opened 2024-11-26 10:48 UTC
#### What would you like to do?
We have a last admin dialog warning showing when changing the role on the right panel menu of the room. but we don"t have this behavior when changing on the setting screen of the room.

![image](https://github.com/user-attachments/assets/0f5637fe-8958-43d2-85d9-d95db8457182)

![image](https://github.com/user-attachments/assets/fccc2b9d-7a50-4e01-875c-1a284008ca36)

I would like to also add this warning when changing members roles on this screen.

#### Why would you like to do it?
Not having a warning confirmation modal here can lead to irreversible consequences for the user. Since we already have this behavior on one part of the application, it can be beneficial to apply it everywhere.

#### How would you like to achieve it?

Using the same code in `UserInfo.tsx,` we have the dialog `warnSelfDemote,` but managing to also do the check in `RolesRoomSettingsTab.tsx`  when `onUserPowerLevelChanged` is changing.

**Comment by t3chguy** [comment] 2024-11-26 10:52
Duplicate of https://github.com/element-hq/element-web/issues/26297

**Closed by t3chguy** 2024-11-26 10:52 UTC
Labels: S-Minor, A-Room-Settings, T-Enhancement, O-Occasional
