### ISSUE TITLE
Verification does not work

### ISSUE THREAD

**Issue by KsmoinO** [element-hq/element-web#27497] opened 2024-05-23 15:31 UTC
### Steps to reproduce

1. run `/verify <user-id> <device-id> <device-signing-key>`

#### What did you expect?
the device should be trusted

#### What happened instead?
popup appears with title "**Server error**" and content "End-to-end encryption disabled"

#### Verify also fails
1. On the room info tab, under People, select a user and click verify => Nothing append

#### Interactively verify by emoji also fails
1. On the room info tab, under People, select a user, click on session list, then click on a device ID
2. Click on "Interactively verify by emoji" => Nothing append

#### Manually verify by text also fails
1. On the room info tab, under People, select a user, click on session list, then click on a device ID
2. Click on "Manually verify by text"
3. Click on "Verify session" => Nothing append

The same operations on another computer (Same Debian and element-desktop version) succeed

### Operating system

Debian 12

### Application version

Element version: 1.11.67 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### How did you install the app?

deb https://packages.element.io/debian/ default main

### Homeserver

Synapse version 1.95.1

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-05-24 08:14
Duplicate of https://github.com/element-hq/element-web/issues/27201

**Closed by t3chguy** 2024-05-24 08:14 UTC
Labels: T-Defect, S-Major, A-E2EE
