### ISSUE TITLE
Cant Encrypt in Configured Room "Error sending event Error: Cannot encrypt event in unconfigured room"

### ISSUE THREAD

**Issue by FSG-Cat** [element-hq/element-web#27104] opened 2024-03-03 12:51 UTC
### Steps to reproduce

Change Encryption parameters like what this event shows.

```
{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2"
  },
  "origin_server_ts": ,
  "sender": "",
  "state_key": "",
  "type": "m.room.encryption",
  "unsigned": {
    "replaces_state": "",
    "prev_content": {
      "algorithm": "m.megolm.v1.aes-sha2",
      "rotation_period_ms": 604800000,
      "rotation_period_msgs": 100
    },
    "prev_sender": ""
  },
  "event_id": "",
  "room_id": ""
}
```

Element Desktop Stable and Nightly will both be unable to Send Encrypted messages on my 2 accounts atleast in this situation. 

Element iOS on my iPad is completely happy to send events into the room and others clients are willing to send messages. 

#### What did you expect?
That Sending E2EE messages works as the room is clearly configured even tho the E2EE params changed.
#### What happened instead?
IT doesnt work.

### Operating system

Windows 10 22H2

### Application version

Element version: 1.11.59 Crypto version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1 and Element Nightly version: 0.0.1-nightly.2024030301 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### How did you install the app?

https://element.io/download

### Homeserver

matrix.org and feline.support

### Will you send logs?

No

**Comment by BillCarsonFr** [comment] 2024-03-04 08:17
Is the event really malformed or is it a typo?

**Comment by FSG-Cat** [comment] 2024-03-04 16:32
In what sense is the event malformed? Also i did redact for privacy details like Room ID and sender of the event but i dont think those are relevant details?

**Comment by MidhunSureshR** [comment] 2024-03-07 06:29
Duplicate of https://github.com/element-hq/element-web/issues/

**Closed by MidhunSureshR** 2024-03-07 06:29 UTC
Labels: T-Defect, S-Major, A-E2EE, O-Occasional

**Comment by BillCarsonFr** [comment] 2024-03-07 08:51
> In what sense is the event malformed? Also i did redact for privacy details like Room ID and sender of the event but i dont think those are relevant details?

`"origin_server_ts": ,`

**Comment by FSG-Cat** [comment] 2024-03-07 20:14
@BillCarsonFr origin TS was probably deformed when i censored the event. Sorry for that. It looked correct in the raw event.
