### ISSUE TITLE
Ctrl+K and typing quickly results in network error

### ISSUE THREAD

**Issue by bnjbvr** [element-hq/element-web#28456] opened 2024-11-13 16:22 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Opened Element Web

3. What do you click?

I hit "Ctrl K", which opens the popup to quickly jump from one room to the other,

5. More steps…

Then I start typing some keys quickly.

#### What did you expect?

The room I was looking for shows up in the list, is preselected by default. Like it used to do; this is a regression.

#### What happened instead?

`Unable to load! Check your network connectivity and try again.`

![image](https://github.com/user-attachments/assets/e91f7bee-00ef-47a2-b7d0-04404a4aa224)

### Browser information

latest Firefox Dev Edition

### URL for webapp

develop.element.io

### Application version

Element version: 3132fe3233c1-js-f5f4091a0034 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-11-13 16:27
Duplicate of https://github.com/element-hq/element-web/issues/28404

**Closed by t3chguy** 2024-11-13 16:27 UTC
Labels: T-Defect, S-Minor, A-Shortcuts, O-Frequent

**Comment by bnjbvr** [comment] 2024-11-13 16:36
I swear there was a new instance of this bug and the fix only reached develop.element.io at most a couple of hours ago :sweat_smile:

**Comment by t3chguy** [comment] 2024-11-13 16:40
Yes, modals gained an error boundary so instead of force closing a generic error is shown, the failure is the same, an error being thrown
