### ISSUE TITLE
"Unable to restore session" on upgrade to element-web built on matrix-sdk-crypto-wasm 3.6.0

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26837] opened 2024-01-08 18:52 UTC
When @andybalaam upgraded to a version of element-web which included https://github.com/matrix-org/matrix-js-sdk/pull/3989, he got the following:

![image](https://github.com/element-hq/element-web/assets/1389908/43ec02bc-f905-43ff-beea-c21b426fec43)

We rolled back the update (https://github.com/matrix-org/matrix-js-sdk/pull/3991) which solved the problem.

The logs include lines like:

```
2024-01-08T15:59:21.981Z E Unable to load session Error: invalid type: boolean `false`, expected u8
```

Closer inspection reveals that his indexeddb includes rows in `inbound_group_sessions2` with `needs_backup: false`. This should never happen: `needs_backup` should be either `1` or absent.  (If it were false, then (a) it should be serialized as 0 (b) it should be omitted altogether anyway, due to [`serialize_bool_for_indexeddb`](https://github.com/matrix-org/matrix-rust-sdk/blob/cf57992/crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs#L1236) and [`skip_serializing_if = "std::ops::Not::not"`](https://github.com/matrix-org/matrix-rust-sdk/blob/cf57992/crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs#L1235C1-L1235C52) respectively).

So the question is: how did these rows end up like this, and does it affect anyone except @andybalaam?

**Comment by florianduros** [comment] 2024-01-09 09:23
I had the issue yesterday too. I can share a RS if needed.

**Comment by andybalaam** [comment] 2024-01-09 10:43
Yes please @florianduros , and could you also manually inspect your indexeddb? In the indexeddb table `inbound_group_sessions2` I see some entries that say `needs_backup:false`:

![image](https://github.com/element-hq/element-web/assets/76812/e8acb936-d28d-4af7-9c24-6e8f01756ba7)

which should never happen (it should always be either `needs_backup:1` or no `needs_backup` key at all)

**Comment by andybalaam** [comment] 2024-01-09 13:43
I'm getting a lot of

```
[PerSessionKeyBackupDownloader] Error while decrypting and importing key backup for session eccmiLkh0tFIGZcktq5paapCTlvSbm3D7OEBCDftGG0 TypeError: `target` argument of Reflect.get must be an object, got "2kZss1clJ1hfJprn/lL4J4UCxqv+heQih0O1ESOHwj0"
```

**Comment by andybalaam** [comment] 2024-01-09 13:46
From Florian's rageshake:

```
2024-01-08T17:52:08.801Z E Unable to load session DomException VersionError (0): The operation failed because the stored database is a higher version than the version requested.
./matrix-js-sdk/node_modules/@matrix-org/matrix-sdk-crypto-wasm/pkg/matrix_sdk_crypto_wasm.js/module.exports.__wbindgen_error_new@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js:7291:17
<T as futures_util::fns::FnOnce1<A>>::call_once::h08865017a8c6822a@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js line 8410 > WebAssembly.instantiate:wasm-function[5204]:0x336c71
matrix_sdk_crypto_wasm::future::future_to_promise_with_custom_error::{{closure}}::{{closure}}::h6470b98ef1be1fb0@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js line 8410 > WebAssembly.instantiate:wasm-function[1282]:0x210463
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2a3a1fb83cacd363@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js line 8410 > WebAssembly.instantiate:wasm-function[1241]:0x20740c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8cef6383e8d1f614@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js line 8410 > WebAssembly.instantiate:wasm-function[7701]:0x36c642
__wbg_adapter_63@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js:293:10
real@https://develop.element.io/bundles/537c779b539e5b6ce39f/6984.js:235:20
```

So my first guess is that Florian is not seeing the problem I saw. Instead, he successfully upgraded to version 8 of `inbound_groups_sessions2` and now the code is upset because the version is higher then expected after we reverted.

**Comment by andybalaam** [comment] 2024-01-09 13:47
@florianduros please can you confirm that you have an 8 here?:

![image](https://github.com/element-hq/element-web/assets/76812/22aadea3-f3e4-4cea-ab43-e9abf50ff2c9)

**Comment by andybalaam** [comment] 2024-01-09 13:49
If I'm right about what happened to @florianduros , it will be still broken for him. Meanwhile, it was unbroken for me by the revert we merged.

**Comment by florianduros** [comment] 2024-01-09 14:55
@andybalaam no, I have a 7.

<img width="1774" alt="Capture d’écran 2024-01-09 à 15 54 47" src="https://github.com/element-hq/element-web/assets/2621378/85da5724-7a98-49e1-9e43-e6ce95c79db4">

**Comment by andybalaam** [comment] 2024-01-09 15:04
And is it unbroken now @florianduros ? (Because we reverted the change, so it should not attempt an upgrade to v8)

**Comment by andybalaam** [comment] 2024-01-09 15:18
> @andybalaam When it happened, I clicked on `Clear storage and sign out` and signed in again. It fixed the issue to me to sign out and sign in

Ah, then I think my original theory is right: you upgraded to version 8, and that went wrong when we reverted the code making it expect version 7. When you cleared storage, the code recreated it at version 7.

**Comment by lieuwex** [comment] 2024-01-09 18:18
[rageshake (2).zip](https://github.com/element-hq/element-web/files/13877590/rageshake.2.zip)

I got the same issue, but weirdly enough not yesterday but today.

**Comment by andybalaam** [comment] 2024-01-10 11:44
From @lieuwex 's rageshake:

```
2024-01-09T18:03:13.714Z E Unable to load session DomException VersionError (0): The requested version (7) is less than the existing version (8).
Error: DomException VersionError (0): The requested version (7) is less than the existing version (8).
```

Again, this is caused by the revert, not the original problem.

**Closed** 2024-01-10 11:46 UTC
Labels: S-Critical, O-Uncommon, Z-Labs, A-Element-R
