### ISSUE TITLE
UTD

### ISSUE THREAD

**Issue by grati-cule** [element-hq/element-web#27898] opened 2024-08-05 09:04 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I viewed the Product Feedback Internal room and couldn't see Davide's message
2. What do you click?
Nothing
3. More steps…
None

#### What did you expect?
to be able to read messages (a critical requirement of the product imo)
#### What happened instead?
i couldn't read the message

### Operating system

Windows 11 Pro

### Application version

Element version: 1.11.72 Crypto version: Rust SDK 0.7.1 (431263d), Vodozemac 0.6.0

### How did you install the app?

goodness knows, i installed it nearly 3 years ago

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-08-05 09:08
Duplicate of https://github.com/element-hq/element-meta/issues/245

**Closed by t3chguy** 2024-08-05 09:08 UTC
Labels: T-Defect, S-Critical
