### ISSUE TITLE
Add the option to create unfederated spaces

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#28266] opened 2024-10-22 10:45 UTC
#### What would you like to do?

To be able to create unfederated spaces using Element

#### Why would you like to do it?

To make it easier to create a more secured section on my otherwise federated server

#### How would you like to achieve it?

Add an option in the space creation modal to make the space unfederated (`"m.federate": false`) similar to the room creation modal

![screenshot_2024-10-22T10-42-36Z](https://github.com/user-attachments/assets/d304d869-c94d-4cce-8699-ee2b91af7c62)

### Have you considered any alternatives?

You can manually call the client-server API, but this is not very convenient or user-friendly

```bash
curl --request POST \
  --url 'https://matrix.your-server.tld/_matrix/client/r0/createRoom' \
  --header 'Authorization: Bearer your_accessToken' \
  --header 'content-type: application/json' \
  --data '{
  "name": "Example unfederated, private space",
  "topic": "Optionally add a topic here",
  "preset": "private_chat",
  "visibility": "private",
  "power_level_content_override": {
    "events_default": 100,
    "invite": 50
  },
  "creation_content": {
    "type": "m.space",
    "m.federate": false
  },
  "initial_state": [
    {
      "type": "m.room.guest_access",
      "state_key": "",
      "content": {
        "guest_access": "can_join"
      }
    },
    {
      "type": "m.room.history_visibility",
      "content": {
        "history_visibility": "invited"
      }
    }
  ]
}'
```

### Additional context

Element does handle/support unfederated spaces other than creating them

![screenshot_2024-10-22T10-35-29Z](https://github.com/user-attachments/assets/82cadcc6-5784-4f0b-b5b0-87b1f3e5561f)

Optionally, child rooms created under unfederated spaces should default to also be unfederated.

**Comment by t3chguy** [comment] 2024-10-22 10:46
Duplicate of https://github.com/element-hq/element-meta/discussions/741

**Closed by t3chguy** 2024-10-22 10:46 UTC
Labels: T-Enhancement
