### ISSUE TITLE
Mentions and keywords not working

### ISSUE THREAD

**Issue by gaelledel** [element-hq/element-web#24022] opened 2022-12-15 12:09 UTC
### Steps to reproduce

Receiving a notification
Click on the room
Realise it was a mention type notif where it looked like a regular notif at room level (panel)

#### What did you expect? 
To receive a red badge notification

#### What happened instead? 
I received a regular notification 

These occurred several times today as 15.12.22

### Operating system

Mac OS

### Application version

Element Nightly version: 2022112805 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by gaelledel** [comment] 2022-12-15 13:20
<img width="414" alt="Screenshot 2022-12-15 at 14 20 22" src="https://user-images.githubusercontent.com/76945183/207869403-8bceaabe-aef3-4946-ba0f-8ed36f4bca7f.png">
It keeps saying no update is available.

**Comment by robintown** [comment] 2022-12-16 17:56
Blocked on https://github.com/vector-im/element-web/issues/24025 being fixed, after which we'll need to know again if mentions are fixed in the new version

**Comment by t3chguy** [comment] 2024-11-18 12:24
Closing due to lack of reproduction in over a year

**Closed by t3chguy** 2024-11-18 12:24 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Notifications, X-Needs-Investigation, O-Uncommon
