### ISSUE TITLE
Character escape issue when editing message with "<" character

### ISSUE THREAD

**Issue by agowa** [element-hq/element-web#26981] opened 2024-02-07 11:48 UTC
### Steps to reproduce

1. Write the below text as a message to someone or into some channel.
2. Post the message
3. Edit the message
4. Now the `<` was silently changed to `\<` however Element does not (yet) consider the message changed and nothing happens. BUT
5. When the user tries to change anything else in the message all line breaks appear to vanish (probably because of the silently inserted `\` triggering #25891)
6. When the user now edits the message again and thereby removes the `\` the line breaks are rendered correctly again.

```
line 1
line 2
some wile < appears
line 4
line 5
```

Screenshots:
![image](https://github.com/element-hq/element-web/assets/2544867/516c1780-0666-4bab-b9fc-8efd02d39fdc)
![image](https://github.com/element-hq/element-web/assets/2544867/707295e1-aeab-454f-a339-333107bd5393)
![image](https://github.com/element-hq/element-web/assets/2544867/ffc4a8fd-249a-47cb-a718-9df9762ae053)

When saving the message without removing the silently introduced `\`:
![image](https://github.com/element-hq/element-web/assets/2544867/873b1c7c-33f8-4f88-921e-f7afc84e0fc2)

When opening that message again for editing (the `\` is NOT getting doubled, so it is not a 1:1 replacement issue):
![image](https://github.com/element-hq/element-web/assets/2544867/7a44084f-edbe-4c46-8ca1-96ad1f0a1afa)

And when the `\` is manually removed each time when editing the message it appears correct again:
![image](https://github.com/element-hq/element-web/assets/2544867/c2fdd3b0-0b0b-4a15-b3d2-affd0092c787)

#### What did you expect?
Linebreaks should be preserved. Opening a message for editing it should not introduce any change to the message itself. Why exactly does Element insert the `\` into the edit box to begin with? If it is required underneath for HTML escaping then it should be stripped before showing the text in the edit box.

#### What happened instead?
Element is mangling the message and introducing silent changes into the "to be edited" message.

### Operating system

Arch Linux

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-02-12 10:52
Duplicate of https://github.com/element-hq/element-web/issues/22456

**Closed by t3chguy** 2024-02-12 10:52 UTC
Labels: T-Defect, S-Minor, A-Composer, O-Frequent
