### ISSUE TITLE
Can't decrypt message from a specific participant in a group chat

### ISSUE THREAD

**Issue by schiessle** [element-hq/element-web#27521] opened 2024-06-04 15:40 UTC
### Steps to reproduce

1. I'm a member of a group chat
2. I can read messages from all participants.
3. Only from one participant I always get "Unable to decrypt message"

#### What did you expect?

I can read all chat messages

#### What happened instead?

I can not read the messages from one participant reliable

### Operating system

Linux

### Application version

 1.11.67

### How did you install the app?

Flatpak

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-04 16:06
Duplicate of https://github.com/element-hq/element-meta/issues/245

**Closed by t3chguy** 2024-06-04 16:06 UTC
Labels: T-Defect, S-Major, A-E2EE
