### ISSUE TITLE
Signing into Element afresh, the roomlist loaded but clicking on a room in the list didn't replace the home screen with the timeline

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-web#21191] opened 2022-02-24 00:26 UTC
### Steps to reproduce

1. Sign in to Element
2. Click on a room
3. Don't get the timeline in the middle of the screen

#### What did you expect?
Timeline

#### What happened instead?
Just the "Welcome to Element Nightly" screen, stubbornly not moving.

### Operating system

macOS

### Application version

Element Nightly version: 2022022001 Olm version: 3.2.8

### How did you install the app?

Website

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by gsouquet** [comment] 2022-02-24 09:19
Does it eventually change screen? If so, this might be another flavour of https://github.com/vector-im/element-web/issues/21127

In any case, would you be able to rageshake? Looks like some JS error could be causing this

**Comment by lampholder** [comment] 2022-02-25 11:21
It never eventually changed screen, and I've since killed that session - I tried to rageshake but (another symptom I've experienced a few times recently) the rageshake spun and spun without ever termination, so presumably it failed?

**Comment by t3chguy** [comment] 2024-07-12 07:40
@lampholder are you still experiencing this?

**Comment by t3chguy** [comment] 2024-11-18 12:26
Closing due to lack of reproduction in over a year

**Closed by t3chguy** 2024-11-18 12:26 UTC
Labels: T-Defect, X-Needs-Info, X-Cannot-Reproduce, X-Regression, S-Major, A-Room-View, O-Uncommon
