### ISSUE TITLE
Every time to room-view will be create a Worker if had a voice message.

### ISSUE THREAD

**Issue by Benercoco** [element-hq/element-web#27295] opened 2024-04-08 09:59 UTC
### Steps to reproduce

1. send a voice message into room.
2. to other view and back to room view.
3. repeat step 2. We got may worker in memory
![image](https://github.com/element-hq/element-web/assets/68285771/3b4c5562-1be0-4f53-b002-922f469e4c3e)

#### What did you expect?
memory will not up
#### What happened instead?
out of memory

### Operating system

windows

### Browser information

Chrome 123.0.6312.106

### URL for webapp

app.element.io

### Application version

Element version: 1.11.63 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-04-08 10:52
Duplicate of https://github.com/element-hq/element-web/issues/26239

**Closed by t3chguy** 2024-04-08 10:52 UTC
Labels: T-Defect
