### ISSUE TITLE
User picture covers timestamp

### ISSUE THREAD

**Issue by bwdavis** [element-hq/element-web#27712] opened 2024-07-11 15:08 UTC
### Steps to reproduce

- Where are you starting? What can you see?
- Matrix client on right side of window, both vertical sidebars minimized, messages on right side.  The behavior is not affected by scaling or moving the window or by making the sidebars visible.  The problem is when you highlight, or hover over the top message from someone (where their picture appears to the left), the timestamp is partially obscured by the user's picture or the default picture icon.  See below:
- 
![peek07112024](https://github.com/element-hq/element-web/assets/13699204/7d07dff8-f933-4e9b-80e1-b47608302731)

#### What did you expect?
To see the time that a message was received
#### What happened instead?
The time is partially obscured

### Operating system

Windows 10 22H2 19045.4529 

### Application version

Element version: 1.11.70

### Homeserver

matrix-synapse-ldap3   0.2.2+git20221102+258473620416-2  LDAP auth provider for the Matrix homeserver
matrix-synapse-py3      1.109.0+lunar1  Open federated Instant Messaging and VoIP server
Ubuntu 24.04 noble Ubuntu 24.04 LTS

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-07-11 15:14
Duplicate of https://github.com/element-hq/element-web/issues/11051

**Comment by t3chguy** [comment] 2024-07-11 15:14
Duplicate of https://github.com/element-hq/element-web/issues/11051

**Closed by t3chguy** 2024-07-11 15:14 UTC
Labels: T-Defect, S-Tolerable, A-Appearance, O-Occasional
