### ISSUE TITLE
Unable to decrypt scenario in element web

### ISSUE THREAD

**Issue by derbertum** [element-hq/element-web#27232] opened 2024-03-23 19:05 UTC
### Steps to reproduce

While trying to automatically create large populated E2E encrypted rooms for testing we encountered following scenario:

1. A number of users is created and logged in with backup creation via passphrase
2. All those users (Bs) are logged out again
3. Another user (A) creates an e2e encrypted room and invites all Bs
4. The Bs log in one after another in a private browser session and accept the invitation afterwards the browser is closed but the user not logged out (a session should remain)
5. A sends a message in the room
6. The Bs open the browser again
7. The Message from A is encrypted

#### What did you expect?
The Bs can read the message from A because all of them had an open session (even without dehydrated session)

#### What happened instead?
The Message stays encrypted for the Bs

### Operating system

Does not matter

### Browser information

Does not matter

### URL for webapp

both app.element.io and develop.element.io

### Application version

Version von Element: 1.11.61 Krypto-Version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-03-25 07:42
Duplicate of https://github.com/element-hq/element-meta/issues/1893

**Comment by giomfo** [comment] 2024-03-25 07:53
@t3chguy this is not a duplicate issue.

The receiver accounts (Bs) are all logged in when the user A send the message (See the point 4: "The Bs log in one after another in a private browser session and accept the invitation afterwards the browser is closed but the user not logged out (a session should remain)).

**Comment by t3chguy** [comment] 2024-03-25 07:56
> private browser session

Just because the session remains on the server, doesn't mean it does on the client. Private browser sessions are amnesiac. I believe it to be a duplicate of the PFS issue but if you're not happy with that feel free to have it as a duplicate of https://github.com/element-hq/element-meta/issues/245

**Closed by t3chguy** 2024-03-25 07:56 UTC
Labels: T-Defect
