### ISSUE TITLE
Corrupt data trying to restore session

### ISSUE THREAD

**Issue by kenrachynski** [element-hq/element-web#28638] opened 2024-12-04 20:00 UTC
### Steps to reproduce

1. Wake MacBook Pro from nap
2. Close Element tab because it has gone completely weird
3. Open new tab and connect to app.element.io

#### What did you expect?
Eventually, the app would load and I'd be able to chat. slowly.
#### What happened instead?
Could not restore previous session. Log out and clear cache; this will erase all your encryption keys and you won't be able to read encrypted messages.

### Operating system

macOS 15.1.1

### Browser information

Safari 18.1.1

### URL for webapp

app.element.io

### Application version

As far as I know it is current.

### Homeserver

troublemaker.dev (conduwuit 0.5.0)

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2024-12-04 20:45
Logs contain:

```
2024-12-04T19:41:51.631Z D Downloading Rust crypto library
2024-12-04T19:53:18.021Z E Unable to load session Loading chunk 7490 failed.
(timeout: https://app.element.io/bundles/21aae0d466bc7a53aaa1/7490.js)
```

Duplicate of https://github.com/element-hq/element-web/issues/27361

**Closed by richvdh** 2024-12-04 20:45 UTC
Labels: T-Defect, S-Critical, A-Storage, A-Session-Mgmt, O-Uncommon
