### ISSUE TITLE
Element Call Room widget not sticky

### ISSUE THREAD

**Issue by onestacked** [element-hq/element-web#27371] opened 2024-04-21 14:35 UTC
### Steps to reproduce

1. Join the call of an Element Call Video Room
2. Switch to a different chat

#### What did you expect?
The call gets put into a smaller floating widget (like the Jitsi/old Call Rooms)

#### What happened instead?
The Call disappears (still in the active user count, but can't hear anyone in the call) 
and when swapping back to the Call Room I am back at the Join Call screeen.

### Operating system

Observed on Windows and Linux

### Browser information

Firefox and in Element Desktop

### URL for webapp

Private Server (using https://github.com/spantaleev/matrix-docker-ansible-deploy/)

(also observed on matrix.org with app.element.io)

### Application version

Element version: 1.11.64 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1
Also seen on a few older versions (not sure when exactly this changed)

### Homeserver
Synapse 1.105.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-04-22 09:43
Duplicate of https://github.com/element-hq/element-web/issues/27114

**Closed by t3chguy** 2024-04-22 09:43 UTC
Labels: T-Defect, X-Needs-Info

**Comment by onestacked** [comment] 2024-04-22 10:58
> This sounds like an issue with the Element Call you are embedding, it is up to the Widget to request the always on screen permission via the postMessage API. Are you running the Element Call related labs flags?

I've got the Video Rooms Beta enabled and Element Call video rooms. New group Call experience doesn't change the behaviour.

> > Will you send logs?
> > Yes
> 
> Not seeing any logs from you.

I've now sent some logs from Firefox Linux on app.element.io with matrix.org account.

**Comment by onestacked** [comment] 2024-04-22 11:02
> Duplicate of #27114
Might be different, at least in [this comment](https://github.com/element-hq/element-web/issues/27114#issuecomment-1993951293) they mentioned that this also happens for 1:1 calls, but I've never seen that.

#27114 also seems like it is inconsistent, but for me this happens every time I swap to a different room.
