### ISSUE TITLE
Incorrect notification count

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#27882] opened 2024-07-31 14:31 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

I'm in Element Desktop
 
3. What do you click?

Nothing

4. More steps…

The Home icon has "Show all rooms" selected and has a [10] badge.
The room list (when Home is selected) is collapsed and has a total of [9] unread messages.
There are no unreads in my TAC

<img width="412" alt="Screenshot 2024-07-31 at 15 30 46" src="https://github.com/user-attachments/assets/6e2cc997-29af-408e-9bb9-e1cdeb8c2c76">

I've tried using Notification debug in devtools but it doesn't really share much... 

#### What did you expect?
home to show [9] and match the room list

### Operating system

MacOS

### Application version

Element Nightly version: 2024073001 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

Nightly

### Homeserver

EMS ONE

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-07-31 14:33
Duplicate of https://github.com/element-hq/element-web/issues/20372

**Closed by t3chguy** 2024-07-31 14:33 UTC
Labels: T-Defect
