### ISSUE TITLE
Option to disables spaces

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#22765] opened 2022-07-07 09:42 UTC
#### What would you like to do?

As a user I want to have an option to disable spaces,
because this feature is too complicated / I don't want to use it.

#### Why would you like to do it?

It makes the app easier by removing one complexity level.
Removing the spaces bar saves space.

#### How would you like to achieve it?

- Provide an option to disable spaces
- With this option active the „“ option should be activated in the background as well

#### Open questions

- Are there any issues if people already joined a space?
- It is possible to define room permissions based on spaces
  - Should we handle that?
- People are loosing parts of the room discovery by spaces.
  - Should we handle that?

### Additional context

- A mock-up for parts of it exist here https://www.figma.com/file/QTxqmDYaQiSU4I2KYHz35T/Untitled?node-id=3%3A3024
- This seems to become a common PS request as well as many users are asking for it #18898

**Comment by t3chguy** [comment] 2022-07-07 09:46
Duplicate of https://github.com/vector-im/element-web/issues/18898

Even though the title is phrased as disabling spaces bar, the actual product ask there is broader

**Closed as completed by t3chguy** 2022-07-07 09:46 UTC
Labels: P3, T-Enhancement

**Comment by weeman1337** [comment] 2022-07-10 10:05
See these comments:
- https://github.com/vector-im/element-web/issues/18898#issuecomment-1179328959
- https://github.com/vector-im/element-web/issues/18898#issuecomment-1179613302
