### ISSUE TITLE
Selected radio button in settings barely visible

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27177] opened 2024-03-13 22:03 UTC
### Steps to reproduce

1. Go to settings
2. Observe radio button

#### What did you expect?
Selected radio button to be filled to signal selection

#### What happened instead?
Selected radio button has somewhat lighter border but dark inside like all other buttons

![image](https://github.com/element-hq/element-web/assets/640121/ce8428d4-93ff-4bf6-a2bb-4787aeb1dffb)

### Operating system

Windows 11

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-03-13 22:08
Duplicate of https://github.com/element-hq/element-web/issues/27166

**Closed by t3chguy** 2024-03-13 22:08 UTC
Labels: T-Defect
