### ISSUE TITLE
Encrypted events seem to get into `handleCallEvent()`

### ISSUE THREAD

**Issue by SimonBrandner** [element-hq/element-web#18540] opened 2021-08-13 19:40 UTC
![Screenshot_20210813_213936](https://user-images.githubusercontent.com/25768714/129410470-9fce5865-c9f7-4acb-ac8f-aed80c6a8a20.png)

**Comment by Palid** [comment] 2021-08-14 09:26
Related: https://github.com/matrix-org/matrix-js-sdk/pull/1834
Looks like this PR has shown us additional problems we didn't know about before.

**Comment by SimonBrandner** [comment] 2021-08-16 10:21
It's quite unclear to me how can this happen since we have this line: https://github.com/matrix-org/matrix-js-sdk/blob/977720cee47e49371db46dca291868b78b2c29ca/src/webrtc/callEventHandler.ts#L61

**Comment by dbkr** [comment] 2021-08-16 17:40
Interesting. How do we know this is an encrypted event? Does this visibly cause any badness? How did you repro this?

**Comment by SimonBrandner** [comment] 2021-08-16 17:45
> Interesting. How do we know this is an encrypted event? 

The log says, so - `event.getType() === "m.room.encrypted"`

> Does this visibly cause any badness? 

No, it just unnecessarily goes through `handleCallEvent` wasting some tiny amount of time

> How did you repro this?

Open an E2EE and receive a message

**Comment by SimonBrandner** [comment] 2021-08-16 18:47
I think I've run out of ideas here, if someone wants to take a look please go ahead

**Comment by dkasak** [comment] 2021-08-18 14:14
I just stumbled across this while debugging something else. These are `m.bad.encrypted` messages that we're injecting when we can't decrypt a message:

```
content: Object {
    msgtype: "m.bad.encrypted",
    body: "** Unable to decrypt: The sender's device has not sent us the keys for this message. **"
}
```

I think the reason we're reporting `m.room.encrypted` instead of `m.room.message` (with `msgtype: m.bad.encrypted`) is that we're recording the type [at the beginning](https://github.com/matrix-org/matrix-js-sdk/blob/c2a0c02898f6bd1d4e508559b67880494005e1de/src/webrtc/callEventHandler.ts#L133) of the `handleCallEvent` function and it gets decrypted between that location and the logger call.

> It's quite unclear to me how can this happen since we have this line: https://github.com/matrix-org/matrix-js-sdk/blob/977720cee47e49371db46dca291868b78b2c29ca/src/webrtc/callEventHandler.ts#L61

That's not the only place from which can reach `handleCallEvent`, since it's also called directly [here](https://github.com/matrix-org/matrix-js-sdk/blob/c2a0c02898f6bd1d4e508559b67880494005e1de/src/webrtc/callEventHandler.ts#L113) so maybe that has something to do with it?

> No, it just unnecessarily goes through handleCallEvent wasting some tiny amount of time

I think log pollution is also quite counterproductive when it comes to debugging, especially when we're producing spurious warnings/errors.

To reproduce, just join an encrypted room with some existing history for which you won't receive keys (e.g. the [Megolm test room](https://matrix.to/#/#megolm:matrix.org)) and watch the console.

**Comment by SimonBrandner** [comment] 2021-08-18 14:21
> I think the reason we're reporting `m.room.encrypted` instead of `m.room.message` (with `msgtype: m.bad.encrypted`) is that we're recording the type [at the beginning](https://github.com/matrix-org/matrix-js-sdk/blob/c2a0c02898f6bd1d4e508559b67880494005e1de/src/webrtc/callEventHandler.ts#L133) of the `handleCallEvent` function and it gets decrypted between that location and the logger call.

It's quite unclear to me how can this happen since we have this line: matrix-org/matrix-js-sdk@977720c/src/webrtc/callEventHandler.ts#L61

**Comment by dkasak** [comment] 2021-08-18 14:55
@SimonBrandner Did you perhaps miss this later part of my comment?

> That's not the only place from which can reach handleCallEvent, since it's also called directly [here](https://github.com/matrix-org/matrix-js-sdk/blob/c2a0c02898f6bd1d4e508559b67880494005e1de/src/webrtc/callEventHandler.ts#L113) so maybe that has something to do with it?

Maybe the link in that was not obvious; I was linking to this direct `handleCallEvent` which doesn't go through `evaluateEventBuffer` (which contains the line you're quoting): https://github.com/matrix-org/matrix-js-sdk/blob/c2a0c02898f6bd1d4e508559b67880494005e1de/src/webrtc/callEventHandler.ts#L113

**Comment by t3chguy** [comment] 2024-11-25 16:06
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2553 which filters the buffer to only include `m.call.*` | `org.matrix.call.*` events

**Closed by t3chguy** 2024-11-25 16:06 UTC
Labels: T-Defect, S-Tolerable, A-E2EE, A-VoIP, X-Needs-Investigation, O-Frequent
