### ISSUE TITLE
Please make message entry box resizeable, improving usability

### ISSUE THREAD

**Issue by Moini** [element-hq/element-web#28037] opened 2024-09-11 21:09 UTC
### Steps to reproduce

1. Use the message box to type a multi-line message or to paste a multi-line message
2. Try to edit what I just typed

#### What did you expect?

I would like to be able to see the complete message that I am writing, so I can have everything I wrote in context, and not only mini pieces of the whole thing. This is especially important for code bits, or longer, multi-line messages.

I would expect the message box to increase in size if I type multiple lines, so that I can easily see what I wrote. Of course, this needs a max height, too. Or at least, I would like to be able to resize the message box myself.

Usage example: sharing social media post contents with team members who are supposed to post it on our organization's social media channels, sharing bits of code. I'm not only using Matrix to chat, but also to achieve my volunteer work.

#### What happened instead?

* I cannot read what I wrote in context.
* Especially for code, this is pretty unhelpful
* Additionally, using arrow keys to navigate through the lines, to read back and edit, often jumps to previous messages, which I am definitely not working on - but as I cannot see the whole message, it is sometimes difficult to know whether I'm actually already in the first line.
* It's really difficult to edit and have a good overview.

### Operating system

Linux Mint

### Application version

1.11.77  

### How did you install the app?

https://packages.element.io/debian default/main amd64

### Homeserver

tchncs.de

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-09-12 09:07
Duplicate of https://github.com/element-hq/element-web/issues/5882

**Closed by t3chguy** 2024-09-12 09:07 UTC
Labels: T-Defect, S-Minor, T-Enhancement, A-Composer, O-Occasional
