### ISSUE TITLE
Crash on click.

### ISSUE THREAD

**Issue by grinapo** [element-hq/element-web#27138] opened 2024-03-07 22:12 UTC
### Steps to reproduce

1. Just clicked into the window.

#### What happened instead?

Crash.

### Operating system

Linux Debian/sid, xwindow, xfce4

### Browser information

firefox nightly

### URL for webapp

https://riot.grin.hu/#/room/#osm:grin.hu

### Homeserver

synapse 

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-03-07 22:22
Duplicate of https://github.com/element-hq/element-web/issues/25435

**Closed by t3chguy** 2024-03-07 22:22 UTC
Labels: T-Defect
