### ISSUE TITLE
Error: Unable to restore session

### ISSUE THREAD

**Issue by davidak** [element-hq/element-web#25147] opened 2023-04-18 15:32 UTC
### Steps to reproduce

1. Open https://app.element.io/
2. See error

I did not use this device for like a year.

#### What did you expect?

Be still logged in.

#### What happened instead?

I get this error:

![Screenshot from 2023-04-18 17-27-28](https://user-images.githubusercontent.com/91113/232826357-b3b8d453-3687-4b40-bf27-41deac5ef168.png)

> **Unable to restore session**
> We encountered an error trying to restore your previous session.
> 
> If you have previously used a more recent version of Element, your session may be incompatible with this version. Close this window and return to the more recent version.
> 
> Clearing your browser's storage may fix the problem, but will sign you out and cause any encrypted chat history to become unreadable.

### Operating system

NixOS 22.11.3689.fda0d99c2cb

### Browser information

Chromium 112.0.5615.49

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.29
Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

I already clicked on "Clear Storage and Sign Out" to get the application version and can't send logs anymore.

**Comment by bjherbison** [comment] 2024-02-13 21:45
I just got this error. I updated to a newer Element on one computer then used Element on another computer (which had been off for about a week). Sending error logs.

Using https://chat.mozilla.org/ under Firefox 124.0a1 on a Ubuntu system using XFCE.

**Comment by richvdh** [comment] 2024-02-16 10:54
Duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed by richvdh** 2024-02-16 10:54 UTC
Labels: T-Defect, S-Major, A-E2EE, A-Login, O-Uncommon
