### ISSUE TITLE
EW swallows unsent DMs

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27975] opened 2024-08-29 10:35 UTC
STR:

* Start a DM with a new user. Observe "send your first message to start a chat", or words to that effect
* Write out a long message
* Realise that you need refer to something in another room, and switch room
* Attempt to switch back to DM
* Realise that EW has thrown away your nearly-complete message
* Throw your monitor out of a window

**Comment by richvdh** [comment] 2024-08-29 10:36
Slightly provocatively labelling this as S-Critical because it caused data loss...

**Comment by t3chguy** [comment] 2024-08-29 10:39
Duplicate of https://github.com/element-hq/element-web/issues/23196

**Closed by t3chguy** 2024-08-29 10:39 UTC
Labels: T-Defect, S-Critical, S-Major, O-Uncommon, O-Frequent, A-DM-Start
