### ISSUE TITLE
Crosssigning a Web or Desktop Session from another Websession: No Keybackup

### ISSUE THREAD

**Issue by derbertum** [element-hq/element-web#27327] opened 2024-04-12 07:37 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
 I have an Element Web Session on Firefox (Version von Element: 1.11.64 Krypto-Version: Olm 3.2.15). OS: MacOS Sonoma. I want to Login a new Session on either Element Desktop or Web Safari
2. What do you click?
I Login with username and Passwort and click crosssigning on the new session. The Crosssigning via emojis appear on both devices and the crosssigning appears to be successful.
Afterwards my new session is verified but my key backup is not available. Under Settings -> Security there is a button "Connect your session with a key backup". Old messages cannot be decrypted

#### What did you expect?
After crosssigning my new session, my key backup and old messages are available
#### What happened instead?
No key backup, no messages

### Operating system

macOS Sonoma

### Application version

Version von Element: 1.11.64 Krypto-Version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### How did you install the app?

element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by subscribernamegoeshere** [comment] 2024-04-16 19:59
okay sorry dont to be a pest but I think this is a sudden change? on the matrix.org backend or something other happened as the original element.io webpage session has exactly the same problem. it says "connect this session to key backup" button, when clicking it it reports that 80something keys have been successfully restored and I click that final popup with okay. and after this it is again telling me that I dont have backups and this session is not backing up at all and I can start all over trying to connect to key backup. going nowhere. is the element.io page (implementation) the stuff to report here?

**Comment by aabittner** [comment] 2024-04-19 10:41
new around here but having apparently the very same problem. having multiple sessions, one in Firefox 115.9.1 (original via: element.io web client) and one in separate clean Debian 12.5 (x64)  via your original command line instructions from https://element.io/download  (Linux instructions there) on this Debian 12.5 (x64). on both, the web version of element (Firefox) and the element-desktop (Debian) are not able to take part in the key backup:

always trying via: all settings, security and privacy, chapter: Encryption, sub chapter: secure backup, button: connect this seccion to Key Backup. triggers an action which results in a pop-up telling: keys restored, successfully restored n number (of) keys, dismissing this pop-up with okay, re-visiting the all-settings, security and privacy, ... leading to the same non-backed up state and telling me that this session is not backing up your keys, and the button connect this session to Key Backup.

This happens on both the Firefox element-web (element.io) in there and the Debian element-desktop application.
I dont know when this started, but I know that Key Backup was working normally in the past before.
Thank you for fixing this matter.

**Comment by kegsay** [comment] 2024-05-15 09:28
Duplicate of https://github.com/element-hq/element-web/issues/27330 by the sounds of it?

**Comment by t3chguy** [comment] 2024-05-15 09:44
Duplicate of https://github.com/element-hq/element-web/issues/27330

**Closed by t3chguy** 2024-05-15 09:44 UTC
Labels: T-Defect, S-Major, A-E2EE, A-E2EE-Key-Backup, O-Uncommon, Team: Crypto
