### ISSUE TITLE
Can not join space using "share this space" invite link

### ISSUE THREAD

**Issue by MarkWieczorek** [element-hq/element-web#26985] opened 2024-02-07 22:25 UTC
### Steps to reproduce

1. I created a private test space with a single encrypted room.
2. . In the space, I clicked on invite, and then clicked on the link "share this space"
![Screenshot from 2024-02-07 23-12-12](https://github.com/element-hq/element-web/assets/8697285/851484b4-ad4b-4b7d-921c-e0adf85d7615)
3. This opens a web page 
![Screenshot from 2024-02-07 23-37-15](https://github.com/element-hq/element-web/assets/8697285/9af85d0e-8bc2-4a12-a3be-0e59e69b396a)
4. I copy the link "https://matrix.to/#/!lytgBmotywlZghXvDG:matrix.org?via=matrix.org" and open it in another browser where I am logged into Element with a different account. After clicking "join the conversation", I get the following error
![Screenshot from 2024-02-07 23-38-50](https://github.com/element-hq/element-web/assets/8697285/3ebe18cf-bec4-48d9-908c-354bc7e4aa31)

#### What did you expect?
I expected that I would be able to join the space using the link provided by "share this space"
#### What happened instead?
I got an error message.

### Operating system

Linux

### Browser information

unGoogled chromium, firefox

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-02-12 08:18
Duplicate of https://github.com/element-hq/element-meta/issues/1995 / https://github.com/element-hq/element-meta/issues/514 / https://github.com/element-hq/element-meta/issues/1149

**Closed by t3chguy** 2024-02-12 08:18 UTC
Labels: T-Defect, S-Major, A-Spaces, O-Occasional

**Comment by MarkWieczorek** [comment] 2024-02-12 10:20
@t3chguy If this is "not planned", could you close the other issues that you reference above as well?

**Comment by t3chguy** [comment] 2024-02-12 10:23
![image](https://github.com/element-hq/element-web/assets/2403652/6bd649ae-24fa-4031-a3a9-e32388b23094)

Not planned in Github means duplicate too.
