### ISSUE TITLE
Notification counters are not aligned

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27967] opened 2024-08-27 15:04 UTC
### Steps to reproduce

1. Observe the notification counter in the panel on the left - it doesn't reflect the sum of notifications in the room list on the right

![image](https://github.com/user-attachments/assets/7c2f57f3-540a-434a-a905-83d5f5eedf7a)

2. Observe a new message coming in. The counter on the left goes up 2, not 1

![image](https://github.com/user-attachments/assets/f8bff453-c254-47d0-82cc-5fa2231b4894)

3. Read the new message. The counter on the left goes down 1

![image](https://github.com/user-attachments/assets/783f77ae-a2a5-47eb-a42c-b299b97c9a4e)

#### What did you expect?
Counter on the left to be consistent with the sum of counters on the right

#### What happened instead?
Counter on the left feels arbitrary

Discussed here: https://matrix.to/#/!bYSNiRQzSqoaVuYiFK:matrix.org/$veoDwR2f3jTMFL13le_C6Wtt0CxxV_PsaY5-pABzBi8?via=element.io&via=matrix.org&via=one.ems.host

### Operating system

Windows 11

### Application version

Element version: 1.11.75 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

element.io

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment] 2024-08-28 08:37
@florianduros , you're maintainer this week? Would you take a look 🙏

**Comment by t3chguy** [comment] 2024-08-28 09:38
Duplicate of https://github.com/element-hq/element-web/issues/20372

**Closed by t3chguy** 2024-08-28 09:38 UTC
Labels: T-Defect, S-Minor, A-Notifications, O-Frequent
