### ISSUE TITLE
dead ends galore

### ISSUE THREAD

**Issue by matthiasclasen** [element-hq/element-web#27066] opened 2024-02-24 19:57 UTC
### Steps to reproduce

I start the app as usual, and out of the blue, it thows up a dialog that tells me it can't load my data. Even though I see the data in the main window behind the dialog. The dialog has two options "clear storage and sign out" and "send logs". There's  no way out, you force me to submit this issue.

### Will you send logs?

Yes

**Comment by florianduros** [comment] 2024-02-26 10:35
Duplicate of https://github.com/element-hq/element-web/issues/26967

**Closed by florianduros** 2024-02-26 10:35 UTC
Labels: T-Defect
