### ISSUE TITLE
UTD: incorrect "DecryptionError: This message was sent before this device logged in."

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27589] opened 2024-06-17 19:52 UTC
### Steps to reproduce

1. I DMed a user from latest ED (2024061701)
2. They couldn't decrypt the msgs sent before they joined with "DecryptionError: This message was sent before this device logged in."

However, their session is a long-lived FF session which should be fine.

Am worried that the new pre-join anti-UTD logic might be broken (or perhaps this is a legit UTD?)

#### What did you expect?

Users should be able to decrypt msgs sent in a DM before they join it.

### Application version

2024061701

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2024-06-17 20:59
Not yet sure what caused the original decryption failure, but have filed https://github.com/element-hq/element-web/issues/27590 to track the incorrect error message.

**Comment by richvdh** [comment] 2024-06-18 10:25
Ok, we suspect the original decryption failure was due to https://github.com/element-hq/element-meta/issues/2356.

Closing this issue as a duplicate of the two issues above.

**Closed by richvdh** 2024-06-18 10:25 UTC
Labels: T-Defect, S-Minor, Z-UISI
