### ISSUE TITLE
Can't load threaded message in Element Desktop

### ISSUE THREAD

**Issue by 7h3kk1d** [element-hq/element-web#22266] opened 2022-05-18 14:59 UTC
### Steps to reproduce

1. I created a threaded message in Element Android
2. Then opened the thread in Element Desktop
3. I had also edited the original message the thread was spawned from in element desktop

#### What did you expect?
I expected to see the message that I added to the thread
#### What happened instead?
I see a message: `Can't load this message (m.room.message)Submit logs`

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### How did you install the app?

apt using https://packages.element.io/debian/

### Homeserver

dagarten.modular.im (EMS Hosted)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-05-18 15:02
Duplicate of https://github.com/vector-im/element-web/issues/22141

**Closed as completed by t3chguy** 2022-05-18 15:02 UTC
Labels: T-Defect
