### ISSUE TITLE
Unable to get past the loading screen when opening a message link

### ISSUE THREAD

**Issue by rufuskahler** [element-hq/element-web#25744] opened 2023-07-10 07:38 UTC
### Steps to reproduce

Unable to get past the loading screen when opening the link below: https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$XcIEoi4a6DCyJE7iIN6Bs8-khzc8D1kpPjXVq-JC35c?via=matrix.org&via=element.io&via=envs.net

### Operating system

macOS

### Application version

Nightly Version 2023070601 (2023070601)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-07-10 08:26
![image](https://github.com/vector-im/element-web/assets/2403652/7d2420f3-2162-4040-9cb9-99a3dbc75311)

Worked fine for me, spinner while server was attempting to peek room then gave up and asked me to log in. No errors in your logs.

**Comment by t3chguy** [comment] 2024-11-18 12:24
Closing due to lack of reproduction in over a year

**Closed by t3chguy** 2024-11-18 12:24 UTC
Labels: T-Defect, X-Cannot-Reproduce
