### ISSUE TITLE
UTD

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27885] opened 2024-08-01 08:37 UTC
### Steps to reproduce

1. Read a message

#### What did you expect?
to be able to read the message

#### What happened instead?
unable to decrypt

### Operating system

Windows 11

### How did you install the app?

element.io

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-08-01 08:38
Duplicate of https://github.com/element-hq/element-meta/issues/245

**Closed by t3chguy** 2024-08-01 08:38 UTC
Labels: T-Defect
