### ISSUE TITLE
No way to start a video call going if you're currently the only person in a room.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#28380] opened 2024-11-05 09:44 UTC
### Steps to reproduce

1. Want to start a video call
2. Create a room and invite some users to it, much as you would with the EC SPA
3. Hit the video call button - discover that you can't start it because it refuses to let you start a call with noone present:
![Screenshot 2024-11-05 at 09 42 32](https://github.com/user-attachments/assets/782714bd-f2fc-48c4-a610-f2fffff09ad0)

#### What did you expect?

You should be able to set a video call going at any time, whether or not people have yet joined the conversation to participate in it.

### Application version

Element version: 1.11.83 Crypto version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-11-05 09:47
Duplicate of https://github.com/element-hq/element-web/issues/28298

**Closed by t3chguy** 2024-11-05 09:47 UTC
Labels: T-Defect, S-Tolerable, A-VoIP
