### ISSUE TITLE
Two new stuck notifications since upgrading to Element Element version: 1.11.62 Crypto version: Olm 3.2.15

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-web#27247] opened 2024-03-27 11:26 UTC
### Steps to reproduce

One is stuck on a WA bridged room (no threads)
One is stuck on a DM with Erik (again, no threads)

I'll file this issue to attach a rageshake, then try more efforts to dislodge the notifications.

### Operating system

macOS 14.4 (23E214)

### Application version

Element version: 1.11.62 Crypto version: Olm 3.2.15

### Homeserver

lant.uk 1.101.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-03-27 11:36
Duplicate of https://github.com/vector-im/element-web/issues/24392

**Closed by t3chguy** 2024-03-27 11:36 UTC
Labels: T-Defect
