### ISSUE TITLE
Thread timeline completely misordered (and no workarounds to make it work)

### ISSUE THREAD

**Issue by estux** [element-hq/element-web#27302] opened 2024-04-09 00:01 UTC
### Steps to reproduce

1. Element Web open in a browser tab (Firefox 124.0.2)
2. Open a room
3. Open the newest thread
4. Messages in the thread timeline are misordered.

#### What did you expect?
Thread messages ordered by time.
#### What happened instead?
Thread messages misordered like:
- yesterday (sunday)
- friday of last week
- wednesday of last week
- yesterday (sunday)
- today (monday)
- yesterday (sunday)

This is different by other reported issues as there seems to be no workarounds to make it work again (switching threads doesn't work). 
I think the problem arose after I started writing messages in the thread also from mobile Android apps (Element Android and Element X Android).
Paradoxically I can see the messages with the right order on Android mobile apps.

### Operating system

Windows 10

### Browser information

Firefox 124.0.2 (64 bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.63 Olm version: 3.2.15

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-04-09 07:29
Duplicate of https://github.com/element-hq/element-web/issues/26555

**Closed by t3chguy** 2024-04-09 07:29 UTC
Labels: T-Defect

**Comment by estux** [comment] 2024-04-09 10:35
Hello, I read of course #26555 but it seemed to me like a different bug as it's not possible to have a workaround like the one explained by Matthew to view again a normal timeline.
