### ISSUE TITLE
Multiple copies of the same thread in Threads panel

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27499] opened 2024-05-24 09:45 UTC
### Steps to reproduce

shrug

#### What did you expect?

One copy of each thread in a room

#### What happened instead?

![image](https://github.com/element-hq/element-web/assets/1389908/cdd6f8a1-1382-4666-9063-4c4472607a2c)

Also what's with those threads with 0 messages? I'm pretty sure there *should* be messages in those threads

### Operating system

Ubuntu 22.04

### Application version

Element Nightly 1234 version: 2024051502 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### How did you install the app?

nightly debian

### Homeserver

Synapse v1.107.0ish

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-05-24 10:14
Duplicate of https://github.com/element-hq/element-web/issues/24637

**Closed by t3chguy** 2024-05-24 10:14 UTC
Labels: T-Defect, S-Minor, A-Threads
