### ISSUE TITLE
Option to always open room at the last unread message

### ISSUE THREAD

**Issue by code-IM-perfect** [element-hq/element-web#27954] opened 2024-08-22 19:39 UTC
#### What would you like to do?
I would like to have an option to always open rooms at the last unread message of that room.

#### Why would you like to do it?
Cuz I really hate to scroll all the way up to catch up to conversations and I have to remember what my last read message was in order to not miss conversations.

#### How would you like to achieve it?
By adding a global and local option to enable or disable this behaviour

### Have you considered any alternatives?

I mean scrolling up but that's like super inconvenient

### Additional context

It feels like a feature that should exists but I have searched both the web and the settings and have not been able to find any such setting.

**Comment by t3chguy** [comment] 2024-08-28 10:17
Duplicate of https://github.com/element-hq/element-meta/issues/1548

**Closed by t3chguy** 2024-08-28 10:17 UTC
Labels: A-Timeline, X-Needs-Product, T-Enhancement, O-Frequent, T-Feature
