### ISSUE TITLE
Search window closes automatically

### ISSUE THREAD

**Issue by drufus1337** [element-hq/element-web#28589] opened 2024-11-28 12:34 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Start in Main Window (All Rooms View)

2. What do you click?
Click on "Search" or hit "Ctrl+k"
Type a username - really fast (sounds stupid but makes a difference)

#### What did you expect?
The searchwindow stays visible until i select a search result (e.g. a username)

#### What happened instead?
If you type fast enough (e.g. "daniela") the search window closes itself after the "da" and the rest of it "nie..." is being typed in the last active chat window

If you type slow, search works fine

### Operating system

Windows 11 PRO

### Application version

1.11.86

### How did you install the app?

Internal Source provided by IT

### Homeserver

unknown

### Will you send logs?

unfortunately, no

**Comment by Shirkanesi** [comment] 2024-11-28 12:54
Same problem here. Also 1.11.86 but on debian bookworm.

**Comment by itsbirdo** [comment] 2024-11-29 12:38
I also have this problem!

**Comment by t3chguy** [comment] 2024-12-02 09:04
Duplicate of https://github.com/element-hq/element-web/issues/28493

**Closed by t3chguy** 2024-12-02 09:04 UTC
Labels: T-Defect, S-Minor, O-Frequent, A-Spotlight-Search
