### ISSUE TITLE
Expanding sub-spaces panel on left-hand of element crashed element

### ISSUE THREAD

**Issue by Aranjedeath** [element-hq/element-web#27531] opened 2024-06-06 14:47 UTC
### Steps to reproduce

I was looking at a room in Element Desktop. The left hand vertical panel of space icons was in compact or shrunk mode, and I clicked one of the little arrows ( > ) next to a space that has child-spaces to expand the panel and select a child space. 

Element indicated to report a bug, and send debug logs, which will accompany this post. 

#### What did you expect?
I expected the left hand spaces panel to expand to display child spaces.
#### What happened instead?
Element ... told me to report a bug, which I take to be a crash of some kind. 

### Operating system

Linux - KDE NEON

### Application version

Element Desktop 1.11.68

### How did you install the app?

apt/deb

### Homeserver

explodie.org / conduwuit 0.4.1 (main not release)

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-06 14:48
Duplicate of https://github.com/element-hq/element-web/issues/27503

**Closed by t3chguy** 2024-06-06 14:48 UTC
Labels: T-Defect
