### ISSUE TITLE
Cannot accept a user verification sent in a freshly created DM

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#28065] opened 2024-09-18 13:26 UTC
### Steps to reproduce

1. Where are you starting? What can you see?

Try to verify someone when you don't yet have a DM with.
In order to start the verification, a new DM room will be created.

The recipient will see the invite, and after accepting he will only see 
<img width="537" alt="image" src="https://github.com/user-attachments/assets/29145aa9-c01e-4ba7-a5ea-f3b7de4b5733">

There is no UX, no dialog to interact with.

This flow used to work before the following change https://github.com/matrix-org/matrix-react-sdk/pull/11931

But it is not anymore.

If you request the verification when there is already an existing DM, the recipient will see a dialog to accept the request

#### What did you expect?

To be able to accept the verification request

#### What happened instead?

No UX/Dialog to do it.

### Operating system

all

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2024-09-18 14:02
> Try to verify someone when you don't yet have a DM with. In order to start the verification, a new DM room will be created.
> 
> The recipient will see the invite, and after accepting he will only see <img alt="image" width="537" src="https://private-user-images.githubusercontent.com/9841565/368586378-29145aa9-c01e-4ba7-a5ea-f3b7de4b5733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjgwMjAsIm5iZiI6MTcyNjY2NzcyMCwicGF0aCI6Ii85ODQxNTY1LzM2ODU4NjM3OC0yOTE0NWFhOS1jMDFlLTRiYTctYTVlYS1mM2I3ZGU0YjU3MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTM1NTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjFkNmQ0NWY1YWY5NmIzMjY1NTA0OTlhYWU4ZDYyNzJiZTBjMWFhNmRlMjMyNTVjODg5YmM3NTUxODUzYmY5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j0o4H1WeQ7TpL7R4flDWVU6O7Nl2Mf9yoLG_vvecDz4">
> 
> There is no UX, no dialog to interact with.

I was unable to reproduce this.

On the recipient side:

1. I saw the invite:
![image](https://github.com/user-attachments/assets/ee9dc857-59f2-4aa6-99b5-d870d685cdc3)
![image](https://github.com/user-attachments/assets/5cd4a594-6bfe-4610-b750-c4ae5e78c6a3)

2. After clicking "start chatting" I saw this toast:
![image](https://github.com/user-attachments/assets/7d02bcbc-6a55-40e1-a1e2-af89c8543c3a)

3. I was able to start the verification process as normal.

It sounds like something specific went wrong in your case, Valere, rather than this being a general failure mode.

**Comment by andybalaam** [comment] 2024-09-30 13:11
Unable to reproduce, closing for now.

**Closed by andybalaam** 2024-09-30 13:11 UTC
Labels: T-Defect, S-Major, A-E2EE-SAS-Verification, O-Uncommon, A-DM-Start, A-Element-R
