### ISSUE TITLE
:+1: emoji is replaced by :o: emoji when final : is written

### ISSUE THREAD

**Issue by michaelkaye** [element-hq/element-web#21014] opened 2022-02-09 17:19 UTC
### Steps to reproduce

When typing `: + 1 :` to put a thumbs up, i end up with :o: instead.

at the point of typing `: + 1 <tab or mouse click>` i get the right one.

(see video)

#### What did you expect?
:+1: 
#### What happened instead?
:o:

### Operating system

Linux ubuntu

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by michaelkaye** [comment] 2022-02-09 17:22
https://user-images.githubusercontent.com/1917473/153255249-e9d06bd3-4909-4271-9599-a38377043c79.mp4

**Comment by HarHarLinks** [comment] 2022-02-09 17:24
dupe of #19302

**Closed as completed** 2022-02-09 17:26 UTC
Labels: T-Defect, A-Autocomplete, A-Emoji
