### ISSUE TITLE
Switching spaces unintentionally marks random intentionally left unread room as read

### ISSUE THREAD

**Issue by rda0** [element-hq/element-web#28388] opened 2024-11-05 18:48 UTC
### Steps to reproduce

1. I see Element with 2 columns (the spaces and the rooms of the selected space `1`) and a lot of white dots, grey and red numbers next to them.
2. Now I need to check room `K` (in space `2`). Or I heard some ping and my best guess is that the ping came from space `2`. If it is not in space `2` I will have to check space `3-n` until the room with the ping is found.
3. I am forced to interact with Element and to click on those spaces in order to find out what is going on. (Maybe there is something in some room which really matters now?)
4. But I have a problem: There is a room `F` in space `2` with an unread counter of 123, which I intentionally
left unread for reasons (like read it later when I have time for it). Or there is a DM with `jdoe` with an unread counter of 2, which I intentionally left unread for privacy reasons (I don't want to let them think (or know) that I am available or online or clicking around in my client) or for other reasons (like read it later when I have time for it).
5. I need those unread counters/markers (like in my email client) to not forget to read the unread stuff
6. Due to 4) and this bug I am scared of clicking on space `2` (or `3-n`)
7. But I have no choice and I click on space `2`

### What did you expect?

I expect my matrix client to honor my wish and leave the room which I successfully avoided for days untouched.

I never want the client to decide to open some random room and mark it as read.
My email client would never do this!

Ideally I would never even need to interact with the client if I need to monitor multiple rooms in multiple spaces. If I need to monitor 2 spaces I would like to have the ability to show the rooms of both spaces on screen at the same time, so that I do not have to interact with the client. A quick look would be enough. Like it was possible with room tags or as shown in #19140. I don't expect this to happen, but this bug should be fixable?

### What happened instead?

Element randomly (or preferably based on highest unread count in that space?) selects that room `F` on its own, show it to me in the timeline column, mark it as read, clear the unread count, send other users read receipts, etc. (I know that the last room that was selected the last time when space `2` was active was not `F`)

- It could be that I don't even notice this happening, forget room `F` and never read it.
- It could be that someone gets information about me without me wanting them to know.

### Operating system

Linux, Windows

### Application version

Element version: 1.11.84 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

deb package

### Homeserver

phys.ethz.ch

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-11-05 18:54
Duplicate of https://github.com/element-hq/element-web/issues/26218 / https://github.com/element-hq/element-web/issues/19941

**Closed by t3chguy** 2024-11-05 18:54 UTC
Labels: T-Defect, S-Minor, A-Spaces, O-Occasional

**Comment by rda0** [comment] 2024-11-06 09:02
@t3chguy #19941 seems not to be valid for me (on Linux):

I just did:

- From some other space
- Click on `Matrix Community` space (not on the notification dot) -> brought me to https://matrix.to/#/#slack:maunium.net
- Switch to other space
- Click on `Matrix Community` space (not on the notification dot) -> brought me to https://matrix.to/#/#synapse:matrix.org

**Comment by rda0** [comment] 2024-11-06 09:10
Now it openend the space home 🤷
