### ISSUE TITLE
After a device verification, the device is still unverified

### ISSUE THREAD

**Issue by florianduros** [element-hq/element-web#27502] opened 2024-05-27 13:18 UTC
### Steps to reproduce

1. Launch verification from unverified Device B
2. Accept request from Device A
3. Do emoji SAS between the two devices
4. The verification ends with success
5. But in the session settings tab, the device is still unverified (If I refresh, the device stays unverified)

<img width="668" alt="Screenshot 2024-05-27 at 15 16 33" src="https://github.com/element-hq/element-web/assets/2621378/15c73b3c-b206-4098-ba1f-98adcb552d01">

#### What did you expect?

I'm expecting the device B to be verified.

### URL for webapp

local element

### Application version

Element version: !!UNSET!! Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment] 2024-05-27 13:29
It's an incomplete session problem:
Device B: `cross_signing_self_signing_privkey_cached: false`

So B cannot cross-sign and can't gossip the key to device A

So occurence of that https://github.com/element-hq/crypto-internal/issues/289

**Comment by richvdh** [comment] 2024-06-28 09:49
Duplicate of #27655

**Closed by richvdh** 2024-06-28 09:49 UTC
Labels: T-Defect, S-Major, A-E2EE-SAS-Verification, O-Uncommon, A-Element-R
