### ISSUE TITLE
Expanding and collapsing and expanding space in side bar crash

### ISSUE THREAD

**Issue by Stonley890** [element-hq/element-web#27541] opened 2024-06-08 04:36 UTC
### Steps to reproduce

1. Join a space that contains spaces.
2. In the side bar, click the arrow to expand the space and reveal the subspaces.
3. Click the same arrow to collapse.
4. Click the same arrow to expand.
5. "Something went wrong" screen appears.

#### What did you expect?
The space expands and collapses without errors.

#### What happened instead?
"Something went wrong!" screen appeared.

### Operating system

Linux Mint 21.3 Cinnamon (X session)

### Application version

Element version: 1.11.68 Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### How did you install the app?

https://flathub.org/apps/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-06-10 08:19
Duplicate of https://github.com/element-hq/element-web/issues/27503

**Closed by t3chguy** 2024-06-10 08:19 UTC
Labels: T-Defect, S-Major, A-Spaces
