### ISSUE TITLE
Flaky playwright test: `Spotlight > should find unknown people`

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26138] opened 2023-09-08 00:59 UTC
```
Timed out retrying after 10000ms: Expected to find element: .mx_SpotlightDialog_section.mx_SpotlightDialog_results .mx_SpotlightDialog_option, but never found it.
```

https://github.com/matrix-org/matrix-react-sdk/actions/runs/6115896270/job/16600238039#step:8:20244

**Comment by richvdh** [comment] 2023-09-20 20:30
https://cloud.cypress.io/projects/ppvnzg/runs/19256/test-results/dd4050c3-96e7-48fa-8ae2-b7fe7377f23b

**Comment by weeman1337** [comment] 2023-09-29 12:04
My current hypothesis is that the rooms are created too quickly before the profile information is populated in Synapse. https://github.com/matrix-org/synapse/issues/1444 I have found some notes bout that the user search only returns profiles of users in public rooms. But this is all a guess and I need to look into it further.

**Comment by weeman1337** [comment] 2023-09-29 12:05
Element Web seems to send the correct requests and also handles responses correctly. If test failures are too painful in CI we can deactivate the test until the issue is solved.

**Comment by richvdh** [comment] 2023-09-29 13:18
... it's certainly true that the public user directory is populated asynchronously within synapse. If the cypress tests aren't taking account of that, it could well explain the problem

**Comment by weeman1337** [comment] 2023-10-12 11:33
[Filed a Synapse issue](https://github.com/matrix-org/synapse/issues/16472)

**Comment by richvdh** [comment] 2024-02-29 15:45
cypress is dead, long live playwright

**Comment by t3chguy** [comment] 2024-10-31 12:48
Closing as fixed

**Closed by t3chguy** 2024-10-31 12:48 UTC
Labels: T-Defect, A-Developer-Experience, Z-Flaky-Test
