### ISSUE TITLE
Thread preview in main timeline can be misleading when quoting content

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-web#26957] opened 2024-02-02 09:19 UTC
#### What would you like to do?

When the thread preview is rendered in the timeline, it removes all the formatting, and this can be misleading when the last message contains quote.

For instance here:

<img width="1149" alt="image" src="https://github.com/element-hq/element-web/assets/3940906/23da7eb9-362b-48d6-9866-c86f24fef88c">

`benoit` did not really write `This message is sent by another user`, but just quoted it.

With the example the consequences are not important, but it can be really bad with other messages, I let you imagine what it could be.

So I would like the thread preview in the main timeline to be reliable regarding who has said what.

#### Why would you like to do it?

Trust in the product, and avoid confusion.

#### How would you like to achieve it?

Remove quoted content to render the thread preview, or any other solution.

**Comment by t3chguy** [comment] 2024-02-02 10:37
Duplicate of https://github.com/element-hq/element-web/issues/19945

**Closed by t3chguy** 2024-02-02 10:37 UTC
Labels: T-Enhancement
