### ISSUE TITLE
EW & MAS: Clicking 'Create Account' fails on the welcome screen when using MAS

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-web#27993] opened 2024-09-03 12:42 UTC
### Steps to reproduce

On a MAS enabled server (beta.matrix.org for instance)

Open Element Web
See 'Welcome to Element' screen

![image](https://github.com/user-attachments/assets/8d9e5b0a-6d97-4a80-96c0-cebdeb03b13f)

Click 'Create Account' 
See error message

![image](https://github.com/user-attachments/assets/905c8ddc-f58b-478f-a77a-318e548aaf3d)

#### What did you expect?
To be able to create an account following this flow

#### What happened instead?
You get an error message

There are probably two things to consider:
1) What should be the correct flow long-term, ie there are a couple of screens in the working flow that have sign-in and create account. The bug only happens if you click create account at the first opportunity / screen. If you click Sign In first rather than Create Account, then it works. 
2) A short term fix to get it working for now

### Homeserver

beta.matrix.org

### Will you send logs?

No

**Comment by wrjlewis** [comment] 2024-09-03 12:43
In terms of priority: the short-term fix is fairly urgent as it prevents users from registering new accounts on beta.matrix.org or where-ever else we want to enable MAS.

**Comment by americanrefugee** [comment] 2024-09-03 13:25
Also, [here's the vision for MAS](https://www.figma.com/design/66PalsLxjI7v0UAWF1bGE0/Compound-Matrix-Auth-Service-(MAS)-Templates?node-id=1-4)

**Comment by ara4n** [comment] 2024-09-04 02:55
my suggested short term fix would be "if create user view errors, redirect the user back to the signin view".

**Comment by sandhose** [comment] 2024-09-04 09:45
Fix on the Synapse side to make sure we return a sensible error: https://github.com/element-hq/synapse/pull/17661

**Comment by t3chguy** [comment] 2024-09-12 10:56
Duplicate of https://github.com/element-hq/element-web/issues/6847

**Closed as not planned by t3chguy** 2024-09-12 10:56 UTC
Labels: T-Defect, S-Critical, A-Registration, O-Occasional, A-OIDC
