### ISSUE TITLE
UTD

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27108] opened 2024-03-04 15:05 UTC
### Steps to reproduce

1.One room full of UTDs

#### What did you expect?
read content

#### What happened instead?
UTD

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2024030401
Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by kongo09** [comment] 2024-03-04 15:06
includes my own messages from another Element Desktop

**Comment by t3chguy** [comment] 2024-03-04 15:12
Duplicate of https://github.com/element-hq/element-meta/issues/245

**Closed by t3chguy** 2024-03-04 15:12 UTC
Labels: T-Defect
