### ISSUE TITLE
In rare cases, updating room history settings get applied correctly, but E does not see it

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#14843] opened 2020-07-31 15:01 UTC
### Description

Created a room and set `Who can read history?` to `Anyone`. The setting gets applied and other users joining the room can see the correct setting and can see messages from before they joined. 

This is that the user who created the room sees in their Element room settings:
This persists over 'Clear cache and reload`
![imagen](https://user-images.githubusercontent.com/19155609/89047382-3cd53a80-d346-11ea-92e1-63436d9fc842.png)

This is how the room settings looks for me:
<img width="389" alt="Screen Shot 2020-07-31 at 3 15 23 PM" src="https://user-images.githubusercontent.com/19155609/89047411-48286600-d346-11ea-8a99-b7f3e6f23887.png">

### Steps to reproduce

- unknown

Element should pick up on the correct room settings

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) 1.7.2

For the web app:

- **Browser**: Firefox 80.0
- **URL**: chat.mozilla.org

**Comment by Twi1ightSparkle** [comment] 2020-07-31 15:52
User has same bug in a new Element web session. But works on E Android

**Comment by t3chguy** [comment] 2024-11-18 12:22
Closing due to lack of reproduction in multiple years

**Closed by t3chguy** 2024-11-18 12:22 UTC
Labels: T-Defect, X-Cannot-Reproduce
