### ISSUE TITLE
Message history no longer loads reliably (may get hidden behind spurious "You can't see earlier messages")

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27274] opened 2024-04-03 16:30 UTC
### Steps to reproduce

See rageshake

#### What did you expect?

Visible history. Especially in non-E2EE rooms like this one.

#### What happened instead?

Incorrect "you can't see earlier messages" notification

### Application version

Element Nightly version: 2024040301 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment] 2024-04-14 14:29
This is completely reproduceable in the rageshaked room (which is unfortunate, as it's one of my main demo rooms)

**Comment by richvdh** [comment] 2024-06-14 09:26
duplicate of https://github.com/element-hq/element-web/issues/22671

**Closed by richvdh** 2024-06-14 09:26 UTC
Labels: T-Defect, X-Regression, S-Major, A-Timeline, O-Occasional
