### ISSUE TITLE
Messages partially typed in the Rich Text Editor are lost when we navigate in other rooms

### ISSUE THREAD

**Issue by giomfo** [element-hq/element-web#26871] opened 2024-01-15 16:07 UTC
### Steps to reproduce

- Enable the Rich Text Editor in the application settings
- Select a room and type a message without sending it
- Navigate to another room, and move back to the first one

#### What did you expect?
I expect to see my partially typed message in order to finish it and send it

#### What happened instead?
My partially typed message is lost - the composer is empty

### Operating system

macOS

### Application version

Element version: 3f578ad80adc-react-80e75e3b70ad-js-2ef3ebb466ec Crypto version: Olm 3.2.15

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-01-15 16:08
Duplicate of https://github.com/element-hq/element-web/issues/25135

**Closed by t3chguy** 2024-01-15 16:08 UTC
Labels: T-Defect
