### ISSUE TITLE
Timeline stuck in history

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-web#22512] opened 2022-06-10 09:10 UTC
### Steps to reproduce

1. Scroll up to look at older messages
2. Look at other rooms, then come back to original room

#### What did you expect?
I can at least scroll down to more recent messages

#### What happened instead?
Timeline doesn't show most recent messages. The read receipts are showing in the wrong place (all the people in the room have read down to the most recent message).

![Screenshot from 2022-06-10 10-04-07](https://user-images.githubusercontent.com/51663/173032763-6fde826b-5445-4afd-b389-55dac98e4a95.png)

### Browser information

Chromium 101.0.4951.64 (Official Build) Arch Linux (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.10.14
Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-11-18 12:23
Closing due to lack of reproduction in multiple years

**Closed by t3chguy** 2024-11-18 12:23 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Major, A-Timeline, A-Read-Receipts, O-Uncommon
