### ISSUE TITLE
Endless loading of entire web app

### ISSUE THREAD

**Issue by mpeter50** [element-hq/element-web#27794] opened 2024-07-21 13:26 UTC
### Steps to reproduce

1. I wanted to open this link: https://matrix.to/#/#vger.app:matrix.org
2. So I attempted to open it with my homeserver's web client this way: https://riot.grin.hu/#/#vger.app:matrix.org

#### What did you expect?

I expected the client to load up, and open the room I have put in the link

#### What happened instead?

The client started loading, I see the spinner (which is still moving, not frozen) and the log out button, but this has been going for 13 minutes now.

#### Additional information

Reloading, and reloading-without-cache multiple times did not help to solve the issue.
Application version was found by opening the client in a new container tab, and finding the "startUpdater, current version is 1.11.71" log message in the browser dev console, hopefully this is what you mean.

I will not be sending the normal logs, because I am unable to.
I'll upload console logs instead.

### Browser information

Firefox 126.0.1

### URL for webapp

https://riot.grin.hu/

### Application version

1.11.71

### Homeserver

https://matrix.grin.hu/

### Will you send logs?

No

**Comment by mpeter50** [comment] 2024-07-21 13:28
The console logs: https://gist.github.com/mpeter50/cdadf67268bca53ca1fc2216f1eef992

According to the devtools, all log messages that are not an error come from rageshake.ts:77:16

**Comment by t3chguy** [comment] 2024-07-22 07:50
> all log messages that are not an error come from rageshake.ts:77:16

That's because rageshake intercepts all logs to store them in IndexedDB also in case you want to submit or download them at a later date.

**Comment by t3chguy** [comment] 2024-07-22 07:51
`(Reason: CORS header ‘Access-Control-Allow-Origin’ missing)` all these CORS errors show that `matrix.grin.hu` isn't spec compliant. 

https://spec.matrix.org/v1.11/client-server-api/#web-browser-clients

Closing as a server problem

**Closed by t3chguy** 2024-07-22 07:51 UTC
Labels: T-Defect, S-Critical, O-Frequent

**Comment by grinapo** [comment] 2024-07-23 20:30
@t3chguy the server is spec compliant, there is no point providing CORS for a 404. Probably the problem is not related to the report.

**Comment by grinapo** [comment] 2024-07-23 20:59
…in fact the problem was uglier: `apache2` required `AllowEncodedSlashes NoDecode` in its revproxy config since keys contain percents in random positions, and `%2f` is an immediate 404 sue to security reasons.

**Comment by t3chguy** [comment] 2024-07-24 07:43
> there is no point providing CORS for a 404

Yes there is, as otherwise the client can't read that the status code is a 404, nor the Matrix errcode, thus cannot behave correctly. The spec I linked does not say "except on 404"
