### ISSUE TITLE
Session manager shows incorrect verification status

### ISSUE THREAD

**Issue by uhoreg** [element-hq/element-web#26989] opened 2024-02-08 15:08 UTC
### Steps to reproduce

Not sure how to reproduce, but could be related to rust migration, as I'm pretty sure it was displaying correctly before migrating.

#### What did you expect?

Session manager should show all my devices as verified

#### What happened instead?

Session manager shows all my devices (including itself) as unverified:

![image](https://github.com/element-hq/element-web/assets/1012976/c0dcfebb-c860-4ee8-a8aa-adcdfe170ebf)

User info panel in sidebar shows all my devices as verified:

![image](https://github.com/element-hq/element-web/assets/1012976/a769305d-5c64-4367-8bac-996aced1d94c)

Session manager on another device (develop.element.io, was always running rust crypto) shows everything correctly

![image](https://github.com/element-hq/element-web/assets/1012976/4fb38958-17c8-4517-a0a7-bfff3b68d925)

### Operating system

Debian Linux

### Application version

Element nightly 2024020701, Rust SDK 0.7.0 (691ec63), Vodozemac 0.5.0

### How did you install the app?

element.io Debian package repository

### Homeserver

uhoreg.ca, Synapse 1.100.0

### Will you send logs?

Yes

**Comment by uhoreg** [comment] 2024-02-08 15:39
Looks like the cause was that the client was missing some cross-signing key, and had to fetch it from SSSS.  So probably not a critical bug, but it's not nice that the session manager shows different results from the user info panel, and that it doesn't indicate what the problem is.

**Comment by BillCarsonFr** [comment] 2024-02-29 09:00
Closing as duplicate of https://github.com/element-hq/element-web/issues/27079

**Closed by BillCarsonFr** 2024-02-29 09:00 UTC
Labels: T-Defect, S-Major, O-Uncommon, Team: Crypto, Z-Labs, A-Element-R
