### ISSUE TITLE
Pre-join UISI hiding logic is somehow broken

### ISSUE THREAD

**Issue by dkasak** [element-hq/element-web#22671] opened 2022-06-28 11:27 UTC
### Steps to reproduce

1. Open the `!RqphPmfqRYPWcDpkqi:matrix.org` room \(you can message me privately on Matrix to find out which room this is\)
2. Scroll up until you reach a Figma screenshot and then a bit beyond that.
    This one:

![image](https://user-images.githubusercontent.com/463342/176166221-bbf292e7-d120-4e90-b86b-d85191f6f5f5.png)

1. While scrolling beyond the screenshot in 2, the client suddenly jumps to an earlier point of history. Attempting to scroll upwards again now shows a message from Amandine as the first message in the room:

![image](https://user-images.githubusercontent.com/463342/176166642-cc56e525-4622-4c8c-917f-48345b117bdd.png)

The earlier screenshot from step 2 is now unreachable.

#### What did you expect?

I expect the client not to randomly hide a chunk of the room from me.

#### What happened instead?

The client hid a chunk of the room from me and prevented me from scrolling beyond. I suspect this is related to the pre-join UISI hiding logic, since at the point the jump happens, the following happens in the console:

![image](https://user-images.githubusercontent.com/463342/176166902-4f431a2e-8825-4e76-a11a-fa22eec6ac7a.png)

I must admit the pre-join UISI hiding has so far proven to be more of a nuisance than anything useful.

### Operating system

Arch Linux

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### How did you install the app?

Arch Linux repository

### Homeserver

termina.org.uk, Synapse 1.60.0

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment] 2022-06-30 04:23
Possibly related: https://github.com/matrix-org/matrix-react-sdk/pull/8563

**Comment by SimonBrandner** [comment] 2022-06-30 04:24
Possibly related https://github.com/matrix-org/matrix-react-sdk/pull/8563

**Comment by dkasak** [comment] 2022-09-11 20:47
And now after switch to another room and then back, I can again scroll upwards beyond this point, so there may be some race condition at play?

**Comment by z411** [comment] 2023-01-10 10:16
I"m also affected by this; indeed other clients show an undecryptable event just before the join, thus Element shows this message with the `checkForPreJoinUISI: did not find pre-join UISI` log message and hides all history with the `You can't see earlier messages` box. Switching rooms doesn't fix it for me.

**Comment by richvdh** [comment] 2023-04-20 13:54
seems to be a duplicate of https://github.com/vector-im/element-web/issues/22671?

**Comment by t3chguy** [comment] 2024-05-10 20:51
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12464 which removes the `checkForPreJoinUISI` code

**Closed by t3chguy** 2024-05-10 20:51 UTC
Labels: T-Defect, S-Major, A-E2EE, A-Timeline, O-Occasional
