### ISSUE TITLE
Screen sharing from withing a call not working on Kubuntu Linux using wayland session. 

### ISSUE THREAD

**Issue by janewayuk** [element-hq/element-web#26809] opened 2023-12-26 16:53 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
When in a call

3. What do you click?
The Screen share  button

5. More steps…
The KDE Screen Share Portal pops up asking what screen or window I would like to share. I choose the screen I want to share with the call and click share. 
![image](https://github.com/element-hq/element-web/assets/82512093/91ab766a-15a6-4b68-8ded-b368a7979b4a)

#### What did you expect?
The chosen screen to start sharing to other users on the call. 

#### What happened instead?
The KDE Screen sharing portal pops up again within few seconds asking what screen or window I would like to share again . This behaviour happens again and again, like its stuck in a loop. 

### Operating system

Kubuntu 23.10

### Application version

Element version: 1.11.52 Crypto version: Olm 3.2.15

### How did you install the app?

https://element.io/download#linux

### Homeserver

Synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2023-12-29 10:12
Duplicate of https://github.com/element-hq/element-desktop/issues/683

**Closed by t3chguy** 2023-12-29 10:12 UTC
Labels: T-Defect
