### ISSUE TITLE
Pressing CMD+K does not trigger spotlight

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-web#22831] opened 2022-07-13 09:15 UTC
### Steps to reproduce

1. Press CMD+K

#### Extra info

This is a sporadic issue, I can not reproduce it consistently but i have encountered a number of times over the past two weeks.
Switching spaces or rooms does seem to fix the problem

It looks like the `LinkPreviewWidget` is throwing an exception in the console. I don't know whether this is related a not, but you'll find a rageshake attached to this issue 

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-07-13 09:21
> It looks like the LinkPreviewWidget is throwing an exception in the console. I don't know whether this is related a not, but you'll find a rageshake attached to this issue

This is unrelated and already fixed, your Nightly is 3 days out of date.

**Comment by daniellekirkwood** [comment] 2023-05-05 14:05
@gsouquet this still an issue for you?

**Comment by gsouquet** [comment] 2023-05-05 14:39
It occasionally happens yes, but i have been unable to determine the trigger

**Comment by t3chguy** [comment] 2024-11-18 12:25
Closing due to lack of reproduction in over a year

**Closed by t3chguy** 2024-11-18 12:25 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Tolerable, O-Uncommon, A-New-Search-Experience
