### ISSUE TITLE
Login form's placeholder switches between upper and lower case

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#22813] opened 2022-07-11 20:48 UTC
### Steps to reproduce

1. Go to login screen
2. position cursor inside username field
3. watch Username get lowercased

#### What did you expect?
Username appears multiple times, including as a placeholder in the input field. upon entering the field, it should not change, but only disappear once you start typing. The password field has this behaviour.
#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/178354842-7ac39adf-3862-4777-93d9-b72fef308c1a.png)

In a i18n such as :de:, nouns are generally spelled with an upper case first letter. Here, converting to lower is even more wrong compared to the fact that all your other labels stick to upper case:
![image](https://user-images.githubusercontent.com/2803622/178355096-7549c02a-22b0-4666-bb2c-87306bc74721.png)

Might be caused by:
https://github.com/matrix-org/matrix-react-sdk/blob/d599b1b206dba16fecdaf1824e2de38a302e4b60/src/components/views/auth/PasswordLogin.tsx#L317

### Operating system

arch

### Application version

Element Nightly version: 2022071101 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by robintown** [comment] 2022-07-11 21:36
If I recall, this is done as a subtle hint that the username needs to be all lowercase. It is weird though.

**Comment by t3chguy** [comment] 2022-07-12 06:25
Duplicate of https://github.com/vector-im/element-web/issues/21820

**Comment by HarHarLinks** [comment] 2022-07-12 11:28
You could mark this as duplicate, but what #21820 fails to point out is that this input field's behaviour in particular makes no sense. Even if it is intended to be lower case, then the unselected state is defective:
![image](https://user-images.githubusercontent.com/2803622/178479744-e7b5952e-9b28-4c90-b41e-462059b41245.png)

**Comment by HarHarLinks** [comment] 2022-07-12 11:57
@t3chguy 
> Duplicate of #21820

sorry, I think there is some confusion.

That issue is about the registration form and the UX around creating only new lowercase MXIDs. This issue here is about the login form and capitalization of the placeholder at a point where the capitalization of the placeholder is simply irrelevant because users already need to remember the spelling of their names anyway. The only thing I think you could do is upon failed login attempt with upper case letters, include in the error message to perhaps try lower case, or try that automatically.

**Comment by t3chguy** [comment] 2022-07-12 12:01
Yes, but the reason it is lowercase is as a failed solution to https://github.com/vector-im/element-web/issues/21820 - so closing as duplicate to find a better solution and revert this one.

**Comment by t3chguy** [comment] 2022-07-12 12:01
Oh my bad on registration vs login

**Closed** 2024-02-15 12:40 UTC
Labels: T-Defect, S-Tolerable, A-Login, X-Needs-Design, O-Frequent
