### ISSUE TITLE
The display of the screen on the desktop version does not work in the group chat.

### ISSUE THREAD

**Issue by AlexanderGasman** [element-hq/element-web#28085] opened 2024-09-20 13:49 UTC
### Steps to reproduce

The display of the screen on the desktop version does not work in the group chat. Everything works in the web version.
Tested on different computers and Windows 10-11 operating systems. User rights-administrators/moderators
![2024-09-20_164034](https://github.com/user-attachments/assets/7c196dc5-612b-4591-9402-4a8e2be6e282)

#### What happened instead?
The display of the screen on the desktop version does not work in the group chat.

### Operating system

Windows10,11

### Application version

Element Nightly: 0.0.1-nightly.2024092001 Криптоверсия: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-09-24 09:16
Duplicate of https://github.com/element-hq/element-desktop/issues/683

**Closed by t3chguy** 2024-09-24 09:16 UTC
Labels: T-Defect, S-Major, O-Occasional, Z-Labs, A-Element-Call
