### ISSUE TITLE
verify by text do nothing

### ISSUE THREAD

**Issue by BasilYes** [element-hq/element-web#27307] opened 2024-04-09 10:01 UTC
### Steps to reproduce

Room info -> people -> select unverified account (picture 1) -> select unverified session (picture 2) -> click verify by text (picture 3)-> click verify session (picture 3) and... nothing heppend
![image](https://github.com/element-hq/element-web/assets/36816595/c3c9e584-cc31-4961-87f0-157ca2a1acf1)
![image](https://github.com/element-hq/element-web/assets/36816595/1eb62701-f64e-49e1-b1aa-3b0571569b47)
![image](https://github.com/element-hq/element-web/assets/36816595/9ce3832b-4f66-40b9-8995-ed941e9ab034)
![image](https://github.com/element-hq/element-web/assets/36816595/2ddf1d2b-1e45-497e-be1e-557a24e6192d)

#### What did you expect?
window closed, session verified 
#### What happened instead?
nothing

### Operating system

NixOS linux

### Application version

Element version: 1.11.63 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### How did you install the app?

in web browser, native pakege and flatpak (all)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-04-09 10:02
Duplicate of https://github.com/element-hq/element-web/issues/27201

**Closed by t3chguy** 2024-04-09 10:02 UTC
Labels: T-Defect
