### ISSUE TITLE
Full Freeze in one specific channel

### ISSUE THREAD

**Issue by YourSandwich** [element-hq/element-web#27012] opened 2024-02-14 22:27 UTC
### Steps to reproduce

It's not easily reproducible since it happens in just one specific chat.

1. Join The chat.
2. Wait or Scroll

Both users are on the same server.
I believe the first time it happened was about 4 months ago, when the sender sent a voice message.

This does not Happen on Element X

### Outcome

Element Desktop Freezes completly with this stdout

```
Error getting the event index passphrase out of the secret store [Error: The name is not activatable]
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG

<--- Last few GCs --->

[1:0x34dc30c94000]     1645 ms: Mark-Compact (reduce) 404.7 (428.1) -> 243.0 (249.1) MB, 102.99 / 0.00 ms  (average mu = 0.936, current mu = 0.799) last resort; GC in old space requested
[1:0x34dc30c94000]     1804 ms: Mark-Compact (reduce) 243.0 (249.1) -> 243.0 (247.9) MB, 159.14 / 0.00 ms  (average mu = 0.785, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

[199078:0214/231511.530936:ERROR:v8_initializer.cc(789)] V8 javascript OOM (CALL_AND_RETRY_LAST).
```

### Operating system

Arch Linux

### Application version

Element Nightly version: 2024021401 Crypto version: Olm 3.2.15

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Homeserver

https://archworks.co | Synapse 1.101.0

### Will you send logs?

Yes

**Comment by YourSandwich** [comment] 2024-02-14 22:34
The Issue is with the RoomID `!WAxBAeiOXmflFgjefd:archworks.co`

**Comment by YourSandwich** [comment] 2024-02-14 22:42
This also happens on the Stable Client

```
Element version: 1.11.57
Crypto version: Olm 3.2.15
```

**Comment by YourSandwich** [comment] 2024-04-18 16:10
Nothing changed. I can manage to keep the client working as long as i don't scroll up sometimes.
This happens only on Element Desktop Client.

**Comment by YourSandwich** [comment] 2024-04-18 16:13
Same result on Windows. Other clients like Cinny, Fractal, Fluffychat are unaffected.

**Comment by YourSandwich** [comment] 2024-04-18 16:15
Can I get some tips on debugging this? Maybe I could delete some unimportant events that are maybe causing this?

One specific thing about this DM Room is, it has Gigabytes of Voice Messages and other Media.

**Comment by t3chguy** [comment] 2024-04-18 16:17
Duplicate of https://github.com/element-hq/element-web/issues/26239

**Closed by t3chguy** 2024-04-18 16:17 UTC
Labels: T-Defect, S-Major, O-Uncommon
