### ISSUE TITLE
Sync loop stopped working for unknown reasons

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#26608] opened 2023-11-20 05:45 UTC
### Steps to reproduce

1. Run the app for a while?

#### What did you expect?

Syncing.

#### What happened instead?

I noticed that my rooms stopped updating, but my server's federation was OK. Element X Android was still able to sync and receive push notifications to prove the server was receiving traffic.

There was no visual indication that Element Desktop (Nightly) stopped syncing, other than the stale rooms. The "offline" banner didn't appear. No obvious errors in console either.

I've had this happen on my laptop before several times, but assumed it was related to Windows going to sleep. This machine however does *not* go to sleep and was in use at the time it stopped.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023111901 Crypto version: Olm 3.2.15

### How did you install the app?

The Internet

### Homeserver

t2l.io, workerized Synapse

### Will you send logs?

Yes

**Comment by turt2live** [comment] 2023-11-20 05:50
Quitting the application from the task tray and reopening it appears to resolve the issue, albeit with a long startup due to time between syncs.

**Comment by t3chguy** [comment] 2023-11-20 07:57
Sounds like https://github.com/vector-im/element-web/issues/25113 so not a new symptom

**Comment by o0oo00o0o** [comment] 2024-03-14 23:47
This is happening to me on iOS, except nothing gets it working again. I’ve even tried deleting and reinstalling the app.

**Comment by t3chguy** [comment] 2024-03-15 09:25
@o0oo00o0o Element Web doesn't support mobile.

**Comment by t3chguy** [comment] 2024-11-18 12:26
Closing due to lack of reproduction in over a year

**Closed by t3chguy** 2024-11-18 12:26 UTC
Labels: T-Defect, X-Cannot-Reproduce, S-Critical, O-Uncommon
