### ISSUE TITLE
Encryption on develop breaks when bundles dont load in time

### ISSUE THREAD

**Issue by MTRNord** [element-hq/element-web#27622] opened 2024-06-22 09:18 UTC
### Steps to reproduce

1. Have one bundle fail to load

#### What did you expect?

It retries or refuses to continue running

#### What happened instead?

It gave me the "your encryption is unrecoverable" error

### Operating system

Fedora Silverblue 40

### Browser information

Firefox 127.0 (64-Bit)

### URL for webapp

develop.element.io

### Application version

Unknown due to being stuck in an error dialog

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

Yes

**Comment by MTRNord** [comment] 2024-06-22 09:19
a workaround usually is to _not_ click the logout but rather do a full reload without cache

**Comment by richvdh** [comment] 2024-06-24 10:52
Duplicate of https://github.com/element-hq/element-web/issues/27361, I believe

**Closed by richvdh** 2024-06-24 10:52 UTC
Labels: T-Defect, S-Critical, A-E2EE, O-Uncommon
