### ISSUE TITLE
Message jumps, after clicking on a message link, only occur once

### ISSUE THREAD

**Issue by K4LCIFER** [element-hq/element-web#26769] opened 2023-12-15 08:20 UTC
### Steps to reproduce

1. send a link to a message (triple dots, share, copy message link, send)
2. click on it
3. observe that a jump occurs
4. scroll down
5. click again
6. observe that nothing happens

#### What did you expect?

I would expect that it would jump every time the message link is clicked

#### What happened instead?

only one jump occured

### Operating system

Arch Linux, Kernel v6.6.7-arch1-1

### Application version

Element version: 1.11.51 Crypto version: Olm 3.2.15

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2023-12-15 11:00
Duplicate of https://github.com/element-hq/element-web/issues/26179

**Closed by t3chguy** 2023-12-15 11:00 UTC
Labels: T-Defect
