### ISSUE TITLE
Notifications showing up at every startup for messages i already read.

### ISSUE THREAD

**Issue by arnodu** [element-hq/element-web#27257] opened 2024-03-29 11:08 UTC
### Steps to reproduce

Just start Elements : at every startup, notifications show up for older messages i already read.

The messages all come from the same user, they may have in common that the message have been edited by the sender at some point, but i'm not sure.

#### What did you expect?
No notification at startup. Or at least not for older messages.
#### What happened instead?
Same notifications appear every time for messages that i already read.

### Operating system

Arch Linux / Manjaro

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### How did you install the app?

Manjaro repositories

### Homeserver

non-public Synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-03-29 11:09
Duplicate of https://github.com/element-hq/element-web/issues/24392

**Closed by t3chguy** 2024-03-29 11:09 UTC
Labels: T-Defect
