### ISSUE TITLE
Your browser can't run Element (Firefox ESR)

### ISSUE THREAD

**Issue by jgoerzen** [element-hq/element-web#27785] opened 2024-07-18 20:44 UTC
### Steps to reproduce

1. At the homepage for my Element installation, it says "Unsupported browser: Your browser can't run element"

Element is unusable.

The system is running Debian stable, which has Firefox 115.13.0esr.  The issue began after an upgrade to Element, from 1.11.69 to 1.11.71.  Clearing cookies and LocalStorage did not help.

I am unable to send logs because the app will not load far enough to do so.

This is on a private server.

#### What did you expect?

Element to load.

#### What happened instead?

The error listed above.  Here is the browser console output:

![element-issue](https://github.com/user-attachments/assets/6b8dae70-4cc5-4277-87c0-b1ed8373bdb6)

### Operating system

Debian Linux

### Browser information

Firefox 115.13.0esr

### URL for webapp

1.11.71

### Application version

Element 1.11.71

### Homeserver

Synapse 1.111.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-07-18 22:31
Duplicate of https://github.com/element-hq/element-web/issues/27684

**Closed by t3chguy** 2024-07-18 22:31 UTC
Labels: T-Defect, S-Critical, A-Error-Message
