### ISSUE TITLE
Key Backup is broken (for my account/client) with NO warning and NO remediation steps

### ISSUE THREAD

**Issue by colemickens** [element-hq/element-web#27330] opened 2024-04-13 01:18 UTC
### Steps to reproduce

1. I have no idea. Be me? On Element Web (same behavior on two different laptops)? Try to join **Key Backup**

Please see this 30 second demo for context: https://www.youtube.com/watch?v=mHDxBK4klss

#### What did you expect?

* Joining Key Backup to work.
* Automatically, when I verified this session.

In lieu of it not working, it should guide me through how to fix it. And warn me that it *didn't actually connect*.

The entire UX of this page needs a lot of love, and I say that with ... love and concern and maybe some other emotions.

#### What happened instead?

1. There was **NO** warning that my  clients were not participating in Key Backup. Ever, as far as I can tell
 
2. There was **NO** warning after attempting to join Key Backup, that I *had still not joined Key Backup*. If I weren't paying attention, this would have caused data loss, as I'm due to return a loaner laptop which was the *only* place those keys were stored until I manually backed them up.

3. There were no instructions on how to remediate "Failed to decrypt 8 sessions". I honestly have NO idea what that means, or how to fix it.

4. There is no clear way for me to "Fix" Key Backup. 

### Operating system

Linux, NixOS, 6.6.26

### Browser information

Firefox - 126.0a1 - 20240412093252

### URL for webapp

develop.element.io

### Application version

Element version: 8ce46d3de88e-react-6392759bec51-js-475f82c5ce94 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by colemickens** [comment] 2024-04-13 01:18
(I did the rageshake thing, it seemed successful! Hope y'all got it!)

**Comment by richvdh** [comment] 2024-06-11 11:40
Duplicate of https://github.com/element-hq/element-web/issues/26530, mostly. 

The 8 failed sessions are corrupt in some way, likely due to a bug in another client, probably https://github.com/element-hq/element-meta/issues/2338. Unfortunately there's not much more information we can give you here.

**Closed by richvdh** 2024-06-11 11:40 UTC
Labels: T-Defect, S-Major, A-E2EE, A-E2EE-Key-Backup, O-Uncommon, Team: Crypto
