### ISSUE TITLE
Quick Switching between homeservers

### ISSUE THREAD

**Issue by kriki200** [element-hq/element-web#28365] opened 2024-11-02 01:43 UTC
#### What would you like to do?

Quickly switch between homeservers with one click.

#### Why would you like to do it?

That you'd have an option when clicking on your profile picture in the topr right to change the server and would switch the server and log you in with one click.

### Have you considered any alternatives?

There isn't one.

**Comment by t3chguy** [comment] 2024-11-04 09:50
Duplicate of https://github.com/element-hq/element-web/issues/2320

**Closed by t3chguy** 2024-11-04 09:50 UTC
Labels: T-Enhancement, A-Session-Mgmt, T-Feature
