### ISSUE TITLE
Red notification for a specific room doesn't go away

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27860] opened 2024-07-26 09:22 UTC
### Steps to reproduce

1. Observe room list
2. Notice a certain room with a red (1) notification
3. Visit the room
4. Go elsewhere
5. Observe room list again

#### What did you expect?
Notification for visited room is gone

#### What happened instead?
Notification stays around.

There is nothing unread in those rooms, including threads.

### Operating system

Windows 11

### Application version

Element version: 1.11.71
Crypto version: Rust SDK 0.7.1 (80a151e), Vodozemac 0.6.0

### How did you install the app?

element.io

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-07-26 09:24
Duplicate of https://github.com/vector-im/element-web/issues/24392

**Closed by t3chguy** 2024-07-26 09:24 UTC
Labels: T-Defect
