### ISSUE TITLE
Logout fails if homeserver is down

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-web#21160] opened 2022-02-22 15:21 UTC
### Steps to reproduce

1. Make your homeserver database crash
2. Try logging out

#### What did you expect?

To be logged out from the client

#### What happened instead?

<img width="843" alt="Screen Shot 2022-02-22 at 15 19 44" src="https://user-images.githubusercontent.com/769871/155162884-0a1cabdd-d75a-42aa-b88d-37d688d2f470.png">

The above modal appear, and the spinner stayed on until the request to the homeserver timed-out. When clicking "I don't want my encrypted messages", the modal got dismissed but my client did not log me out

### Will you send logs?

No

**Comment by t3chguy** [comment] 2022-02-22 16:25
Duplicate of https://github.com/vector-im/element-web/issues/2289

**Closed as completed by t3chguy** 2022-02-22 16:25 UTC
Labels: T-Defect, S-Major, A-Logout, O-Uncommon
