### ISSUE TITLE
Custom/extra fields of user profile

### ISSUE THREAD

**Issue by DimitryVo** [element-hq/element-web#27448] opened 2024-05-08 07:45 UTC
#### What would you like to do?
Add custom/extra fields to user profile, f.e. position, and set it value from token of OpenID

#### Why would you like to do it?
Custom requirements

#### How would you like to achieve it?
Best solution is possibility to add custom user profile fields to synapse with mapping it from OpenID and auto add it to UX of Element-WEB, maybe by custom template.

How can I add custom fields?

**Comment by t3chguy** [comment] 2024-05-08 07:48
Duplicate of https://github.com/element-hq/element-meta/issues/896

**Closed by t3chguy** 2024-05-08 07:48 UTC
Labels: T-Enhancement
