### ISSUE TITLE
Riot should be optimised to work in portrait mode

### ISSUE THREAD

**Issue by jmkim** [element-hq/element-web#8716] opened 2019-02-15 21:45 UTC
## Problem
- Cannot read message properly while using the vertical layout (resolution 900x1600).

## Suggestion
- **Left sidebars should be hideable (both `TagPanel` and `RoomList`)**.
    - `TagPanel` is fixed. It should be hidable.
    - `RoomList` is resize-able, but still not hideable. It should be hideable for maximising the main contents (messages).
- Read receipt show as vertically (change interactively if vertical window size is too small).

## Screenshot
![riot-portrait](https://user-images.githubusercontent.com/3622008/52885399-68954c80-31b4-11e9-86e5-2ef177a06eeb.png)

**Comment by nerwall** [comment] 2019-02-19 07:32
I place all my messaging apps on a 900px wide monitor. Riot is by far the most cramped. Hiding the right panel makes it usable but the left panels always being open and the communities panel being separate wastes a significant amount of space.

**Comment by jryans** [comment] 2019-02-19 10:56
I believe the current design generally assumes a landscape orientation. If other people are also using / wanting to use Riot in portrait mode, please add a reaction to the top comment here so we can understand the priority of this.

**Comment by egolus** [comment] 2019-02-20 14:53
I use it in portrait mode and when I hide the right panel and minimize the left it's usable. As a first fix it would be enough if riot remembered these configurations so I don't have to do it every time I open the app

**Comment by chmln** [comment] 2019-03-19 01:37
IMO the left-most sidebar is rather useless right now, with its only useful feature being the "communities" button. Why not place communities under rooms?

Having an entire sidebar for just two buttons is a waste of space. I have used Riot for months and don't think I've clicked on "communities" even once.

**Comment by jryans** [comment] 2019-03-19 09:36
Communities aren't currently used very much because they have many issues at multiple levels, including UX, feature set, APIs, etc. Reworking communities is coming up soon on our roadmap, so much of this should improve.

**Comment by aaronraimist** [comment] 2019-04-02 19:39
@chmln if you don't use communities then there already is an option in the preferences to disable the entire left-most communities panel

for people who are actually in communities (or use the tags feature) it is insanely useful but you just probably aren't one of those users.

**Comment by chmln** [comment] 2019-04-02 19:50
@aaronraimist :tada::tada::tada: that is amazing, thank you so much for pointing it out - I didn't even know there was an option to disable it.

**Comment by afranke** [comment] 2023-04-22 10:12
> @chmln if you don't use communities then there already is an option in the preferences to disable the entire left-most communities panel

Is this option still a thing in 2023? I couldn’t find it.

**Comment by t3chguy** [comment] 2024-12-04 12:29
Duplicate of https://github.com/element-hq/element-web/issues/1633

**Closed by t3chguy** 2024-12-04 12:29 UTC
Labels: T-Enhancement
