### ISSUE TITLE
FacePile component regression: overlapping faces

### ISSUE THREAD

**Issue by anoadragon453** [element-hq/element-web#27110] opened 2024-03-04 16:42 UTC
### Steps to reproduce

![image](https://github.com/element-hq/element-web/assets/1342360/c507967c-4574-4096-93ec-4ea1aa620243)

1. View a timeline of a room that has multiple recent read receipts
2. See that elements from different faces (outline, avatar) overlap each other in an unexpected way.

### Outcome

This appears to be a recent regression in the display of user read receipts.

### Operating system

NixOS Linux

### Application version

Element version: 1.11.59, Crypto version: Olm 3.2.15

### How did you install the app?

From https://github.com/NixOS/nixpkgs/

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-03-04 16:49
Duplicate of https://github.com/element-hq/element-web/issues/26987

**Closed by t3chguy** 2024-03-04 16:49 UTC
Labels: T-Defect
