### ISSUE TITLE
Behaviour when trying to DM a federated user on a server with federation disabled is awful

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27438] opened 2024-05-07 06:13 UTC
### Steps to reproduce

1. Logged into the OIDC test lab
2. Tried to DM myself on matrix.org (see also https://github.com/element-hq/element-web/issues/27437)
3. Got an ambiguous "failed" error in the proto DM.
4. Tried again, which created a new proto DM.
5. Restarted the app
6. Now have two proto-dms in the room list, which provide a 'join' button.
7. Hitting the join button produces a fugly error complaining about trying to call `/join` on a `local+...` room ID.

#### What did you expect?

 * Reasons why I can't send messages should be shown to the user in the nice red warning error, so the user knows what's going on.
 * Failed proto-DMs should be reused when trying to contact the same user
 * Failed proto-DMs should not switch to showing a 'join' button which doesn't work, when you refresh

#### What happened instead?

 * The error from the server (`{errcode: "M_FORBIDDEN", error: "Federation denied with matrix.org."}`) was swallowed entirely by the UI.
 * I ended up with multiple broken DMs to the same user
 * They ended up giving me useless buggy 'join' buttons

### URL for webapp

https://pr12370--matrix-react-sdk.netlify.app/

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-05-07 07:28
Duplicate of https://github.com/element-hq/element-web/issues/24991

**Closed by t3chguy** 2024-05-07 07:28 UTC
Labels: T-Defect, S-Major, A-Federation, A-DM-Start
