### ISSUE TITLE
File and image sharing is broken

### ISSUE THREAD

**Issue by artenax** [element-hq/element-web#28248] opened 2024-10-19 23:53 UTC
Read more
https://github.com/matrix-org/matrix.org/issues/2537
https://github.com/matrix-org/matrix.org/issues/2538

**Comment by t3chguy** [comment] 2024-10-21 08:14
Duplicate of https://github.com/element-hq/element-web/issues/28018

**Closed by t3chguy** 2024-10-21 08:14 UTC
Labels: T-Defect, A-File-Upload
