### ISSUE TITLE
My application cannot display the human-machine authentication

### ISSUE THREAD

**Issue by EACjn** [element-hq/element-web#28423] opened 2024-11-12 04:42 UTC
### Steps to reproduce

I used a network proxy to register an account. The server is the default setting, but I tried for a long time and it didn't show the human-machine verification. I also tried to change the proxy server but it didn't work.

### Outcome

导致我无法通过人机验证从而无法注册账号
![屏幕截图 2024-11-12 115357](https://github.com/user-attachments/assets/2f961479-04fa-465c-942d-e36291d1b7ab)

### Operating system

Windows11

### Application version

1.11.84.0

### How did you install the app?

https://github.com/element-hq/element-web/releases

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-11-12 09:44
Duplicate of https://github.com/element-hq/element-web/issues/12137

Your chosen Matrix homeserver requires captcha which uses gstatic.cn which is not safe to allow access to.

**Closed by t3chguy** 2024-11-12 09:44 UTC
Labels: T-Defect, S-Critical, A-Registration, O-Uncommon

**Comment by EACjn** [comment] 2024-11-15 09:26
> 的重复 [#12137 ](https://github.com/element-hq/element-web/issues/12137)
> 
> 您选择的 Matrix 家庭服务器需要使用 gstatic.cn 的验证码，而 gstatic.cn 是不安全的，不允许访问。

Thank you for your answer, but how can I solve it? I searched online but couldn't find the answer. I tried using v2rayn's tun mode but couldn't load the human-machine verification. I also tried the web version. I'm using Firefox.

**Comment by t3chguy** [comment] 2024-11-15 09:31
You would need to pick a Matrix server which doesn't rely on services blocked in your country

**Comment by EACjn** [comment] 2024-11-15 09:33
> 您需要选择一个不依赖于您所在国家/地区阻止的服务的 Matrix 服务器

Thanks

**Comment by EACjn** [comment] 2024-11-17 06:52
> > > 的重复 [#12137 ](https://github.com/element-hq/element-web/issues/12137)
> > > 您选择的 Matrix 家庭服务器需要使用 gstatic.cn 的验证码，而 gstatic.cn 是不安全的，不允许访问。
> > 
> > 
> > Thank you for your answer, but how can I solve it? I searched online but couldn't find the answer. I tried using v2rayn's tun mode but couldn't load the human-machine verification. I also tried the web version. I'm using Firefox.
> 
> 这个老毛病了，我用v2rayn开全局代理是可以刷出验证框的，套个tor也能刷出来

ok了全局可以注册，谢谢
