### ISSUE TITLE
Jitsi preferred domain not respected

### ISSUE THREAD

**Issue by crjo** [element-hq/element-web#26862] opened 2024-01-11 14:58 UTC
### Steps to reproduce

Tried to change jitsi default server following configuration tips from https://github.com/element-hq/element-web/blob/master/docs/jitsi.md
![image](https://github.com/element-hq/element-web/assets/5144838/7df068b6-3f2f-4dd6-a24e-896c45f33c48)
configured like that on my nginx :
```
                location /.well-known/matrix/client {
                        add_header Access-Control-Allow-Origin "*";
                        add_header Content-Type "application/json";
                        return 200 '{"im.vector.riot.jitsi": {"preferredDomain": "your.jitsi.example.org"}}';
                }
```
i see the request going to my homeserver when starting Element desktop:
`"GET /.well-known/matrix/client HTTP/2.0" 200 70 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.53 Chrome/118.0.5993.144 Electron/27.1.2 Safari/537.36"`

But still going to default one

#### What did you expect?
Change jitsi server

#### What happened instead?
Still default jitsi server

### Operating system

Windows

### Application version

Element Desktop 1.11.53

### Homeserver

Synapse 1.98.0

### Will you send logs?

No

**Comment by t3chguy** [comment] 2024-01-11 16:42
Duplicate of https://github.com/element-hq/element-desktop/issues/816

**Closed by t3chguy** 2024-01-11 16:42 UTC
Labels: T-Defect, S-Minor, A-Config, A-Jitsi, X-Needs-Investigation, O-Uncommon
