### ISSUE TITLE
Error message when starting 

### ISSUE THREAD

**Issue by janvlug** [element-hq/element-web#27792] opened 2024-07-20 08:12 UTC
### Steps to reproduce

I tried to start Element Web and got an error message. I did not write the error down, but I have the option to submit debug reports. Creating this issue to attach the debug logs to.

### Outcome

Element to start normally.

### Operating system

Linux Fedora Wayland

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2024-07-20 20:58
Duplicate of https://github.com/element-hq/element-desktop/issues/1077

**Closed by t3chguy** 2024-07-20 20:58 UTC
Labels: T-Defect, S-Major, O-Uncommon
