### ISSUE TITLE
Jumping to oldest unread message doesn't load timeline properly

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-web#22989] opened 2022-08-04 10:04 UTC
### Steps to reproduce

1. Find a room with ~100 unread messages
2. Click on ^ to go to oldest unread message

#### What did you expect?
Jump to oldest unread message

#### What happened instead?
Timeline goes blank, 1-3 messages load, timeline goes blank, 1-3 different messages load, and so on for at least a few minutes.

### Browser information

Chromium 103.0.5060.134 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: fc6c859976b3-react-ed8ccb5d8007-js-d867affc40fb Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment] 2022-08-04 10:05
Related https://github.com/vector-im/element-web/issues/21922 https://github.com/vector-im/element-web/issues/20927

**Comment by turt2live** [comment] 2022-08-05 03:05
This sounds like it might be a duplicate of https://github.com/vector-im/element-web/issues/22123

**Closed** 2024-11-25 16:21 UTC
Labels: T-Defect, S-Minor, A-Timeline, X-Needs-Investigation, O-Uncommon, A-Timeline-Jumpy-Scroll
