### ISSUE TITLE
Un-favouriting room in room list is very unresponsive

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#28154] opened 2024-10-04 14:39 UTC
1. From a "Favourite" room in the room list, open the three-dots menu: 
![image](https://github.com/user-attachments/assets/38e173a3-3f4f-4a87-a5c5-cdab3e7d444b)
2. Click "Favourited" to un-favourite
3. nothing happens
4. wait
5. wait
6. wait
7. It suddenly disappears from the favourites list

**Comment by t3chguy** [comment] 2024-10-04 14:40
Duplicate of https://github.com/element-hq/element-web/issues/14302

**Closed by t3chguy** 2024-10-04 14:40 UTC
