### ISSUE TITLE
After clicking on a permalink, scrolling jumps between two points repeatedly without interaction

### ISSUE THREAD

**Issue by anoadragon453** [element-hq/element-web#27986] opened 2024-09-02 10:37 UTC
### Steps to reproduce

1. Click on a permalink in a room, I clicked on https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$p6UI8x_QAZKYU3wb2S_1MLnIWl-laZC2MdHVsDPcNrw
2. Watch the timeline jump up and down

[Screencast from 2024-09-02 11-33-06.webm](https://github.com/user-attachments/assets/d7695980-34a1-4aed-a8d6-92af04dceb6a)

(I usually keep Element on a vertical monitor, but the timeline continued to jump even after moving it over to a horizontal monitor.)

#### What did you expect?

To jump to the message and that be it.

#### What happened instead?

The client jumped up and down repeatedly without any user interaction.

### Operating system

NixOS Linux

### Application version

Element version: 1.11.74 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

From https://github.com/NixOS/nixpkgs/

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by MidhunSureshR** [comment] 2024-09-03 11:16
I think this is because of message loading above/below the target messages?

**Comment by t3chguy** [comment] 2024-09-12 10:47
Duplicate of https://github.com/element-hq/element-web/issues/26080

**Closed by t3chguy** 2024-09-12 10:47 UTC
Labels: T-Defect, S-Minor, A-Timeline, O-Occasional
